### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by arunsai123** [tsujan/Kvantum#102]
**Transparent background for KDE settings application** 
If possible please add transparency hack for kde settings like dolphin.
Thank you.

**Comment by tsujan** [comment]
You mean systemsettings5? I don't think that's possible because systemsettings has its internal style. On the other hand, I don't want to bloat Kvantum's exception list.

BTW, Qt-5.7 has some bugs/regressions about window translucency. If you encounter them, disable window transluceny with Kvantum Manager.

**Comment by arunsai123** [comment]
yes systemsettings5 . 
thanks for the info
