### ISSUE TITLE
Strange blur behavior on context menus (maybe more)

### ISSUE THREAD

**Issue by Stunnerer** [tsujan/Kvantum#1025]
Fedora 41, Plasma 6.2.3, Kvantum 1.1.2, Qt 6.8.0
Using any blurred theme (tested on two different by different authors), context menus blur behaves weirdly - opaque background being removed only after hovering on active elements (so decorations never get blurred)

Examples in Dolphin:

Window:
1. Right-clicking anywhere except burger-menu - blur is broken
2. Left-clicking on burger-menu - blur is broken
3. Right-clicking on burger-menu - blur works as expected

Maximized (details tab open):
1. Right-clicking anywhere - blur works as expected
2. Left-clicking and then right-clicking - blur is broken

Maximized (details tab closed):
1. Left-clicking and then right-clicking - blur works as expected

Screencast:

https://github.com/user-attachments/assets/ccdd6d29-af65-49fe-9814-6b210f339e25

**Comment by tsujan** [comment]
That isn't about blurring itself but translucency. Please read https://github.com/tsujan/Kvantum/releases/tag/V1.1.3 .

In short, that's a regression in Qt 6.8, and the latest version of Kvantum already includes an efficient workaround for it. The problem was much worse than in your video, and I couldn't wait for Qt devs to fix it ;)

Anyway, thanks for your attentions!

**Comment by Stunnerer** [comment]
Yes.
Built and installed 1.1.3, it fixed the issue, thanks!

**Comment by tsujan** [comment]
Good :)

I encountered this Qt regression, in LXQt+kwin_wayland as well as Labwc and Wayfiire, when Qt 6.8 came into Arch. Sadly, it isn't reported; I don't know how to report it either, because they usually want a "sample code", which doesn't make much sense in this case.
