### ISSUE TITLE
PartitionManager partition visualizer shows as window color

### ISSUE THREAD

**Issue by AnotherBugworm** [tsujan/Kvantum#105]
It works okay on both breeze and qtcurve, but on kvantum is just colored like window(or base) color
Breeze
![screenshot_20161107_131850](https://cloud.githubusercontent.com/assets/7214361/20057041/e9db5e9e-a4f1-11e6-99c9-4af5e4174059.png)
Kvantum
![screenshot_20161107_135121](https://cloud.githubusercontent.com/assets/7214361/20057042/e9dd2f8a-a4f1-11e6-8682-2538ec5614e2.png)

**Comment by tsujan** [comment]
Thanks for reporting! I'll look into it.

**Comment by tsujan** [comment]
Fixed by https://github.com/tsujan/Kvantum/commit/754c1611655e28bf55071d1532aee1487c0d6987

Actually it was a bad styling method in KDE Partition Manager and caused that problem only in Kvantum because Kvantum is SVG-based.

KDE Partition Manager may still have other bad methods. Please tell me if you encounter a color problem in another part of it! Thanks in advance!
