### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by AnotherBugworm** [tsujan/Kvantum#106]
The problem is connected with frames, they are drawn layers in some situations. For example this(check it in zoom):
![screenshot_20161109_031047](https://cloud.githubusercontent.com/assets/7214361/20123903/235b3e8e-a62b-11e6-95c4-5f3b13c11aa6.png)
Look at the shadows, left shadow seems strange. Same svg, left window is a toolbar with frame.bottom=7, right window is a toolbar with frame.bottom=6. Middle is actually what I want, so nvm. Another example, it's a lineedit.
![screenshot_20161109_032823](https://cloud.githubusercontent.com/assets/7214361/20124100/9a20bd04-a62c-11e6-8bf8-6207d6b594ae.png)
It have one color for all surface but we see strange lines. frame.top/bottom=4 and left/right=2

**Comment by tsujan** [comment]
Although I didn't understand your description, I'm pretty sure that the problem is in the config and/or SVG file. Please give me a link to your theme (from dropbox or somewhere else) to see what's wrong (tomorrow, perhaps)!

**Comment by AnotherBugworm** [comment]
https://drive.google.com/file/d/0B51MheNYkDBORkZGUXFPUzdUZW8/view?usp=sharing
On first screenshot you can see that the same svg renders with spaces when it have frame.bottom=7(left). I did another screenshot to show it more clearly, it's hard to see in normal scale, but with zooming it can be seen pretty clearly
![screenshot_20161109_035803](https://cloud.githubusercontent.com/assets/7214361/20124683/eee22874-a630-11e6-8605-b1b76ab71a25.png)

**Comment by AnotherBugworm** [comment]
Looks like example with lineedit is my mistake

**Comment by tsujan** [comment]
Kvantum is tested by many theme makers (including me) in making very different themes since it was started. You could rely on the fact that it does exactly what you tell it to do. `Theme-Config.pdf` and `Theme-Making.pdf` should answer all of your questions. If not, please tell me to add the missing info to it! I update those docs whenever needed.

Contrary to other theme engines, no one can make a Kvantum theme at once. It's like sculpture: you "carve out" your theme little by little until it seems complete. I haven't completed any theme in less than two days and usually, I have to fix it the day after ;)

I know that you've just started this theme but I think it's good to mention two things:

(1) Without `inherits=PanelButtonCommand` under `[LineEdit]`, the interior and frames of *the default theme* are used in your theme. I'm sure you don't want that. Please read the explanation in `Theme-Config.pdf`, after its first table!

(2) You have no state specific text color in your theme. Please read `Theme-Config.pdf` -> `Variables Table` -> `text.normal.color` and the items below it.

**Comment by tsujan** [comment]
I forgot to say this:

Frame margins are *forced* by Kvantum; Qt doesn't have such a concept. Now, frame margins are respected in most places but not in all widgets. For example, *for technical reasons*, all toolbar frame margins are equal to the maximum margin set in the theme config. If you set
````
frame.bottom=0
frame.right=7
frame.left=0
frame.top=0
````
under the [Toolbar] section, the margin will be 7 in all directions. Moreover, in some cases, toolbar and menubar depend on each other; etc.

I'll add this info to the doc if it's missing.

**Comment by tsujan** [comment]
This is a modified version of your theme: https://dl.dropboxusercontent.com/u/7793460/MaterialDesign.tar.gz

I didn't fix all issues though. The theme needs a KDE color scheme too.

A few points:

(1) You should be careful when you use backgrounds that have high contrast with the window color. Qt doesn't support high contrast in all places. As it's written in `Theme-Making.pdf`,

"... apart from textless widgets, only the interior elements of those widgets that accept state-specific text colors can have a high contrast with the window or base background".

And as it's written in `Theme-Config.pdf`,

"State-specific text colors do not have meaning for Window, Dialog, Dock, *LineEdit*...."

Therefore, if you give lineedits a dark background while your window background is `#fafafa`, you could expect unreadable texts.

(2) `inherits=xxx` is an important line in many places.

(3) You could see that, with the changes I made to colors, the Breeze icon theme gives the correct color to the "symbolic" icons (on toolbars and menubars).

**Comment by AnotherBugworm** [comment]
This theme is actually in early state and I used my dark theme as the basis, so many stuff looks unreadable now

**Comment by tsujan** [comment]
> This theme is actually in early state

I know. That's normal at early stages, and making light-and-dark themes isn't easy. You could consult KvAmbience or KvFlatLight (I do so myself sometimes).

Sorry for one wrong comment above (corrected later) and looking forward to your new theme :)
