### ISSUE TITLE
Progressbar text status

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#107]
I create some themes and progressbar not show text status. 
It's very strange, because on Dolphin text status on progressbar showing:
![image](https://cloud.githubusercontent.com/assets/8083855/20214187/9c7a3a60-a81d-11e6-857b-cfbb1953e148.png)
But on KTorrent not:
![screenshot_20161111_015126](https://cloud.githubusercontent.com/assets/8083855/20214123/3ca4a742-a81d-11e6-84f9-c4585f9715f9.png)
Please help how fix this 
Theme:
[ArcDarkTransparent.zip](https://github.com/tsujan/Kvantum/files/585701/ArcDarkTransparent.zip)

**Comment by tsujan** [comment]
You have `progressbar_thickness=14` in your theme and, as is explained in `Theme-Config.pdf` under "progressbar_thickness": 
````
Note: If it is positive but less than the height of the progressbar text, the text will not be shown.
````
Dolphin's bar isn't a progressbar but a "KCapacityBar". KCapacityBar doesn't follow the setting for `progressbar_thickness` and always has text. That's intentional because the info on KCapacityBar is important.

**Comment by varlesh** [comment]
Big thx :+1:

**Comment by tsujan** [comment]
You're welcome!
