### ISSUE TITLE
Some feature request

### ISSUE THREAD

**Issue by samuaz** [tsujan/Kvantum#109]
Hi Tsujan,
Thanks for the hard work. 

can be possible to add a hack or something to hide/show as normal or personalize the alert messages like this (the red frame that say: "bluetooth esta desactivado"):  

![screenshot_20161213_235152](https://cloud.githubusercontent.com/assets/1245839/21318815/877b8ecc-c5e9-11e6-85b5-4665982c0ce7.png)

that frame broke the theme and design and the other request is the option to hide the icons in dialog windows like the root password promp to make it a more minimalistic :

![screenshot_20161214_005029](https://cloud.githubusercontent.com/assets/1245839/21318866/bcfca2d4-c5e9-11e6-8f8b-0d451b3f8903.png)

and other question is possible the add compatibility to the qsvgstyle theme builder? or something like that for people that no have experience with vectors. 

thanks!!

**Comment by tsujan** [comment]
Hi,

Some apps have hard-coded styles, so that parts of them cannot be drawn by style engines. For example, ksysguard has some hard-coded colors. I think the red frame in your screenshot has the same story: it should be inside the code.

I agree that adding colors/styles to an app code can be a bad practice but, unfortunately, many developers do so and nothing can be done by Kvantum in such cases.

BTW, what are those dialogs? Are they KDialog?

**Comment by tsujan** [comment]
> other question is possible the add compatibility to the qsvgstyle theme builder?

No, it isn't possible. Kvantum and qsvgstyle are so much different from each other.

Making Kvantum themes requires SVG skills and a lot of patience ;) I've never finished a theme in less than a day. This is what is paid for high flexibility.
