### ISSUE TITLE
DEBIAN packaging

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#110]
@tsujan Hi, i see you create deb-package for kvantum. Will be good if you help me and post your debian packaging? Because i'm not found **debian** folder on kvantum project.

PS: We create PPA for pack [arc-kde](https://github.com/PapirusDevelopmentTeam/arc-kde) and kvantum depend for this...

**Comment by tsujan** [comment]
Hi,

This is the debian folder I use for deb packaging: https://www.dropbox.com/s/zcgvmhiitctyb8o/debian.tar.xz?dl=0

I think you only need its `rules` file, which is for both Qt4 and Qt5 -- I don't like to split packages in the Debian way ;) Dropbox doesn't need sign-in for downloading but if you encounter any problem, I could copy/paste the `rules` file here.

The debian folder isn't included in the source because I don't want any distro to seem privileged.

BTW, V0.10.4 will be published soon because important translucency issues are fixed by some commits after V0.10.3.

**Comment by varlesh** [comment]
Big thx!!!

**Comment by tsujan** [comment]
You're welcome!

**Comment by varlesh** [comment]
I want your awesome engine by default on KDE :)

**Comment by tsujan** [comment]
Thanks! Glad to know you enjoy it!

**Comment by varlesh** [comment]
@tsujan It's possibe change path to qmake-qt for universal arch?
```
cd builddir && /usr/lib/x86_64-linux-gnu/qt4/bin/qmake PREFIX=/usr ../$(APPNAME).pro
cd builddir && /usr/lib/x86_64-linux-gnu/qt5/bin/qmake PREFIX=/usr ../$(APPNAME).pro
```
For qmake-qt4 i found /usr/bin/qmake-qt4 but what doing with qmake-qt5?

**Comment by tsujan** [comment]
Oh sorry, the debian folder was only for 64-bit! I don't know if there's an arch-dependent path. Moreover, some systems may not have `/usr/bin/qmake-qtX`.

However, there is another possibility: I added CMake support a while ago. You could rely on cmake instead of qmake (see INSTALL). I still don't know of any way to use cmake for both Qt4 and Qt5 but, with cmake, no path is needed. I'll think about a cmake-based `rules` file for both Qt4 and Qt5 when I find some free time -- but I don't know yet if it's possible.

**Comment by varlesh** [comment]
We now try this variant:
ARCH := $(shell uname -m)
```
cd builddir && /usr/lib/$(ARCH)-linux-gnu/qt4/bin/qmake PREFIX=/usr ../$(APPNAME).pro
cd builddir && /usr/lib/$(ARCH)-linux-gnu/qt5/bin/qmake PREFIX=/usr ../$(APPNAME).pro
```

**Comment by tsujan** [comment]
> We now try this variant...

Please tell me if it works!

**Comment by varlesh** [comment]
not worked :( this added i686
```
dpkg-buildpackage: source package kvantum
dpkg-buildpackage: source version 0.10.3ubuntu16.04.1
dpkg-buildpackage: source distribution xenial
 dpkg-source --before-build kvantum-0.10.3ubuntu16.04.1
dpkg-buildpackage: host architecture i386
 fakeroot debian/rules clean
dh_testdir
dh_testroot
rm -f build-stamp
# Add here commands to clean up after the build process.
rm -rf builddir
dh_clean
dpkg-buildpackage: warning: debian/rules must be updated to support the 'build-arch' and 'build-indep' targets (at least 'build-arch' seems to be missing)
 debian/rules build
mkdir -p builddir
cd builddir && /usr/lib/i686-linux-gnu/qt4/bin/qmake PREFIX=/usr ../kvantum.pro
/bin/sh: 1: /usr/lib/i686-linux-gnu/qt4/bin/qmake: not found
debian/rules:14: recipe for target 'builddir/Makefile' failed
make: *** [builddir/Makefile] Error 127
dpkg-buildpackage: error: debian/rules build gave error exit status 2
```

**Comment by tsujan** [comment]
Let's reopen this until we find a solution (although it isn't about a bug)!

**Comment by varlesh** [comment]
This worked:
```
#!/usr/bin/make -f
# -*- makefile -*-

# Uncomment this to turn on verbose mode.
#export DH_VERBOSE=1

ifeq ($(DEB_BUILD_ARCH),amd64)
ARCH:=x86_64
else
ARCH:=i386
endif

APPNAME := kvantum

builddir:
	mkdir -p builddir

builddir/Makefile: builddir
	cd builddir && /usr/lib/$(ARCH)-linux-gnu/qt4/bin/qmake PREFIX=/usr ../$(APPNAME).pro

build: build-stamp

build-stamp: builddir/Makefile
	dh_testdir
	# Add here commands to compile the package.
	cd builddir && $(MAKE)
	touch $@

clean:
	dh_testdir
	dh_testroot
	rm -f build-stamp
	# Add here commands to clean up after the build process.
	rm -rf builddir
	dh_clean
install: build
	dh_testdir
	dh_testroot
	dh_clean -k
	dh_installdirs

	# Add here commands to install the package into debian/your_appname
	cd builddir && $(MAKE) INSTALL_ROOT=$(CURDIR)/debian/$(APPNAME) install && $(MAKE) distclean
	# Recompile against Qt5
	cd builddir && /usr/lib/$(ARCH)-linux-gnu/qt5/bin/qmake PREFIX=/usr ../$(APPNAME).pro
	cd builddir && $(MAKE) INSTALL_ROOT=$(CURDIR)/debian/$(APPNAME) install && $(MAKE) distclean
# Build architecture-independent files here.
binary-indep: build install
# We have nothing to do by default.

# Build architecture-dependent files here.
binary-arch: build install
	dh_testdir
	dh_testroot
	dh_installdocs
	dh_installchangelogs
	dh_installexamples
	dh_installman
	dh_link
	dh_compress
	dh_fixperms
	dh_installdeb
	dh_shlibdeps
	dh_gencontrol
	dh_md5sums
	dh_builddeb

binary: binary-indep binary-arch
.PHONY: build clean binary-indep binary-arch binary install configure

```

**Comment by varlesh** [comment]
@tsujan packages builded on Launchpad farm. For example:
https://launchpad.net/~papirus/+archive/ubuntu/arc-kde/+packages

**Comment by varlesh** [comment]
Also i'm delete versions for depends on **control**:
```
Depends: ${shlibs:Depends}, ${misc:Depends}, libqt5core5a, libqt5gui5, libqt5svg5, libqt5widgets5, libqt5x11extras5
```

**Comment by tsujan** [comment]
Great! I can refer Ubuntu users to Launchpad's papirus page for the latest Ubuntu. 

I'm still thinking about a cmake variant.

**Comment by varlesh** [comment]
I think better create autobuilding PPA for stable releases  - it's easy for development (you don't build packages manually) 
For example, if available new release tag > build new releases on PPA. This worked with bzr, recipe and github... but i don't know how doing this (i'm not good maintainer).
More you found here:
https://help.launchpad.net/Packaging/SourceBuilds/Recipes

**Comment by tsujan** [comment]
> I think better create autobuilding PPA for stable releases...

You're right but, since I migrated from Debian to Manjaro (Arch based), it isn't easy for me to work with Debian based systems anymore -- Arch and Debian being so different in packaging. With every release, I added 2 deb packages (build manually and tested on VirtualBox) just for those Ubuntu/Debian users who want to try Kvantum without hassle. However, if your Launchpad packages are made soon after every release, I could add a link to them instead. *But I don't want to bother you with that*. If, someday, you find an easy solution, please tell me!

**Comment by varlesh** [comment]
Launchpad builded this packages - not you. You already have DEBIAN folder, need install only bzr (i think from AUR) and upload this debian folder to launchpad. Create recipe and etc...
@SmartFinn you can help with that?

**Comment by varlesh** [comment]
our kvantum packages not autobuilded - i'm upload changelog with debian for every Ubuntu release... It's not comphortable for you and me, because we need upload packages with new release everytime. Need create autobuild PPA from release tag on github

**Comment by tsujan** [comment]
> It's not comfortable for you and me...

OK! Thanks for the info!

With Kvantum, FeatherPad, FeatherNotes and especially, LXQt, I don't think I have enough time to do that. But, who knows, I may do it sometime 😃

**Comment by SmartFinn** [comment]
> create autobuilding PPA for stable releases

It's impossible now, but you can disable daily builds and run build manually for stable release.

> need install only bzr

bazzar is not needed, Launchpad supports git. 

Auto-build on Launchpad it pretty easy:

1. Create a project https://launchpad.net/projects/+new
2. Create a mirror with automatically import from GitHub  to the project https://code.launchpad.net/+code-imports/+new
3. Create git branch packaging on GitHub with your `debian` directory only. Otherwise you can create branch on code.launchpad.net too.
4. Create a recipe like this:

```
# git-build-recipe format 0.4 deb-version {debupstream}-r{revno}+pkg{revno:packaging}
lp:~tsujan/kvantum master
merge packaging lp:~tsujan/kvantum packaging
```

Examples:
Packaging branch https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/tree/packaging
Mirror of the project https://code.launchpad.net/~papirus/papirus-icon-theme/+git/master
Repice https://code.launchpad.net/~papirus/+recipe/papirus-icon-theme-daily

Docs: https://help.launchpad.net/Packaging/SourceBuilds

**Comment by stevenpusser** [comment]
I've also built some kde-style-kvantum Ubuntu packages on the openSUSE build service (free and very easy to join).  It's possible to use it to build and host repositories for quite a few distros, but the only ones I know how to do are the deb ones, using Debian-style source packages. I know that the source package format has to be different if you want to build for both rpm and deb from one set of sources, though:  

mine:  https://build.opensuse.org/package/show/home:stevenpusser:kvantum/kde-style-kvantum

a "universal" set for smplayer: https://build.opensuse.org/package/show/home:smplayerdev/smplayer

I called it kde-style-kvantum in order to be like similarly named packages already in Debian, but am not married to that name.

**Comment by tsujan** [comment]
@stevenpusser 
Thanks for the links!
it's really good to know that there are good deb packages for Kvantum. For the following reasons, the only deb package I'll make with every release will be for Ubuntu LTS:

Although I was a Debian user for 9 years and, before that, an Ubuntu user for 2 years, I'm far from Debian-based systems now, having migrated to Manjaro, which is Arch based. Because of that, making deb packages wasn't easy for me; every time, I had to restart into Debian, try to upgrade it, resolve conflicts that happened almost always, wait for about an hour for the upgrade process to finish (yes, just the process, not the download, and that on a powerful laptop -- deb packages are very slow).... So, I stopped torturing myself ;) However, I try to have an updated Kubuntu LTS on VirtualBox to make a single deb package for it with every new release.

**Comment by stevenpusser** [comment]
That's what's nice about the OBS that builds and hosts those packages--it spins up a pbuilder virtual machine from scratch for each platform that I specify for every build, so I don't necessarily have to have any of those installed on my machine at all.  Pretty much like a PPA, I gather, but not just for Ubuntu. I do have to generate the source packages on a Debian-type install on my own machine, though.

**Comment by tsujan** [comment]
Closing this because I don't have Debian anymore and there are good deb packages. The only installable package attached to every release will be a deb package for Ubuntu LTS, which I'l make on VirtualBox; PKGBUILD files for Arch and Manjaro are already added to the source and rpm hasn't been my territory for a long time.
