### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by AnotherBugworm** [tsujan/Kvantum#113]
All qt apps just core dumps while using kvantum with wayland, plasma refuse to work with it. breeze, qtcurve and other styles works fine

**Comment by tsujan** [comment]
Thanks for reporting!

I'll look into it but I'm not surprised: Kvantum depends on x11 for some of its features and workarounds. A mechanism should be added for x11 detection, so that in its absence, those features/workarounds are disabled.

However, first of all, I should set up a light wayland DE for testing. I think Enlightenment is ideal.

**Comment by tsujan** [comment]
Done! Now Kvantum shouldn't crash on wayland.

x11drag should work on wayland (it's independent of x11 on wayland) but, due to the poor wayland support of Qt, it may not work.

BTW, trying wayland was a disappointing experience to me. After years of development, it's still *very* unstable and I don't think it'll be stable soon.

**Comment by AnotherBugworm** [comment]
KDE is unusable right now, I'm just testing it time to time. I'll check it later, thanks

**Comment by tsujan** [comment]
Actually, your report helped me find an easy way to prepare programs for Wayland (by using Weston)  :)

**Comment by AnotherBugworm** [comment]
Works fine, thanks! I have a question - windows decoration are red in my theme, I suppose I can change this, which variable is responsible for this?
![wayland-screenshot](https://cloud.githubusercontent.com/assets/7214361/23359592/99106512-fcef-11e6-9df6-1feb8e7c52b2.png)

**Comment by tsujan** [comment]
> indows decoration are red in my theme, I suppose I can change this, which variable is responsible for this?

I think Weston uses the highlight color to draw that decoration. It's form isn't under Qt's control.
