### ISSUE TITLE
Archlinux AUR

### ISSUE THREAD

**Issue by omni6** [tsujan/Kvantum#139]
For a while now i am messing around with a broken [PKGBUILD ](https://aur.archlinux.org/packages/kvantum-tools-qt5-svn). 
If i update kvantum i have to makepkg this package with my modified PKGBUILD to get it compiled. 
Now i found a very well written single PKGBUILD in your git repository. I think it would be very handy if you upload this PKGBUILD to AUR.

Could you be so nice please?

**Comment by tsujan** [comment]
Glad to know that the PKGBUILDs work fine for you! @Lekensteyn was so kind and fixed some problems in them (https://github.com/tsujan/Kvantum/pull/124).

Formerly a Debian user, I migrated to Manjaro (Arch based) not a long time ago, so I'm not familiar with the way PKGBUILDs are uploaded to AUR yet. For example, I don't know if a Manjaro user is allowed to upload anything (I chose Manjaro because I didn't have time to install Arch manually; otherwise, the two systems are almost identical). This was one of the reasons why I included the PKGBUILDs in Kvantum. The other reasons were that (1) there are 2 PKGBUILDs per Qt's major version, one with cmake and the other with qmake, and (2) AUR already had Kvantum PKGBUILDs (although I never tried them, so I didn't know they were broken).

However, I'd be very grateful if anyone familiar with AUR could choose between cmake and qmake and then, upload the corresponding PKGBUILDs (for Qt4 and Qt5) to AUR.

**Comment by omni6** [comment]
done..

**Comment by omni6** [comment]
but why we need qt4 version?

**Comment by tsujan** [comment]
> done..

Thank you very much! So, you preferred cmake.

> but why we need qt4 version?

You're right. We don't need Qt4 on Arch. I've kept Qt4 compatibility for users of Ubuntu LTS and Debian Stable. Sooner or later, I'll remove it and use c++11.

**Comment by omni6** [comment]
i simply prefer cmake because its more common. personally never used qmake... 
no need to thank, i am more than happy that my updates now running without errors. 
i have to thank you for your great project!

**Comment by omni6** [comment]
btw i am working on a german translation. coming soon...

**Comment by tsujan** [comment]
> btw i am working on a german translation. coming soon...

Looking forward to it.

**Comment by tsujan** [comment]
@omni6 
IMO, a `kvantum-qt5-git` is also needed in AUR  for the latest git version. I tried https://aur.archlinux.org/packages/kvantum-qt5/ with `pacaur` and it installed the old version `0.10.4`, of course. The PKGBUILDs included in Kvantum always install the latest git version, which often has new features/fixes and is 99% stable.

**Comment by tsujan** [comment]
On second thought, I updated INSTALL to inform Arch users that they could install the latest *released version* with `pacaur` and if they wanted to install the latest *git version*, they could use the included PKGBUILDs. So, there may be no need to a `kvantum-qt5-git`...

**Comment by omni6** [comment]
i thought the same already...
the problem in the original script was that when the version gets automatically updated the users wont be notified when a new verision is available. so it was like a git package. 
 i will write the pkgbuild for the git version later today.

so you have the latest tagged release and origin:master package

**Comment by omni6** [comment]
ah fast read... i think the most people wont look in the git repo for pkgbuilds... almost everyone uses octopi or pamac, at least yaourt or pacaur (ok not the oldschool arch people, but them can write theirselves..).

**Comment by tsujan** [comment]
> i think the most people wont look in the git repo for pkgbuilds

I agree. The included PKGBUILDs just serve as the last resort ;)

**Comment by tsujan** [comment]
With the included PKGBUILD, I get `kvantum-qt5-0.10.5+g82994bcadc-1-x86_64.pkg.tar.xz`, which is the last commit (but one -- I made it before the last commit). Does a similar thing happen with [yours](https://aur.archlinux.org/packages/kvantum-qt5-git/)? (sorry, I can't check right now, being very busy).

**Comment by tsujan** [comment]
I mean: Is the `pkgver` automatically updated with new commits?

**Comment by tsujan** [comment]
Yes it is updated :) Sorry for the silly question! Will include the new info in INSTALL.

**Comment by tsujan** [comment]
Updated INSTALL. Now, everything is perfect for Arch, thanks to your work :)
