### ISSUE TITLE
Krusader search text color

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#164]
On search used black text:
![image](https://user-images.githubusercontent.com/8083855/31051925-f54f6012-a686-11e7-9954-37281c3c35f1.png)

Kvantum git-version 20170929
Krusader 2.6.0

**Comment by tsujan** [comment]
Have you applied the KDE color scheme that corresponds to that Kvantum theme? I ask because some KDE apps use the KDE color scheme instead of Qt palette colors.

**Comment by varlesh** [comment]
I apply Breeze colorscheme with default Kvantum theme - text anyway use black color on search

**Comment by varlesh** [comment]
With Breeze engine and Breeze Dark color scheme:
![image](https://user-images.githubusercontent.com/8083855/31051972-65819d4a-a688-11e7-980c-e15566a2463f.png)

**Comment by tsujan** [comment]
Please apply the color scheme "Kvantum" with the default Kvantum theme and report back! (Close and reopen Krusader after that.)

**Comment by varlesh** [comment]
Kvantum Theme & Kvantum colorscheme:
![image](https://user-images.githubusercontent.com/8083855/31051993-c1ff6a84-a688-11e7-8e3a-c59586af6cec.png)

**Comment by varlesh** [comment]
@tsujan See tabs too draw with another style

**Comment by tsujan** [comment]
I just installed Krusader and saw it. My guess: Krusader uses a custom background color for that line-edit -- which is a bad design -- while Kvantum uses its (dark) SVG element -- which is correct. I'll see if I can add a workaround for such strange cases.

Thanks for reporting!

**Comment by tsujan** [comment]
OK, I found the cause: The lines that come after the following line in Krusader's source file `krsearchbar.cpp`:
```cpp
QColor fore = Qt::black;
```
It's supposed that if the background color of that line-edit is set correctly, the text will be readable with all styles but Kvantum uses an SVG background for line-edits instead of colors. In such cases, the drawing should be hard-coded (although I don't understand why there are so many custom colors in Krusader!!).

No simple workaround is possible in Kvantum. However, you could change that color by going to Krusader's settings dialog → Colors → Colors → Other tab and changing `Quicksearch, match foreground` and `Quicksearch, non-match foreground` to white. See this screenshot:

![colors](https://user-images.githubusercontent.com/981076/31063467-fdc86874-a73f-11e7-8d49-068e0b4e4b22.png)

**Comment by varlesh** [comment]
Thx for clarification. I don't understand too why needed this more colors ;) But it's nevertheless this decision

**Comment by tsujan** [comment]
Even Krita doesn't need so many colors ;) The word "overkill" is for such cases.

Generally, it isn't a good idea to define colors of complex widgets in the app code but if they're defined, the code should also provide a hard-coded style for drawing those widgets and such widget would often look ugly. Fortunately, Krusader has a detailed color setting that compensates for this problem.
