### ISSUE TITLE
Disabled Button Color in Toolbar

### ISSUE THREAD

**Issue by 2yangk23** [tsujan/Kvantum#182]
![screenshot_20180218_235704](https://user-images.githubusercontent.com/7710340/36367519-dcb294e4-1507-11e8-9c38-14e9e41d84ab.png)

You can see in the screenshot, "Back" is enabled. "Forward" is disabled. However, the arrow for "Forward" is black instead of gray. I tried a bunch of things and no matter what, it seems this arrow is getting its color from "window.text.color". Not directly, but if I change window.text.color to something that isn't black, then I can get the arrow to be gray. However, this also causes all the other text to change colors as well. In the screenshot below, I set "window.text.color=red". You can see the arrow is not black anymore, but all the text is red now.

![screenshot_20180219_000316](https://user-images.githubusercontent.com/7710340/36367609-4e1cbe16-1508-11e8-9c84-3fd7f84e46c8.png)

Is there somewhere I am supposed to be setting this instead?

**Comment by tsujan** [comment]
A very detailed explanation for future reference:

First, the term "symbolic SVG icon": it's an SVG icon with a single drawing that includes a stylesheet ("text/css") with a `.ColorScheme-Text` variable. Open a 16px Breeze icon in a text editor and you'll see that.

The KDE (or LXQt) methods of *colorizing symbolic SVG icons* is based on (1) the "icon mode" (selected/normal), (2) the global window text color, and (3) the global highlighted text color. If the widget reports its symbolic icon as being in the "selected" mode, the highlighted text color will be used for drawing its icon; if it reports its icon as being in the "normal" mode, the window text color will be used.

To enforce dark-and-light themes on `QStyle`, I tricked Qt into believing that the icons are in the selected mode on the dark toolbar of a light theme (while, actually, they should be in the normal mode). So, the symbolic SVG icons become light (= highlighted text color) on such a toolbar.

Now, *the disabled symbolic icons are always drawn by the window text color plus translucency.* That's how KDE (or LXQt) does it. So, the disabled icons are always dark on the dark widgets of a light theme.

Since the colors are added by KDE/LXQt, Kvantum can't do anything. However, there's no problem  because when a widget is disabled, you couldn't use it ;)

I emphasize that dark-and-light themes are *enforced* by Kvantum; they aren't something Qt/KDE supports easily. I think most KDE developers aren't aware of that possibility yet. Before Kvantum, Qt/KDE users were satisfied with either light or dark themes. When I came to Qt from the GTK world, I found that weird and decided to remove the obstacle in whatever way possible. Fortunately, there was a way.

I'm glad about -- and thank you for -- your attention to such details because, although I've wrestled with these problems for a long time, it's the first time they're mentioned explicitly.

**Comment by tsujan** [comment]
BTW, and for the sake of completeness, if curious people really like to see that disabled symbolic SVG icons are drawn by the window text color under KDE/LXQt, they could go to Kvantum → `Kvantum.cpp`, search for `Style::generatedIconPixmap` and replace all the lines inside the block `case QIcon::Disabled:` with:
```cpp
return pixmap;
```
That means Kvantum won't gray out the disabled icons. Then, they should recompile and install Kvantum, change the window text color in a dark-and-light theme and restart an app. Of course, the changes should be reverted after testing.

**Comment by CDrummond** [comment]
For Cantata's monochrome icons, I paint disabled icons using 35% opacity. Could Kvantum not do something similar? You could do this (or some other opacity level) for **all** icons, monochrome or not, for consistency? Just an idea - not an area of Kvantum's code that I really know...

**Comment by tsujan** [comment]
@CDrummond 

There's a Kvantum Manager option that I often use: Hacks → Opacity of disabled icons.

**Comment by CDrummond** [comment]
Ah, fair enough - don't have access to Kvantum at the moment.

However, (and this is just a question) why not always use this? Is there a reason why a user would not want this? If this is set, does it then use the same colour for disabled mono icons as for enabled ones, but just with a lower opacity?

**Comment by tsujan** [comment]
> However, (and this is just a question) why not always use this?

With colored icon sets, the graying-out functionality often does the job. I added that key a long time ago because, with the "new" symbolic icon code and under non-KDE environments, disabled symbolic icons weren't grayed out enough.

Since its effect depends on the icon set as well as DE and because different users might prefer different degrees of opacity for disabled icons, I set it to 100% by default. However, every theme can have its own value for it.

BTW and not related to this, the symbolic icon code (used by KDE) is incomplete, IMO. It's good to have symbolic icons with Qt but just working with the selection mode doesn't seem enough to me. Anyhow, I have no idea about a better code either -- I haven't looked into it yet ;)

**Comment by CDrummond** [comment]
Ah, yeah that all makes **perfect** sense. Kvantum has no way of knowing if the icon set is monochrome or not!

But, if a user sets disabled opacity != 100% - does Kvantum then use the same colour for disabled mono icons as for enabled ones, but just with a lower opacity? This would make sense to me - and again, would resolve the issue?

**Comment by tsujan** [comment]
> But, if a user sets disabled opacity != 100% - does Kvantum then use the same colour for disabled mono icons as for enabled ones

It uses whatever color KDE/LXQt gives to disabled symbolic icons, which is the window text color but grayed out. For enabled icons, it uses that highlighted text color if the icon is in selection mode and the window text color otherwise. Moreover, it tints the selected icons with the highlight color -- the tint can be removed by Kvantum Manager or the theme. With the mouse-over, icons have yet another optional tint.

Oh, now I remember! I learned the QStyle manipulation of symbolic icons from you. In an email, you'd suggested 2 ways and I chose the selection mode -- I don't remember the other way though.

**Comment by CDrummond** [comment]
Yeah - the selection is for when they are in a menu, so that selected icons have the same colour as the text.

Disabled icons are different, however. IMHO (and feel free to ignore, as you know more than me) if a theme/user has set "disabled icon opacity != 100%" then _disabled_ icons should be drawn the same as _enabled_ icons, just with an opacity set. (You could make this yet another option, but that'd be overkill (IMHO))

**Comment by tsujan** [comment]
> Yeah - the selection is for when they are in a menu

And, in Kvantum, wherever there's a high contrast. That makes symbolic icons visible in dark-and-light themes.

**Comment by CDrummond** [comment]
Perhaps then add an option to **not** change icon colouring, just opacity? e.g. 
```
Disabled opacity: 58%
[x] Grey disabled icons
```
Then setting `disabled opacity = (e.g.) 35 %` and `grey disabled = false` would resolve this issue?

**Comment by tsujan** [comment]
> ... would resolve this issue?

No, it wouldn't. The issue isn't in Kvantum and can't be worked around by it, as explained [above](https://github.com/tsujan/Kvantum/issues/182#issuecomment-366657296). The root of this "issue" is that dark-and-light themes aren't predicted by the KDE code for colorizing symbolic icons -- that code works at the `QIconLoader` and `QPlatformTheme` levels.

The visibility of disabled symbolic icons depends on the window text color and the color of the dark SVG elements of a light-and-dark theme. Even without graying-out, a black disabled symbolic icon can be on a black background.

An example of a light theme  whose disabled symbolic icons are visible on its dark toolbar "by chance":

![disabled](https://user-images.githubusercontent.com/981076/36664357-af473238-1af9-11e8-8e00-d7aa8297dba0.png)

**Comment by tsujan** [comment]
Wait a minute! This is only about KDE!

Actually, graying out is *useful* for the visibility of disabled symbolic icons under LXQt. This is KvAdapta under LXQt:

![lxqt](https://user-images.githubusercontent.com/981076/36665619-5090caa2-1afd-11e8-8547-1d33ac6d1704.png)

Of course, if I remove graying-out from the code, those disabled icons will be totally black but they are visible with the current code.

The same app with KvAdapta but under KDE:

![kde](https://user-images.githubusercontent.com/981076/36665704-88451ca0-1afd-11e8-9cc5-df1cf440c57d.png)

That's while we used the KDE code under LXQt, although with a modification by an LXQt developer -- maybe, that modification has fixed the problem (I'm not sure yet -- the modification in question was for something else) .

So, apparently, the culprit is KDE.

If you want to look into the LXQt code, see `libqtxdg` → `xdgiconloader.cpp` → `QPixmap ScalableFollowsColorEntry::pixmap`. I'd copied the KDE code there but the developer I mentioned above changed it -- we had quite a discussion about that.

**Comment by tsujan** [comment]
More precisely:

In the Qt source, `QIcon::pixmap()` calls `d->engine->pixmap()`, which either calls or ignores `Style::generatedIconPixmap()`, depending on the DE.

With KDE, `Style::generatedIconPixmap()` isn't called with symbolic icons (and only with them); hence the lack of graying-out for disabled symbolic icons and their invisibility on dark widgets of light themes. In LXQt, the call is done correctly, so that disabled icons are fairly visible on all widgets.

Actually, under KDE, "tinting label icons on mouse-over" doesn't have any effect on symbolic icons (and only on them) either because it's done inside `Style::generatedIconPixmap()`.

This is definitely a KDE issue. Since we don't know whether `Style::generatedIconPixmap()` is called or not, a workaround doesn't seem possible.

A bug report at KDE is needed but I don't have time for a discussion with them -- they could easily think there's no problem just because they can't see it with Breeze or Fusion and I have no time to explain all this to them (at least, not now).

**Comment by tsujan** [comment]
After some experiments, found and added an effective workaround: https://github.com/tsujan/Kvantum/commit/a833ca1c032a979500fdfe9be0b57b102b9c7d7c

Now, disabled icons of light-and-dark themes shouldn't be totally black under KDE.
