### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#186]
Hi, @tsujan.

I noticed that it is possible to apply colors for some elements, such as text, directly from the color scheme, which is very useful for those who want to create a more flexible theme with greater visual compatibility. Straight to the question: is there any way I can apply a color from the current color scheme to SVG elements? I would like to make a theme that follows the colors exactly as informed in the color scheme. For example: `[Colors: Button] -> BackgroundNormal` for the background of the button in normal state, etc.

If it's not possible, I've seen in some other issue that you don't want kvantum dependent on KDE , what do you think about [this](https://techbase.kde.org/Development/Tutorials/Plasma5/ThemeDetails#Using_system_colors) specs?

I'm glad to see the popularity your project has taken.

cheers

**Comment by tsujan** [comment]
Hi,

The colors of SVG elements (backgrounds) can be defined only in the SVG file (as an image), while various text colors should be defined in the `kvconfig` file appropriately. `base.color` is an exception because it's used by Qt in item-views. Also, if there's no window SVG element, `window.color` will be used.

As for the specs you mentioned, they are for KDE. Since KDE's styling capabilities is very poor compared to Kvantum's, Kvantum uses its own method for defining colors (as mentioned above) and enforces its colors as far as possible. So, no, KDE specs can't have any relevance here.

**Comment by tsujan** [comment]
And I forgot to add that SVG elements don't have mere "colors" -- they can have complex gradients.

**Comment by tsujan** [comment]
LOL! More and more things come to my mind. For example, KDE lacks most of the "inactive colors"; it can't handle buttons with high contrast to the window; it can't handle dark-and-light themes in general; SVG elements can even be PNG images; and so on and so forth...

**Comment by franksouza183** [comment]
I think I can suggest something. The only relevant function in this algorithm is the "text override" function (with regex?)
What about this (I skipped the practical algorithm class, feel free to correct me :D ):

```
[before delivering to QT]
If not cached {
If KDE_color_scheme_compatibility == true {
get current color scheme vars
}

If environment == KDE {
get_svg_element_in_plain_text_mode ();
override specific terms according to the table of variables acquired from the scheme
...
}

}
[delivery to qt]
```

**Comment by tsujan** [comment]
`get_svg_element_in_plain_text_mode()` is impossible because it's too elementary for Kvantum. Please take a look at some themes that come with Kvantum. I don't need to say anything about complex themes like `KvSimplicityTurquoise` (try its latest version and see how buttons change color when a window becomes inactive) or `KvCurves3d`; even Kvantum's default theme is impossible with those poor KDE colors.

I made Kvantum to go *beyond* KDE's ridiculous limitations, not to follow them ;)

**Comment by franksouza183** [comment]
> I made Kvantum to go beyond KDE's ridiculous limitations, not to follow them

Make sense. Thank you!

**Comment by tsujan** [comment]
BTW, `QtCurve` is still alive. Anyone who's satisfied with what KDE provides could use `QtCurve`. As far as I remember, it follows KDE's color scheme and if not, that could be reported to its developers.

**Comment by franksouza183** [comment]
Qtcurve has color integration with KDE, but is poorly customizable for details.
KVantun allows more detailed and liberal customization, but does not fully integrate with KDE colors.

Here's the dilemma that makes me decide for Kvantum

**Comment by tsujan** [comment]
There is a fundamental difference between the philosophy behind KDE's current styling and that of Kvantum. There was a time (KDE3) that KDE's styling was ahead of Qt's but now, it's far behind what `QStyle` can provide, mainly because QML is used by KDE and it can't have QStyle's flexibility. So, KDE's devs went for an elementary look, with disregard for UX. It's 2018 and Breeze can't have real translucency or custom gradients!

In contrast, Kvantum tries to actualize the full potential of QStyle, and more. Looking backward is not an option.
