### ISSUE TITLE
Different toolbar buttons?

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#19]
Is there any way to use different buttons (svg elements) on toolbars? If not, it would be nice to have some option to not use background in normal status.

**Comment by tsujan** [comment]
Toolbar buttons are often toolbuttons and, yes, they can have svg elements different from those of pushbuttons.
However, you don't need a different svg element for that purpose because toolbar buttons won't have any background for their normal state unless the key "group_toolbar_buttons" is intentionally set to true in a theme (see Theme-Config.pdf). That key is false by default and also in Kvantum's default theme. It's true in two of my other themes, namely KvDark and KvGray, for example.

**Comment by franksouza183** [comment]
Oh yes! Sorry, that's works!!

Thank you!!
