### ISSUE TITLE
Kvantum stack overflow in scroll_arrows

### ISSUE THREAD

**Issue by alexminder** [tsujan/Kvantum#196]
Hi,

One of my favorit application constantly crashes with Kvantum Qt style when I move mouse cursor over scroll bar.

Could you look at https://github.com/mujx/nheko/issues/297 how it is related to Kvantum? Especially, `Hawkheart` user comment.

**Comment by tsujan** [comment]
I'll look into it as soon as I find some time.

**Comment by tsujan** [comment]
Does the crash happen after you disable the transient scrollbars in Kvantum Manager and restart nheko?

I installed `nheko` from git but, since I got a matrix account for the first time (hadn't known about it before), I know of no chat room and can't see any scrollbar to test.

On the other hand, the provided backtrace clearly points to these lines:
```cpp
#if QT_VERSION >= 0x050500
    case SH_ScrollBar_Transient : {
      if (qobject_cast<const QGraphicsView*>(widget) && widget->hasMouseTracking())
        return false; // prevent artifacts in QGraphicsView
      return tspec_.transient_scrollbar;
    }
#endif
```
There's nothing in them to cause a crash. Moreover, the second comment on that page doesn't seem correct.

Anyhow, could you please tell me how can I see those scrollbars? A chat room I can join to see them?

**Comment by tsujan** [comment]
Never mind! I created a room and saw it. Disable transient scrollbars for now and it won't happen -- until I find the real cause.

**Comment by alexminder** [comment]
```
$ cat ~/.config/Kvantum/kvantum.kvconfig
[General]
theme=KvHybrid

$ grep transient_scrollbar ~/.config/Kvantum/KvHybrid/KvHybrid.kvconfig
transient_scrollbar=false
```
But nheko still crashes. And I don't see visual changes for scrollbar - it still transient for particular app. With other apps scrollbar not transient.
The issue happens with nheko only.

**Comment by tsujan** [comment]
Here, the crash only happens when transient scrollbars are enabled but the backtrace is very different from yours, maybe because I have the latest git Kvantum.

> it still transient for particular app. With other apps scrollbar not transient.

Some apps have hard-coded styles and don't follow Kvantum/Breeze/Fusion... You could test with a Qt5 app like Dolphin to see whether scrollbars are transient.

All in all, it's too soon to be sure about the cause but it couldn't hide from me ;)

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/Kvantum/commit/f029ce5f678105a5b52b1a04a06ccc0c8abab133

I got rid of the problem by removing an old workaround that had no use anymore, although I don't think it was the real cause. nheko's code calls QStyle/Kvantum where it shouldn't. Anyway, Kvantum shouldn't crash in such rare cases anymore.

Please update to the latest git (not V0.10.6 -- the commit after it). And thanks for the report!

**Comment by alexminder** [comment]
Thank you for support!
There are no more crashes with the last commit.
