### ISSUE TITLE
Window Decorations

### ISSUE THREAD

**Issue by HackaN** [tsujan/Kvantum#206]
I installed Kvantum on two Antergos machines. The first one via git clone and the second one via AUR. On neither can I find any Kvantum Window Decoration in KDE System settings... Did I miss or do something wrong?

**Comment by tsujan** [comment]
> Did I miss or do something wrong?

No, you didn't. Kvantum is a *Qt style engine*, not a window manager. Window decoration is provided by whatever window manager you use (KWin, Compiz-reloaded, Openbox,...).

In old times, I added Openbox decoration to Kvantum but I'll remove them sooner or later because Openbox isn't developed anymore and doesn't support wayland.

**Comment by HackaN** [comment]
Ah yes, I realized it while studying your "Theme-Making.pdf". At first I was expecting something like QtCurve which has both style and decoration. I'll see if I will try to get my hands dirty and contribute with my own theme for Kvantum, haha :-)

Thank you for your reply!

**Comment by tsujan** [comment]
> At first I was expecting something like QtCurve

QtCurve iincluded a window manager in old times of KDE4; it doesn't anymore.
