### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by CDrummond** [tsujan/Kvantum#209]
In order to have Kvantum included with Ubuntu, it needs to be changed to LGPL (see [Call for testing: communitheme + Qt](https://community.ubuntu.com/t/call-for-testing-communitheme-qt/6375/8)

This needs to be agreed by all [contributors](https://github.com/tsujan/Kvantum/graphs/contributors) - and of course, you my permission to re-license, etc, as you please :-)

**Comment by tsujan** [comment]
Ubuntu can't include a deb package of a GPL3 licensed program? That doesn't make sense to me. If so, Ubuntu has a serious problem.

I don't know "didrocks" but from things he's said on that page (like, "18000 lines in a single file isn’t what I would call maintainable code"), I can sense a problematic attitude. *I* am the developer of Kvantum and *I* will "maintain" it, as I have until now. If the code isn't understandable to others, that's not *my* problem.

As you surely know, Qt style plugins are different from other programs in that they need to deal with exceptions. In the case of an SVG style plugin, the number of those exceptions is enormous.

**Comment by CDrummond** [comment]
Its not having a GPL package that is the issue. The issue is that its a GPL package which is then linked into another application. I'm no lawyer, so I don't know if that's a real issue or not. All I was askig wat to change to **LGPL** - then there is no issue.

Is changing to LGPL really that bad for you?

**Comment by tsujan** [comment]
> Is changing to LGPL really that bad for you?

The words of an Ubuntu maintainer with a problematic attitude (didrocks) don't make sense to me. I recommend you don't take them seriously either. Our times are more valuable than that.

**Comment by tsujan** [comment]
FYI:

Ubuntu people wanted to engage us (LXQt developers) in another Ubuntu-specific matter but I strongly disagreed -- and I wan't alone. I don't know how to make them understand the simple fact that Ubuntu is just one distro among many and not as popular as it was before.

**Comment by CDrummond** [comment]
Sorry, but I don't want to attack people I don't know. As stated, I'm not 100% convinced this is an issue - but I can see how it _might_ be. Depends on whether a non-GPL using Qt5 app can actually load this theme and still be legal.

But, what harm will the license change make? Its still GPL - just allows linking to non-GPL apps.

Are you against making this LGPL? If so then that's fair enough - your project, so end of discussion. If you are not against, then what's the sticking point?

---

As stated many times - I just wan a unified desktop. Kvantum will massively help with this, hence wanting it as part of the core Ubuntu install. I'm happy to do the leg work for this, but I cannot change a license.

If Ubuntu won't allow a GPL library, and you won't change the license - then that's this idea scuppered before its really started...

**Comment by tsujan** [comment]
> Sorry, but I don't want to attack people I don't know. 

I didn't want you to do so. As for me, I never attack people themselves but their words, thoughts, acts or attitudes if I find them unreasonable or demanding/commanding.

> But, what harm will the license change make?

The harm is that Ubuntu demands it. Another distro might want something else. I won't do anything distro-specific. I respect all distros as far as their maintainers/developers don't have a demanding behavior.

**Comment by CDrummond** [comment]
Sorry, but that makes no sense. GPL -> LGPL change makes this less 'strictly' (not sure if that's the right word) licensed. As in, allows it to be more freely used - whilst still forcing changes to this codebase to be be made available to you. Kvantum is sort-of a library - hence (IMVHO) LGPL does make sense.

And Ubuntu are not demanding this. Its me trying to get this into Ubuntu. The license would appear to be  stumbling block.

If I email all the contributors, and get them to OK a GPL->LGPL change, would that be OK with you? Would you then change the license? I guess you could dual license - not sure if GPL + LGPL makes sense, but hey ho.

**Comment by tsujan** [comment]
> And Ubuntu are not demanding this.

Ubuntu has its strict conditions, supposedly; so it demands them. I don't like to change anything just to satisfy a set of Ubuntu rules for Ubuntu to accept one of my programs in any way. Ubuntu's problem with GPL3 is not mine and that makes a complete sense to me.

**Comment by CDrummond** [comment]
So, If I had asked for a GPL->LGPL change, with me doing the legwork, **not** related to Ubuntu - you would have no issue with that?

Again, your code your decision. Just curious if you really are opposed to an LGPL change. Which again is fine - you might personally not want this loaded with non-GPL apps.

**Comment by tsujan** [comment]
It's not about the legwork. I'm against changing anything for Ubuntu.

As [Wikipedia](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) says, "The main difference between the GPL and the LGPL is that the latter allows the work to be linked with ... a non-(L)GPLed program, regardless of whether it is free software or proprietary software." I don't like that but I frankly told you about my main reason above: Ubuntu rules.

**Comment by tsujan** [comment]
> Why you did not just answer with that in the first place

It would hide my main reason ;)

> I don't like "I'm against changing anything for Ubuntu" - that's a bit harsh.

That's what I'll do and "Ubuntu" can be replaced by the name of another distro but I haven't seen such a degree of demandingness from other distros. I know you don't agree with me on this.

**Comment by CDrummond** [comment]
The world would be a boring place if we all agreed on everything :-)

**Comment by tsujan** [comment]
Ha ha.

Related to this:

Users' demandingness is mostly useful. A developer shares his/her program with others for users to want this or that feature and report bugs he'd never seen. Said in other words, he shares a program for its quality to get higher with user's help. At least, that's how I see it. Distros don't function in that direction. So, I ignore them.

**Comment by galgalesh** [comment]
Hi tsujan

It seems this started off on the wrong foot. I want to make clear that Ubuntu is not demanding anything from Kvantum. We're just a bunch of community members who are discussing how we can support Qt by default in Communitheme, and your project seems like the best option.

I want to give some context on the GPL topic. Note that I am not a lawyer, I'm not even an Ubuntu contributor, I'm just a community member working on the packaging side of Communitheme. Adding a GPL package to Ubuntu is not an issue at all. After all, Communitheme itself is GPLv2! I personally really like the license and I use it for many of my own projects.

The concern for Kvantum's license seems to be that the code in `style/` runs in the process of the QT application that is styled. This means that the application which is styled by Kvantum is considered a "derivative work" of Kvantum and must have a GPL compatible license. If this is the case, then Ubuntu would be violating your license by shipping Kvantum because Ubuntu cannot guarantee that all Qt applications running on Ubuntu have GPL compatible licenses.

Take Dropbox as an example. This is a closed source application which uses Qt. If Kvantum is installed, then Kvantum's code will be dynamically linked with Dropbox in order to theme Dropbox. The Free Software Foundation is clear in that they consider this a GPL violation.

I can totally understand if you don't want Kvantum to theme closed-source applications, but I want to make sure that this is the behavior you intended. If so, we cannot ship Kvantum with Ubuntu. The GPL itself is not an issue, but we simply can't stop users from installing closed source Qt applications.

Is this the behavior you intended?

**Comment by tsujan** [comment]
> This means that the application which is styled by Kvantum is considered a "derivative work" of Kvantum and must have a GPL compatible license

*Rationally* wrong -- I don't care about formalities. Rationally, Kvantum's code isn't used in an app which is styled by it and they're independent from each other. A Qt app is responsible for its own bugs/functionalities, which aren't related to Kvantum. Kvantum is also responsible for its bugs/functionalities, which aren't related to apps it styles. If styling a closed-source app with Kvantum means "violating" a rule, then sorry, I'm not interested in such discussions.

> Is this the behavior you intended?

Which behavior? Ubuntu's behavior isn't under my control. Kvantum's license is GPL and will remain GPL. That isn't a "behavior".

**Comment by galgalesh** [comment]
Thanks for your clarification.

It is important for everyone to fully comply with the GPL. We will not infringe on the GPL even if you don't care about these formalities. Imagine a company like Microsoft using the argument "I don't care about formalities" in order to justify a GPL violation. Open Source licensing is an important cornerstone to this ecosystem and we should not dismiss it so easily. We will respect the rights of you and all the Kvantum contributors, so we will not use it for Communitheme.

> If styling a closed-source app with Kvantum means "violating" a rule, then sorry, I'm not interested in such discussions.

The position of the Free Software Foundation is clear on this. [The GPL applies to all software linked to a GPL work, even dynamically linked software](https://www.gnu.org/licenses/gpl-faq.en.html#GPLStaticVsDynamic). This means that using Kvantum to theme a closed source app infringes on the rights of all the contributors to Kvantum.

The only way to change this, is to get formal approval from each and every contributor to Kvantum, either for switching to another license [or for including a copyleft exception](https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs). The only difference between GPL and LGPL is this formality: LGPL software is allowed to link to closed source binaries, GPL software is not.

Thank you for your time and thank you for this cool project.

**Comment by tsujan** [comment]
Now I should care about Microsoft too? Just joking ;)

[Frequently Asked Questions about the GNU Licenses](https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem):

"However, in many cases you can distribute the GPL-covered software alongside your proprietary system. To do this validly, you must make sure that the free and nonfree programs communicate at arms length, that they are not combined in a way that would make them effectively a single program."

To me, this is clear enough. Kvantum is a *Qt style plugin*, not a dropbox plugin.

**Comment by tsujan** [comment]
Another quotation: "The goal of the GPL is to grant everyone the freedom to copy, redistribute, understand, and modify a program." The goal is achieved.

Everything will seem complicated if we're lost in interpretations.

**Comment by tsujan** [comment]
Oh, I forgot this:

> so we will not use it for Communitheme.

That's a good decision to me. I prefer `KvCommunitheme` to remain an extra theme of Kvantum itself. However, contrary to your interpretation of GPL, you have right to use Kvantum+KvCommunitheme and, if you used it, I'd respect your right, exactly because it's GPL :)

**Comment by galgalesh** [comment]
> To do this validly, you must make sure that the free and nonfree programs communicate at arms length, that they are not combined in a way that would make them effectively a single program.

and further down

> The difference between this and “incorporating” the GPL-covered software is partly a matter of substance and partly form. The substantive part is this: if the two programs are combined so that they become effectively two parts of one program, then you can't treat them as two separate programs. So the GPL has to cover the whole thing.

Since the Kvantum engine itself runs as part of the same process of the application, Kvantum and the app are considered a single program. They do not "communicate at an arms length"; they communicate in exactly the same way as any dynamically linked library communicates. Kvantum is just a library provided by the system instead of by the app, but this does not matter: 

> Most system libraries either use the GNU Lesser GPL, or use the GNU GPL plus an exception permitting linking the library with anything. These libraries can be used in nonfree programs; but in the case of the Lesser GPL, it does have some requirements you must follow.
> Some libraries are released under the GNU GPL alone; you must use a GPL-compatible license to use those libraries. But these are normally the more specialized libraries, and you would not have had anything much like them on another platform, so you probably won't find yourself wanting to use these libraries for simple porting.

https://www.gnu.org/licenses/gpl-faq.en.html#PortProgramToGPL

The Kvantum themes themselves are a different case, they can be considered at an arms length, but because the engine runs in the same process and is dynamically linked, it is regarded as a combined work.

As a result, all common theme engines use LGPL instead of GPL:

- [All Qt style plugins including QGtkStyle](https://github.com/qt/qtstyleplugins/search?q=QT_BEGIN_LICENSE%3AGPL&unscoped_q=QT_BEGIN_LICENSE%3AGPL)
- [QGnomePlatform](https://github.com/FedoraQt/QGnomePlatform/blob/master/LICENSE)
- `gtk2-murrine-engine` and `gtk2-pixbuf-engine`

**Comment by tsujan** [comment]
> Since the Kvantum engine itself runs as part of the same process of the application,

Then, all apps inside an operating system run as parts of "the same process", which is an arbitrary interpretation.

Anyhow, as implied before, I have no problem with Ubunu's imaginary problem with Kvantum; it's just not my problem.
