### ISSUE TITLE
Feature Request: Spaces between menu items in 

### ISSUE THREAD

**Issue by dooqob** [tsujan/Kvantum#224]
Could you please make an option to control spacing between menu items, because Menus are very huge in small screen resolutions like mine 1366x786.
Thanks in advance.

**Comment by tsujan** [comment]
The vertical space between menu-items is already configurable by using these 4 variables under the `[MenuItem]` section of the `kvconfig` file of the theme: `text.margin.top`, `text.margin.bottom`, `frame.top` and `frame.bottom`.

If the theme is installed as root, you could save it and edit its `kvconfig` file as user. Please read the explanation on the top of `Kvantum Manager` → `Configure Active Theme`.

Such settings are considered to be advanced and aren't directly included in Kvantum manager because they may damage the look and feel of the theme but, of course, almost everything is configurable in Kvantum.

**Comment by tsujan** [comment]
Oh, there's yet another key: `min_height`. It should be zero (`min_height=0`) under the `[MenuItem]` section if it's used at all.

So, there are 5 ways to control menu-item spacing.
