### ISSUE TITLE
.deb

### ISSUE THREAD

**Issue by FMuro** [tsujan/Kvantum#228]
Hi @tsujan, thanks a lot for this, it's great. Do you plan on releasing a .deb package for the last version? Have you thought of shipping them through an Ubuntu PPA?

**Comment by tsujan** [comment]
A long time ago, when I was a Debian user, I added deb packages to each release. Later, I left that to others because my system became Arch-based (Manjaro) and I didn't have time to deal with deb packages anymore.

I'm sure there were up-to-date deb packages somewhere but, unfortunately, I don't remember where.

Anyway, Kvantum supports CMake for a long time, so that it can be compiled like:
```
mkdir build && cd build
cmake ..
make
```
and then installed by `sudo make install`.

**Comment by tsujan** [comment]
Good news: Kvantum might be added to Debian repository soon: https://github.com/tsujan/Kvantum/issues/229 . The deb package(s) may not be for Ubuntu but Ubuntu could make its own package(s) based on it.

**Comment by agaida** [comment]
normally it don't take long - there is nothing special about the packaging, so it can be downstreamed by ubuntu without changes - and they will do, for sure

**Comment by agaida** [comment]
@tsujan fyi
[2018-11-09 15:12:38] <BTS> qt5-style-kvantum (NEW) 0.10.8+repack-1 uploaded by Alf Gaida <agaida@siducti...> (Closes: #889075) https://tracker.debian.org/qt5-style-kvantum
[2018-11-09 15:15:23] <BTS> Closed #889075 in wnpp by Alf Gaida <agaida@siducti...> «ITP: qt5-engines-kvantum -- SVG-based theme engine for Qt5». https://bugs.debian.org/889075

**Comment by tsujan** [comment]
@agaida Thanks!

**Comment by tsujan** [comment]
Debian is Debian; I know how long it might take.
