### ISSUE TITLE
Blur exceeds windows' edges

### ISSUE THREAD

**Issue by Spiffyk** [tsujan/Kvantum#242]
When the blur behind windows is turned on, the blurred "canvas" exceeds the left and right edges of the windows by one pixel on my Manjaro KDE install, as seen on the screenshot below. This happens regardless of the border size. I'm using Kvantum 0.10.7.

![kvantum-bleeding](https://user-images.githubusercontent.com/2039454/43884335-23d04102-9bb6-11e8-90be-e75586f523a1.png)

**Comment by tsujan** [comment]
Oh, that isn't related to Kvantum but to the window decoration you use. Kvantum doesn't draw title-bars or window borders (== decoration); the window manager does.

The default window manager of KDE is KWin and its default window decoration is Breeze but there are other ones too. Recently, the blurring code of KWin changed -- actually, it became much better -- but window decorations like the old Aurorae may have problem with it.

BTW, I use the latest Manjaro Testing; everything is OK with Breeze and [BreezeBlurred](https://github.com/alex47/BreezeBlurred).

**Comment by Spiffyk** [comment]
I see... well, time for me to find Adapta decoration's repository and try to fix it. :)

**Comment by tsujan** [comment]
I hope the Adapta decoration isn't Aurorae. I haven't used Aurorae for a while because it had bad issues with Plasma5 but people may have found workarounds.

For now, the best KWin decorations are those derived/forked from Breeze -- the Breeze decoration itself is still very poor. I use a modified version of BreezeBlurred.
