### ISSUE TITLE
[Suggestion] Make menu selection reach the edge when the menu has rounded corners.

### ISSUE THREAD

**Issue by Luwx** [tsujan/Kvantum#248]
It will be a nice visual improvement.

Currently: 
![screenshot_20180819_220214](https://user-images.githubusercontent.com/33076480/44315958-25257580-a3ff-11e8-8732-c69670d88d3f.png)

In breeze:

![screenshot_20180819_220315](https://user-images.githubusercontent.com/33076480/44315969-2eaedd80-a3ff-11e8-9d05-94d98e7b469f.png)

**Comment by tsujan** [comment]
In Breeze, the selected menu-item is just filled with the highlight color; nothing more. In Kvantum, it can have a complex shape (you could see that in many Kvantum themes). Since the theme can't announce the complexity/simplicity of its elements to the engine, this scenario doesn't have much meaning with Kvantum.

And it's a matter of taste, after all.

That being said, and although it isn't elegant to me, I'll see if I could give a meaning to it in special and simple circumstances. Themes like KvCommunitheme may have it.

**Comment by tsujan** [comment]
Realistically, possible but not maintainable because the menu shadow is inside the menu SVG elements, not provided by WM.

**Comment by tsujan** [comment]
Moreover, as said above, it doesn't make much sense with Kvantum because themes like this should remain possible:

![menu](https://user-images.githubusercontent.com/981076/45039222-60b77500-b078-11e8-97ed-1ff67f80974f.png)
