### ISSUE TITLE
SCD implementation with Kvantum

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#254]
It's possible move or duplicate window buttons on toolbar for Qt-apps?
It's will be looking very similar with GTK3
![image](https://user-images.githubusercontent.com/8083855/45403396-2434dc00-b66b-11e8-875b-4b8395d79625.png)
On aurorae rc-file hide buttons and title with 0px size:
```
ButtonHeight=0
ButtonWidth=0
TitleHeight=0
```

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/adapta-kde/issues/77

**Comment by varlesh** [comment]
I mean show forced window buttons on toolbar as widget and add option on kvantum manager for enable/disable hack and possible postion left/right :)

**Comment by tsujan** [comment]
@varlesh 

Any developer can add those buttons to the toolbar of his Qt app but adding any widget to a Qt app *from a style plugin* is very dangerous and could easily result in crashes. As far as I experimented years ago, there are cases that even resize grip can't be added (Kvantum Manager → Hacks → Force size grips) because, otherwise, it would cause immediate crashes ;)

If, at some point, Qt-6 adds a `QStyle` parameter for showing window buttons on toolbars, I could add an option for it. But I think that the GTK3 method doesn't have many fans among Qt developers...
