### ISSUE TITLE
missing tabbarframe in qupzilla

### ISSUE THREAD

**Issue by andbgr** [tsujan/Kvantum#257]
i'm not sure if this is a bug or a request for a hack:
the tabbarframe in the qupzilla main window is only visible while dragging tabs, then disappears again.

**Comment by andbgr** [comment]
i use the tabbar frame the same way as KvAmbiance (only bottom line), see here (comparison with dolphin):
![screenshot_20180912_202656](https://user-images.githubusercontent.com/26405996/45445565-dcde3800-b6ca-11e8-892b-c56498d9db62.png)
![screenshot_20180912_202810](https://user-images.githubusercontent.com/26405996/45445588-ea93bd80-b6ca-11e8-8306-96375acb7c45.png)

but i forgot, qupzilla will soon be obsolete.
maybe just check if falkon looks right with KvAmbiance, then QTStep should be fine at least in falkon too

**Comment by andbgr** [comment]
ok, weird, i just checked, KvGnome looks fine with qupzilla, but not KvAmbiance

**Comment by tsujan** [comment]
> I use the tabbar frame the same way as KvAmbiance

This is KvAmbiance with Falkon:

![kvambiance](https://user-images.githubusercontent.com/981076/45446272-b24ba980-b6e1-11e8-9f2b-5bb2336a885e.png)

So, there are only two possibilities: Either there was a problem in Qupzilla that's fixed in Falkon (more probable because I'd sent a fix for a similar problem to QupZilla's developer a long time ago); or you use an old version of Kvantum (I don't think so but please always use the latest git).

> ok, weird, i just checked, KvGnome looks fine with qupzilla, but not KvAmbiance

No, it may not be weird; the issue you see with KvAmbiance may be hidden by KvGnome in some way, Anyhow, as mentioned above ,with the latest version of Kvantum and Falkon, there is not issue.
