### ISSUE TITLE
asymmetric GenericFrame frame size

### ISSUE THREAD

**Issue by andbgr** [tsujan/Kvantum#259]
in my theme i have 
frame.top=2
frame.bottom=1
frame.left=2
frame.right=1
for GenericFrame, but it draws a 2px border on every side. Or, more precisely, it draws the right/bottom frames 1px, but then leaves an additional 1px space between frame and content, but only for bottom/right. Is there some other variable (inner padding or something) here that i missed?

**Comment by tsujan** [comment]
This one is easy to answer :)

Most of Kvanum concepts -- like frame widths -- aren't supported by Qt; I've enforced them on Qt. Fortunately, Qt was flexible enough to accept them. However, in some cases, compromises were needed.

In the case of `GenericFrame`, the maximum of all frame widths should be used for the spacing because Qt has only one parameter for it, i.e. `PM_DefaultFrameWidth`.

**Comment by andbgr** [comment]
ah, ok, i suspected something like that
