### ISSUE TITLE
Some apps are not transparent 

### ISSUE THREAD

**Issue by Zeekk9** [tsujan/Kvantum#273]

**Comment by Zeekk9** [comment]
Apps like dophin are transparent but for example, qbittorrent no, whats the problem? thanks!!!
![screenshot_20181011_181039](https://user-images.githubusercontent.com/32948121/46839016-8aec0900-cd81-11e8-8691-380a74e1da0b.png)
![screenshot_20181011_181112](https://user-images.githubusercontent.com/32948121/46839017-8aec0900-cd81-11e8-8fea-58bbea3f8a9e.png)

**Comment by tsujan** [comment]
The theme you use doesn't have a translucent TabFrame interior (which qbittorrent draws behind its widgets); otherwise, qbittorrent *is* translucent and you can see that by showing its Preferences dialog.

**Comment by trmdi** [comment]
@tsujan 
Btw, KDE System Settings is not transparent as well. Can it be changed? (using KvMojave)

**Comment by tsujan** [comment]
@trmdi Let me explain it with some details:

Window translucency only means that the whole window is translucent. Now, there may be many widgets on the window. For example, buttons aren't translucent. Also, generally, item-views cannot be translucent *although Kvantum is the only widget style that can enforce translucency on them too.*

When you open KDE System Settings, it's covered by an item-view. If you go into its Window Management item, for example, you'll see window translucency.

That being said, Mojave has a very mild item-view translucency too. As a matter of fact, the view of System Settings *is* translucent but its opaqueness is very high. It depends on `base.color` in `KvMojave.kvconfig` -- I've given that color a very low translucency for item-views to be distinguished from other widgets. In general, giving a high degree translucency to that color isn't a good idea because of bugs in some apps.

BTW, I started to make MojaveLight; it's taking shape slowly ;)

**Comment by tsujan** [comment]
@Zeekk9

BTW, please upgrade to the latest git Kvantum! Your Dolphin screenshot shows a bug that is fixed in git.
