### ISSUE TITLE
Kvantum has no blurred effect on Plasma Wayland ?

### ISSUE THREAD

**Issue by trmdi** [tsujan/Kvantum#274]
Breeze does has. Can it be implemented on Kvantum ?

**Comment by tsujan** [comment]
In fact, I disabled translucency under wayland a long time ago because it had serious problems. With Qt 5.11, those problems may have been fixed but I haven't tried a wayland session after Qt 5.11 yet.

As for Breeze, it is a KDE program and so, is free to use KDE-specific things. Kvantum is independent from KDE. X11 blurring was/is done by calling KDE blur effect with X11 codes -- not KDE codes. I'm not sure if a similar thing is possible with plasma-wayland.

Your report was in my to-do list but I don't know when I'll have enough time to investigate it. So, it might remain open for a long time.

**Comment by tsujan** [comment]
I investigated it. To enable the blur effect under wayland, `KWindowSystem` should be added to dependencies. `KWindowSystem` doesn't mean a KDE dependency and is used by LXQt too.

I think it's worth adding but I should do some tests first. Its advantage is that the code won't deal with X11 or Wayland directly but will treat them in a unified way. `KWindowSystem` is a valuable KDE contribution to Qt under Linux.

**Comment by tsujan** [comment]
At last, under Wayland:

![wayland](https://user-images.githubusercontent.com/981076/47075741-062e3e80-d20a-11e8-9b77-a7573658ef78.png)

I hope an extra dependency won't confuse users. Will test it for a while before adding a commit.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/125e7721a089bb96c13a427e26bb1f5b08748687

**Comment by trmdi** [comment]
Great! Thank you.

**Comment by trmdi** [comment]
I have a repo for openSUSE Tumbleweed users that provides binary git packages include Kvantum and BreezeEnhanced. You could add it to your INSTALL file if you want.
```
zypper addrepo https://download.opensuse.org/repositories/home:trmdi/openSUSE_Tumbleweed/home:trmdi.repo
zypper refresh
zypper install kvantum
```
https://software.opensuse.org//download.html?project=home%3Atrmdi&package=kvantum

**Comment by tsujan** [comment]
@trmdi I will :) I hope you'll keep it up-to-date; if not, it'll be OK; please only tell me! Please also tell me if something is changed (the name `Tumbleweed`, for example -- I don't know much about how names are changed in `openSUSE`).

Thank you!

**Comment by tsujan** [comment]
@trmdi
Added here: https://github.com/tsujan/Kvantum/blob/ddbdc700f319a3e45ad182e30ad4c0e9e880fa3b/Kvantum/INSTALL#L52
