### ISSUE TITLE
Question: how to remove the pointed frame around selected items in KvSimplicity theme ?

### ISSUE THREAD

**Issue by cipricus** [tsujan/Kvantum#277]
I am interested which setting handles the aspect of this item - the pointed frame around selected items:

![2018-10-19_15-09](https://user-images.githubusercontent.com/3447868/47220197-627f9280-d3b1-11e8-8010-6c3d6f70f9aa.png)

![2018-10-19_15-10_1](https://user-images.githubusercontent.com/3447868/47220213-690e0a00-d3b1-11e8-8661-7e7b221b729f.png)

![2018-10-19_15-10](https://user-images.githubusercontent.com/3447868/47220217-6ca19100-d3b1-11e8-9bad-97480089bb7e.png)

Could  the file `/usr/share/Kvantum/KvSimplicity/KvSimplicity.kvconfig` be edited for this purpose? What line? 

(I prefer the KvSimplicity theme for its non-flat view, I like it in all respects except for the pointed frame around selected items. It might be only a subjective impression, but I find that it gives to this otherwise fresh theme a somewhat outdated look.)

Thanks.

**Comment by tsujan** [comment]
That's called "focus rectangle". Practically, it's important to know which widget has the keyboard focus, so I've added it to all themes. In this case, practicality is more important than look, IMO.

To remove it from *button-like widgets*:

(1) Save `KvSimplicity` with Kvantum Manager;
(2) Add `focusFrame=true` to the end of the`[PanelButtonCommand]` section in `~/.config/Kvantum/KvSimplicity#/KvSimplicity#.kvconfig`.

Since there no "focus frame" in the SVG file (it has another story), nothing will be drawn for focused buttons.

However, if you want to remove it altogether, you should put `KvSimplicity.svg` in `~/.config/Kvantum/KvSimplicity#`, rename it as `KvSimplicity#.svg`, open it with Inkscape, and finally, find and remove `focus-top`, `focus-right`, `focus-bottom` and `focus-left` elements (they're near the bottom of the image. That means a new theme is derived from KvSimplicity. You could rename its folder, SVG file and kvconfig file to keep it for yourself. Of course, you could also edit it in whatever way you like.

**Comment by tsujan** [comment]
BTW, if you use the latest git version of Kvantum, you'll see several non-flat themes in it. I'm not fond of flat themes but have added some because others like them.

**Comment by tsujan** [comment]
@cipricus I updated [the explanation](https://github.com/tsujan/Kvantum/issues/277#issuecomment-431369215); there was a very easy way to remove it completely.

Removing its elements from the SVG file won't help because they will be taken from the default theme.

**Comment by cipricus** [comment]
Thank you for your great work! - as well as for your prompt answer which provides all I have asked for.. 

But if I may I'll make a few more comments.

Using the new setting in Lubuntu Lxqt 18.10 the focus is clear anyway, at least in the occurrences that I've mentioned.

Considering the images I've posted:

![2018-10-19_15-09](https://user-images.githubusercontent.com/3447868/47246480-4e15b700-d3fe-11e8-9b0e-62c0c189c309.png)

In the above the file is selected and marked with blue, so the focus frame is not needed.

![2018-10-19_15-10_1](https://user-images.githubusercontent.com/3447868/47246610-1eb37a00-d3ff-11e8-9131-8ca3788dd780.png)

With the new setting:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3447868/47246842-55d65b00-d400-11e8-84f3-da90127c4e11.gif)

Above the focus is visible through the bold characters and the bottom right sign.

And the following image (similar to the one already posted in the initial question) shows that frame around  a file that was selected but it's not anymore, as a different one is selected and has focus.

![2018-10-20_00-25](https://user-images.githubusercontent.com/3447868/47247078-9da9b200-d401-11e8-9a15-558ff601552a.png)

**Comment by tsujan** [comment]
> In the above image the file is selected and marked with blue, so the focus frame is not needed.

That's only a special case. Consider this one, where a row has 3 columns:

![focus](https://user-images.githubusercontent.com/981076/47247604-9ee2db00-d411-11e8-9057-0dc91558525c.png)

> Above the focus is visible through the bold characters and the bottom right sign

Again, a special case for push-buttons that can be the default button. Not all buttons are so.

> No added value in the pointed frame, and it doesn't look "finished".

I'm not sure what you mean by "added value" but that triangle is an indicator for distinguishing the default button among a group of buttons. It's especially useful when the button has no text but also helps finding it instantly.

> And the following image (similar to the one already posted in the initial question) shows that frame around a file that was selected but it's not anymore, as a different one is selected and has focus.

It shows the item that will responds to the keyboard once you activate the left pane -- that's how the app wants it in its code.

All in all, the focus rectangle is useful when the user works with keyboard. Many apps decide how and when to show it. It isn't necessarily a dotted rectangle but that shape is recognized instantly by most users.

Needless to say, removal of the focus rectangle isn't a disaster; many users rely on mouse instead of keyboard.

Some Kvantum themes -- like KvCurves3d -- make the focused button or tab a little lighter, instead of drawing a focus rectangle.

**Comment by cipricus** [comment]
Thank you for all these clarifications, and all the best to you!

**Comment by tsujan** [comment]
You're very welcome!
