### ISSUE TITLE
Stickers: missing elements

### ISSUE THREAD

**Issue by sohaam** [tsujan/Kvantum#28]
Hello, tsujan.
Please, check first screenshot. Here is a default Kvantum theme selected. This is a KNotes sticker. Is this an expected element behavior?
![kvantum_def_knotes1_mod](https://cloud.githubusercontent.com/assets/11130487/6544664/c0569788-c57c-11e4-8ef6-f84949790840.jpeg)

Then, please, check second screenshot with Okular stickers. It's with default theme:
![kvantum_def_okular1_mod](https://cloud.githubusercontent.com/assets/11130487/6544672/595ec946-c57d-11e4-8827-bec9fb23df43.jpeg)

For example, the same sticker with Kvantum Glare theme:
![kvantum_glare_okular2](https://cloud.githubusercontent.com/assets/11130487/6544675/78689d12-c57d-11e4-8566-d6b29faa112f.jpeg)

and Oxygen theme engine:
![oxygen_okular3_mod](https://cloud.githubusercontent.com/assets/11130487/6544680/9cface66-c57d-11e4-8d7a-e361af697799.jpeg)

**Comment by tsujan** [comment]
The bottom right corner is the resize grip, whose shape depends on the theme.The default theme uses a dark rectangle for it. KNotes should have drwan its resize grip **itself** for a consistent look. However, I might change the grip of the default theme so that such unusual cases look more OK.

The same can be said about the close button rectangle. I have to look into KNotes' code to know why its close button rectangle is so different from other widgets.

All in all, such cases are because the possibility of using SVG elements for drawing widgets isn't considered in writing their codes: it's supposed that rectangles would be filled only with colors. I'll look into them. Thanks!

**Comment by sohaam** [comment]
> The same can be said about the close button rectangle. I have to look into KNotes' code to know why its close button rectangle is so different from other widgets.
You mean look into Okular code? Anyway, thanks for explanation)

**Comment by tsujan** [comment]
> You mean look into Okular code?

Both of them.

**Comment by tsujan** [comment]
Fixed!
Now, only the indicator of resize grip (if it exists) and not its interior is drawn for such widgets.
The close icon of Okular's annotations is added too.
Please close this issue if you're satisfied with the changes!

**Comment by sohaam** [comment]
Hello, thank you! Great work!
