### ISSUE TITLE
Push buttons and tool buttons has differents border sizes

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#29]
Push buttons and tool buttons has differents border sizes, look the image bellow. On the left size, a toolbutton with 2px border bottom (wrong), and on the right, a push button with correct bottom border size (3px). It seems that all toolbuttons borders are reduced.

![Kvantum print](http://i.imgur.com/kBvtbaL.jpg)

**Comment by tsujan** [comment]
That's because setting some size limits on toolbuttons was necessary for several reasons. For example, if a toolbutton doesn't have icon, its right and left frame widths will be equal to the minumum of "frame.left" and "frame.right", and the same for the top and bottom frames. Or if it's inside an view-item, the widths will be reduced to 3px, etc.

The general reason for setting such limits was that many apps don't respect variable frame widths for toolbuttons.

There are size limits for pushbuttons too but they're less strict.

**Comment by tsujan** [comment]
BTW, if you want to show a dark line under toolbuttons, you won't need to choose different top and bottom frame widths but just to use different top and bottom SVG elements.

**Comment by franksouza183** [comment]
I got it. Is there a specific svg element for tool buttons?

**Comment by tsujan** [comment]
First let me be a little more specific because there's a long story behind this and others might also come to this page.

In the early days of Kvantum, I found that many developers supposed (tool-)buttons should have a border of 3px at most and equal on all sides. That was understandable because no theme engine had a variable (key) for border sizes but it could cause various problems with Kvantum. I had a hard time to find the circumstances, under which, size limits would fix such (false) problems. Without those limits, sometimes the text would be cut off, sometimes its position would be wrong, etc. I emphasize that it isn't about a limitation in Qt but about a wrong presupposition. Hence the compromise! And that compromise sometimes results in different frame widths in case of toolbuttons.


Of course, you could choose toolbutton SVG elements that are different from those of pushbuttons by setting different interior and frame elements under the PanelButtonTool section (see my theme, KvFlat, for an example). But you still might not get the same frame widths you've set in the config file because size limits will still show up under special circumstances predicted in the code.

**Comment by franksouza183** [comment]
Absolutely no problems, thanks for the precise explanation! And I perfectly understand why the limits. Anyway, what is the section name from the config file? ToolButtonCommand? ToolButton? I tried both and seems not to work

**Comment by tsujan** [comment]
It's PanelButtonTool. Please see Theme-Config for explanations. I sometimes refer to it myself ;)

**Comment by franksouza183** [comment]
Sorry, for some reason I completely ignored the file "Theme-Config.pdf". I also downloaded your theme, and is a true masterpiece, and is a great base for my. Thanks again!
