### ISSUE TITLE
Why isn't this part of KDE?

### ISSUE THREAD

**Issue by QUASARFREAK** [tsujan/Kvantum#290]
Hi, and good work! Why isn't kvantum part of the official KDE packages?

**Comment by tsujan** [comment]
Because:

(1) It doesn't depend on KDE and can be used anywhere.

(2) I wouldn't agree with that if it was proposed. Qt became very powerful since version 4. Developers don't need KDE's heavy subclassings to work with it. That's why DEs like LXQt became possible. However, KDE has had nice contributions to Qt, like KWindowSystem, which I recently started to use in Kvantum. KWindowSystem doesn't depend on KDE but KDE depends on it.
