### ISSUE TITLE
[Question] vlc blur possible?

### ISSUE THREAD

**Issue by brudolp** [tsujan/Kvantum#299]
https://i.imgur.com/1P5z9y1.png
main vlc interface is blurred with qtcurve, but not with kvantum,
tried removing vlc from non-translucent apps and tried vlc-git version with qt5(afaik).
currently using export QT_STYLE_OVERRIDE=qtcurve && vlc which works, but maybe it's also possible with kvantum?

**Comment by tsujan** [comment]
Since old times, some versions of VLC could be made translucent (and hence, blurry) without problem but some versions had serious problems. So, I decided not to add a special hack for VLC but, instead, exclude it from translucency by default (see Kvantum Manager → Configure Active Theme → Compositing & General Look → Opaque apps) because I didn't want Kvantum users encounter any problem with it.

Moreover, the way QtCurve makes windows translucent is different from that of Kvantum. QtCurve's method has bug and can result in (rare) crashes, while Kvantum's method is safe.
