### ISSUE TITLE
Minor glitch at the junction (left and right) of SVG elements on itemViews

### ISSUE THREAD

**Issue by franksouza183** [tsujan/Kvantum#30]
Hey @tsujan take a look on this screenshot:

![Kvantum print](http://i.imgur.com/yYDZICt.jpg)

There seems to be a minor glitch at the junction (left and right) of SVG elements on itemViews (you may need to enlarge the image to see), but in some specific applications. For now, I could see this on Dolphin and Kdisplay. I have tested with your theme (KvFlat), EvolvereLight and the default. I tested it with several frame.left/right (between 2 and 10) values, and for all, the glitch is visible. I also consulted the manual and I didn't find nothing related. It also seems the text.margin parameter is ignored, I tested with values between 1 and 10, and there was no effect. Can you confirm if I am doing something wrong?

Many thanks!!

**Comment by tsujan** [comment]
Yes, I've seen that in Dolphin before. I think it's about a bug in a KDE library or method, which Dolphin uses for drawing those view-items because I've seen nothing like it in purely Qt apps.

I'll study some related KDE sources whenever I have free time but that won't be an easy task.

And no, I don't think you've done anything wrong. However, it's strange why the problem can be seen with both EvolvereLight and KvFlat in case of Dolphin but not in case of Kdisplay.

**Comment by tsujan** [comment]
Oh, I think that the answer to my last question is just the background color. There's no essential difference between the two themes.

**Comment by tsujan** [comment]
I forgot to explain about the text margin parameter. Yes, it's ignored in case of systemsettings because it's ignored in its code. Some apps don't respect those parameters in their hard-coded styles, unfortunately. Therefore, a reasonable value for frame widths is recommended with themes that have non-flat view-item frames.

**Comment by franksouza183** [comment]
Many thanks for the explanation, I'll wait for you to analyze the dolphin code and see if have any solutions. Close this issue when you want ;)

**Comment by tsujan** [comment]
Should be fixed now. Please test!

It seems that Dolphin has problem with QSvgRenderer. To avoid all such issues, I used QPixmap as a mediator in case of itemviews.

The issue of text on frames, which is because of hard-coded styles in some apps, can be avoided by choosing frame widths <= 3px for 3D itemviews. As the itemview of EvolvereLight is flat, you wouldn't need to do anything.

**Comment by franksouza183** [comment]
Perfect, It works! Yes, indeed, it's not a problem for me about the 3px limit. Many thanks!

**Comment by tsujan** [comment]
Good! So I close this issue. Please tell me if you find any problem like this anywhere else.
