### ISSUE TITLE
Something is wrong with QtQuick Control's TableView

### ISSUE THREAD

**Issue by trmdi** [tsujan/Kvantum#300]
Hi @tsujan 
I know you don't like QtQuick so much, but I post the issue here to see if you can improve something from the Kvantum side.

The issue is that, a  table column's header that doesn't have a title would appear buggy.
Please see the last column's header in the screenshot, the above one uses Breeze, and the below one uses Kvantum (KvMojave Light)

![image](https://user-images.githubusercontent.com/11857205/48624648-8a2d3f00-e9df-11e8-9185-13889649e3de.png)

You can reproduce it with this code:
```QML
// test.qml
import QtQuick.Controls 1.4

TableView {
    id: root 

    TableViewColumn {
        role: "title"
        title: "Title"
        width: root.width*0.4
    }
    TableViewColumn {
        role: "author"
        title: "Author"
        width: root.width*0.4
    }
    TableViewColumn {
        role: "bughere"
        title: "" // when the title is empty
        width: root.width*0.2
    }
    model: [{title: "Happy new year", author: "Abba", bughere: 123456}]
}
```
Run it: `$ qmlscence test.qml`

**Comment by tsujan** [comment]
Please read https://www.reddit.com/r/kde/comments/9p8uwm/open_a_friendly_and_constructive_discussion_about/

In short, QML problems are caused by QML and KDE.

**Comment by tsujan** [comment]
Since I know you pay attention to details and also to give an example of why QML/QtQuick shouldn't get its style from `QStyle` (as a reference), let me give a detailed explanation:

First, compare it with a real Qt header:

![header](https://user-images.githubusercontent.com/981076/48635478-7e407d80-e9dd-11e8-8cf3-a891c9ad41d8.png)

Every real widget, reports a "contents size" to `QStyle`. That contents size is the minimum possible size the widget can have. `QHeaderView` also reports a size in such a way that the heights are equal. *QtQuick doesn't do that.*

Second, let's see what happens in elementary styles:

All elementary styles (like Fusion) take the header size from Qt → `qcommonstyle.cpp`, which doesn't have any configurable value (unlike Kvantum). The text is tightly enclosed with the upper and lower lines.

On the other hand, Breeze has an interesting line in `breezestyle.cpp` → `QSize Style::headerSectionSizeFromContents`:

```c++
int contentsHeight( headerOption->fontMetrics.height() );
```

It means that (1) the reported contents size is totally ignored and instead, (2) the height is always the same and doesn't have any configurable value, whether there is really a text or not.

Of course, none of these can be used by Kvantum because Kvantum has configurable parameters like frame size and text margins.

That being said, I'll make yet another exception for this QML issue in Kvantum soon. 

This was *just one example* of how bad QtQuick behaves when a style has configurable parameters: it totally ignores them and assumes the most elementary look possible (as in Fusion, Breeze,...).

**Comment by tsujan** [comment]
Done in the latest commit. Please take a look at this new line:

https://github.com/tsujan/Kvantum/blob/40efa29b6a0c74fd2d9c64d5ece21e19d6b687e7/Kvantum/style/Kvantum.cpp#L13330

**Comment by tsujan** [comment]
BTW, to see how poor QtQuick is, try to resize the window of `test.qml` vertically -- with any widget style.

**Comment by trmdi** [comment]
Yes, QtQuick has lots of bad things, but from the user point of view, they would think the bug comes from Kvantum. So we should notice that.

Thank you. Your workaround works perfectly!

**Comment by tsujan** [comment]
> but from the user point of view, they would think the bug comes from Kvantum.

It's a mystery to me why so many *good* Qt programmers -- KDE devs included -- don't know much about `QStyle`. If it wasn't so flexible, Kvantum would be impossible.

In recent years, Kvantum started to have so many users. Understandably, users may not think about why, for example, a dark toolbar with a light theme is possible with Kvantum but not with other Qt styles. I can't expect users to be on my side in this regard.

So, in a sense, I'm alone and I know that. However, I won't get tired of saying that *styling QML apps with QStyle is wrong and all GUI problems in QML are caused by that.* KDE's direction is also wrong. It has started to create a split in the look and feel in addition to the GTK-Qt split for no good reason.
