### ISSUE TITLE
Questions and some issues (help)

### ISSUE THREAD

**Issue by Luwx** [tsujan/Kvantum#315]
I came across some issues while polishing up my themes:

##### 1) Buttons with/without text have different height

![screenshot_20181212_184256](https://user-images.githubusercontent.com/33076480/49903228-a6d95d00-fe4d-11e8-9ba2-0391fc664503.png)

I removed bottom and top text margins so all buttons would have the same height (24px), it didn't work. Am i missing any settings?

##### 2) Default push button has different style

![screenshot_20181212_193908](https://user-images.githubusercontent.com/33076480/49903632-f8ceb280-fe4e-11e8-8e5f-70c5a295dde4.png)

 The rounding is not right. Can you reproduce this?
I have also made a inactive state for the default button but it was not affected.

##### 4) Can icon color be affected by inactive windows? 

I changed the color of inactive.window.text.color but only the text was affected.

##### 5) Can the standard combo box have this style? (Different background for the arrows)

![screenshot_20181212_184152](https://user-images.githubusercontent.com/33076480/49904426-3a605d00-fe51-11e8-8a1b-f1b493fbf712.png)

Thanks!

**Comment by tsujan** [comment]
> 1) Buttons with/without text have different height

That is NOT an issue. The widget height is calculated based on its contents in all widget styles. Choose the Breeze/Fusion style and a big font and you'll see the same thing -- in the case of Breeze/Fusion, the font size should be big enough because Breeze/Fusion uses 24-px icons for its toolbars, while most Kvantum themes use 16-px ones.

Anyway, with Kvantum, you could easily increase toolbar icon size by using Kvantum Manager and in that way, you could align those buttons for yourself (although some apps have hard-coded sizes).

> 2) Default push button has different style

That's not my theme. You either use another theme/SVG file or had customized KvMojave but didn't restore its settings after an upgrade (Kvantum Manager → Configure Active Theme → Restore).

> 3) Is it possible to have separators in grouped toolbar buttons, like in tabs? (Not only for toggle state)

No, for technical reasons whose full explanation is beyond the scope of this reply but in short, grouped toolbar buttons can have multiple toggled buttons, while there's only one active tab.

> 4) Can icon color be affected by inactive windows?

Those aren't ordinary icons but *symbolic icons* that are only supported by KDE and LXQt. Their color can't be affected by inactiveness because of the code KDE and LXQt use. That code is separate from Kvantum but Kvantum is the only widget style that supports symbolic icons *completely*.

An an LXQt member, I could change the LXQt code but other members might consider that an overkill because it wouldn't affect Breeze, Fusion or any other style other than Kvantum.

> 5)  Can the standard combo box have this style? (Different background for the arrows)

Yes, of course! It depends on the theme. Update to the latest Kvantum and check the theme `KvRoughGlass`! However, since I'm not a fan of those double arrows, I haven't included them in any theme except for `KvRoughGlass`.

**Comment by tsujan** [comment]
BTW, if you wanted to get rid of dotted focus rectangles in the custom theme you made, you could just add these lines to it config file:
```
[Focus]
interior=false
frame=false
```
If you want it to have a different color and have a frame expansion too, then you'll have to add an "expand-" focus interior element to your SVG file. Everything is explained in Kvantum doc but you could also examine the other themes.

**Comment by tsujan** [comment]
To be thorough, I also give you an example of aligning iconsless toolbar buttons. This is with a 16-px toobar icon size:

![1](https://user-images.githubusercontent.com/981076/49906978-76afaf80-fe89-11e8-8997-4c3aeba8e3b1.png)

But here, I increased the toolbar icon size to 19:

![2](https://user-images.githubusercontent.com/981076/49906990-85966200-fe89-11e8-9832-c17f92256fa4.png)

**Comment by Luwx** [comment]
Aparently KDE apps set specific toolbar icon sizes based on their availability, but even when choosing a bigger size the buttons still not aligned :(
![screenshot_20181212_225221](https://user-images.githubusercontent.com/33076480/49908629-a8615000-fe62-11e8-8c6d-ec7758ec44da.png)

I can reduce the frame so that the button with text is 24px tall, but when it uses only icons the button is really small and the icon almost touches the border.

 Does min_height not apply here? 

--
About the default button, it was missing the expander!  Now it looks correct, although changing the window state does not seem to affect it yet:

![peek 2018-12-12 22-34](https://user-images.githubusercontent.com/33076480/49909191-f1b29f00-fe64-11e8-9e7d-adc23c5c5ccb.gif)
--
>>Those aren't ordinary icons but symbolic icons that are only supported by KDE and LXQt. Their color can't be affected by inactiveness because of the code KDE and LXQt use. That code is separate from Kvantum but Kvantum is the only widget style that supports symbolic icons completely.

I supose the same is valid to the toolbar icon state (toggle, hover), right? 

--

>>Yes, of course! It depends on the theme. Update to the latest Kvantum and check the theme KvRoughGlass! However, since I'm not a fan of those double arrows, I haven't included them in any theme except for KvRoughGlass.

I checked KvRoughGlass and it looks like the arrows and the text are sharing the same background. What was looking for is something similar to the editable combo box in KvYaru.

**Comment by tsujan** [comment]
> but even when choosing a bigger size the buttons still not aligned

That just means the icon size you've chosen is not enough to compensate for your font height; it should be increased by 2 pixels.

KDE apps get their toolbar icon size from KDE settings; that's in their codes. However, unlike Kvantum, KDE provides only a few toolbar icon sizes (16, 22, 32, 48). That's a bad design that KDE devs have kept for a long time.

In [my above screenshot](https://user-images.githubusercontent.com/981076/49906990-85966200-fe89-11e8-9832-c17f92256fa4.png), I wasn't limited to KDE, so I didn't need huge toolbar icons to align them.

> Does min_height not apply here?

You can also play with it in terms of font height but it isn't specific to toolbar buttons.

> I supose the same is valid to the toolbar icon state (toggle, hover), right?

Symbolic icons only have 2 colors, wherever they appear. Selection tint and hover tint are for all icons, whether symbolic or not.

**Comment by jorgicio** [comment]
Hi! I can't find where to ask and I know this is not an issue, but I can't find any information about this:
Where or how can I change the tab size? At least in applications like Dolphin, tabs are small.
I'm using Arc with Arc-KDE and Arc Darker as Kvantum theme.

Thanks.

**Comment by tsujan** [comment]
Tab sizes are set by their contents. These are Dolphin's tab sizes with `KvArc` that comes with Kvantum and with the font size I use (I don't think they're small):

![dolphin](https://user-images.githubusercontent.com/981076/56096823-28c3ba80-5f02-11e9-92b2-7cb34d566f3c.png)

However, you could add the keys `min_width` and/or `min_height` under `[tab]` in the `kvconfig` file of the theme or change them if they already exist. See `Theme-Config.pdf` for explanations of these keys (they're flexible).

**Comment by jorgicio** [comment]
That's my case in Arc Darker, hence my question:

![imagen](https://user-images.githubusercontent.com/554710/56096896-c5169e80-5ebb-11e9-8b53-f179b7cc2a92.png)
Tried both with KvArc and Arc colors, and the result is the same.

I'll try what you mentioned.

Thanks.

**Comment by tsujan** [comment]
> That's my case in Arc Darker, hence my question:

Yes, they're small but it isn't my theme.

Try something like
```
min_width=+0.3font
min_height=+0.3font
```
under the [Tab] section.

EDIT: It's [Tab], not [tab] -- I corrected my previous commit.

**Comment by tsujan** [comment]
And something else is also wrong with that theme: icons of inactive tabs are white; intentional?

**Comment by tsujan** [comment]
Yet another problem I can see in your screenshot: there's a line below the active tab ;)

**Comment by jorgicio** [comment]
> > That's my case in Arc Darker, hence my question:
> 
> Yes, they're small but it isn't my theme.
> 
> Try something like
> 
> ```
> min_width=+0.3font
> min_height=+0.3font
> ```
> 
> under the [Tab] section.
> 
> EDIT: It's [Tab], not [tab] -- I corrected my previous comment.

Did it with other values than 0.3 and now working as expected.

Thanks.
And yes, icons of inactive tabs are white, they came like this (I'm using Papirus).
The line below the tab is also intentional, is part of the theme, I think.

**Comment by tsujan** [comment]
> Did it with other values than 0.3

Good. 0.3 was just an example.

> And yes, icons of inactive tabs are white, they came like this (I'm using Papirus).

It shouldn't related to the icon theme but to a wrong color for inactive tab text: since it has a high contrast with the window text color, the symbolic SVG icon becomes white (if it's really a symbolic SVG icon). The solution is to use black text with alpha, like `#00000067`.
