### ISSUE TITLE
Icons don't scale on HiDPI screens

### ISSUE THREAD

**Issue by mattpepin** [tsujan/Kvantum#316]
On HiDPI screens, I have to manually double all icon sizes to account for the scaling factor (200% in my case). Text is fine though. Is it possible to scale automatically?

**Comment by tsujan** [comment]
Kvantum supports HDPI completely. First, please upgrade to the latest git Kvantum if possible. Then, set the environment variable `QT_SCALE_FACTOR` to 2 (all DEs have places for that, especially KDE) and log out and log in.

To test HDPI scaling in a terminal, use `QT_SCALE_FACTOR=2 APP` (replace `APP` with any Qt5 app, like `dolphin`, `kate` or `kvantumpreview`). All icons and texts should be scaled. An example, with 3 for `QT_SCALE_FACTOR`:

![dolphin](https://user-images.githubusercontent.com/981076/50234453-faf2bd00-03ca-11e9-87d8-cf2333d3d9db.png)

**Comment by mattpepin** [comment]
Hum, that's weird. Setting QT_SCALE_FACTOR to 2 also doubles text size. Might be a Gnome/Wayland issue.

**Comment by mattpepin** [comment]
Here's what I mean:

Default icon size, no QT_SCALE_FACTOR
![image](https://user-images.githubusercontent.com/582959/50242478-856df900-0398-11e9-97df-756b9eafd7cc.png)

2x icon size, no QT_SCALE_FACTOR
![image](https://user-images.githubusercontent.com/582959/50242505-974f9c00-0398-11e9-9dbb-944ebb805883.png)

Default icon size, QT_SCALE_FACTOR=2
![image](https://user-images.githubusercontent.com/582959/50242514-9dde1380-0398-11e9-8cda-5ea00b4cb8a7.png)

**Comment by tsujan** [comment]
With HDPI screens, you DO NOT need to change any icon/font size but just set `QT_SCALE_FACTOR`.

GTK has a similar environmental variable for GTK apps, namely `GDK_SCALE`.

I don't know which Qt platform integration program you use under Gnome (you surely need one) but, apparently, it has a problem. KDE and LXQt have their own Qt platform integration, of course, because they are Qt DEs. This is Kvantum Manager with a scale factor of 2 under KDE and with `KvYaru` (formerly, `KvCommunitheme`) and the latest git Kvantum:

![kvyaru](https://user-images.githubusercontent.com/981076/50244074-3d74c380-03e4-11e9-8294-848dcaea563e.png)

**Comment by tsujan** [comment]
Another important thing:

When you use `QT_SCALE_FACTOR` correctly (with a valid Qt platform integration, of course), not only fonts ans icons become bigger but also the sizes of *all GUI components* are increased. For example, in my above screenshot, the button corners are rounder and the button borders are thicker (2 px instead of 1 px). That's why we use scale factors, instead of changing font/icon sizes.

**Comment by mattpepin** [comment]
Thanks, I found a way to make it work. First, I reset all icon sizes to their defaults. Then, here's what I did in Arch Linux (for reference if it can help someone else):

Install kvantum-qt5-git (https://aur.archlinux.org/packages/kvantum-qt5-git/)
Install qgnomeplatform-git (https://aur.archlinux.org/packages/qgnomeplatform-git/)
Add the following to ~/.profile:
```
export QT_STYLE_OVERRIDE=kvantum
export QT_AUTO_SCREEN_SCALE_FACTOR=1
```
Re-login.


Thanks for the pointers in the right direction!

**Comment by tsujan** [comment]
Happy to know you found a way under Gnome :) Strange that it isn't easy with Gnome!

I think `QT_SCALE_FACTOR` is better than `QT_AUTO_SCREEN_SCALE_FACTOR` because the latter doesn't change the font size -- at least, Qt doc says so: http://doc.qt.io/qt-5/highdpi.html

Could you attach a screenshot for me to see if *everything* (except for fonts) is made larger with `QT_AUTO_SCREEN_SCALE_FACTOR`?

**Comment by mattpepin** [comment]
Ok, maybe it's not 100% fixed then... It's only working correctly using QT_AUTO_SCREEN_SCALE_FACTOR=1. Using QT_SCALE_FACTOR=2 makes the text too big.

QT_SCALE_FACTOR=2
![image](https://user-images.githubusercontent.com/582959/50248441-11881c80-03a9-11e9-8e91-ff38571d7ced.png)

QT_AUTO_SCREEN_SCALE_FACTOR=1
![image](https://user-images.githubusercontent.com/582959/50248536-5744e500-03a9-11e9-9057-b6388dd8eb09.png)

**Comment by tsujan** [comment]
Thanks! `QT_AUTO_SCREEN_SCALE_FACTOR=1` seems OK; everything is made larger correctly in your second screenshot.

`qgnomeplatform` may have a problem with `QT_SCALE_FACTOR`. I remembered that I'd tried `lxqt-qtplugin` under gnome (by setting `QT_QPA_PLATFORMTHEME` to `lxqt`) on another computer and `QT_SCALE_FACTOR` worked correctly.

Anyhow, if you encounter a problem with `QT_AUTO_SCREEN_SCALE_FACTOR=1`, please tell me!

**Comment by kyentei** [comment]
@mattpepin Sorry to approach you through here, but I can't - for the life of me - figure out which window decorations theme you're using with kvyaru. Could you please tell me?

**Comment by tsujan** [comment]
> ... which window decorations theme you're using

KWin + [BreezeEnhanced](https://github.com/tsujan/BreezeEnhanced) (under KDE and LXQt).

**Comment by kyentei** [comment]
Thanks!

**Comment by tsujan** [comment]
You're welcome.
KWin supports various title-bars but the Breeze title-bar and those forked from it are much better in terms of resource usage, shadow quality, code update, etc.

**Comment by tsujan** [comment]
And if you use KVantum+Breeze (or BreezeEnhanced  or another Breeze fork), don't forget to apply the KDE color scheme corresponding to the theme, for the title-bar to match the theme.

**Comment by Rapiz1** [comment]
> Kvantum supports HDPI completely. First, please upgrade to the latest git Kvantum if possible. Then, set the environment variable `QT_SCALE_FACTOR` to 2 (all DEs have places for that, especially KDE) and log out and log in.
> 
> To test HDPI scaling in a terminal, use `QT_SCALE_FACTOR=2 APP` (replace `APP` with any Qt5 app, like `dolphin`, `kate` or `kvantumpreview`). All icons and texts should be scaled. An example, with 3 for `QT_SCALE_FACTOR`:
> 
> ![dolphin](https://user-images.githubusercontent.com/981076/50234453-faf2bd00-03ca-11e9-87d8-cf2333d3d9db.png)

`QT_SCALE_FACTOR`  with `.Xresource` setting DPI will cause double scaling. And the latter is necessary for GTK program scaling. So I'm weather getting too small QT program icons or too small GTK program

**Comment by Rapiz1** [comment]
This works for me.[copied from here](https://ricostacruz.com/til/fractional-scaling-on-xorg-linux)
```
export QT_AUTO_SCREEN_SET_FACTOR=0
export QT_SCALE_FACTOR=2
export QT_FONT_DPI=96
```
