### ISSUE TITLE
Kvantum doesn't change the colors

### ISSUE THREAD

**Issue by TheDevKiller** [tsujan/Kvantum#325]
Hey! I don't know why but when I change my kvantum theme with kvantum manager, it doesn't change anything. When I start kvantum manager, it has the correct theme but when I launch dolphin and kvantumpreview, no one has the good theme. I think they have the default theme.

**Comment by tsujan** [comment]
It should have been caused by a bad/wrong installation/compilation. If you've installed Kvantum with a deb, rpm,.. package, it might be corrupted or compiled against another version Qt. Etc.

Uninstall the deb, rpm,... package if any, grab the latest git Kvantum source and compile and install it cleanly with qmake or cmake, as is explained in the file INSTALL.

(If the problem persists, you should have a second installation in `/usr/local`, which you'll have remove manually).

Anyway, the problem isn't in Kvantum.

**Comment by tsujan** [comment]
The only thing I can say with certainty is that your problem isn't in Kvantum.

A problem should be reproducible for it to be really an issue in the program. This isn't. 30 minutes ago, I needed to install Kvantum on another machine: no problem whatsoever.

**Comment by TheDevKiller** [comment]
Ok ok I'll figure it out. Thank you anyway

**Comment by tsujan** [comment]
My last guess (since you provided no info other than you can't change the style): you haven't activated Kvantum at all.

See Kvantum Manager -> Change/Delete Theme.

**Comment by tsujan** [comment]
> I'd like to provide more infos but I don't have it

Qt and KDE versions might help (but no promise). Also, do a system upgrade if there's any; then restart.

I'm on Manjaro testing, BTW.

**Comment by TheDevKiller** [comment]
Ah x) I really don't see the problem so. Thank you anyway
