### ISSUE TITLE
[Question] Warning dialog button

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#329]
It's possible use specially class for warning dialog button? For example, remove dialog or critical message...
http://doc.qt.io/qt-5/qmessagebox.html#warning
I mean use another color for confirmation buttons. This used on mostly GTK Themes:
![image](https://user-images.githubusercontent.com/8083855/51727105-d9e55200-2083-11e9-901c-b7acb2c65c9c.png)
It's will be good for compatibility GTK with Qt

**Comment by tsujan** [comment]
> remove dialog or critical message...

Even if it was possible, it should never be done. Kvantum shouldn't interfere with such things; they're determined by the app code.

> I mean use another color for confirmation buttons

Qt dialog buttons have one special property: see Kvantum Manager → Miscellaneous → Dialog button layout. You could choose Gnome layout there. Moreover, unlike in GTK+, their number can be 1 to 18.

Do you mean making them as wide as in your screenshot? I don't think that's possible because they're like any other button and have predefined sizes (or, as in Qt terms, "size hints"). However, I could check it.

**Comment by tsujan** [comment]
OK, I checked: gtk dialog buttons aren't always that wide; it depends on the gtk theme. And Qt buttons follow the sizePolicy that's given to them by the app.

**Comment by trmdi** [comment]
@tsujan
I think he wants to make some buttons red like the screenshot, not the width.

**Comment by tsujan** [comment]
As mentioned above, the buttons of a dialog aren't different from other buttons -- they don't have a special type of their own -- and so, are drawn like other buttons.

**Comment by varlesh** [comment]
@trmdi Yes, i mean another color.
@tsujan Ok, thx for your clarification
