### ISSUE TITLE
a minimum size for spinbuttons

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#33]
there should be a way to set a minumum size for spinbuttons. Also I already set the minumum size of lineedits and buttons to 22px but spinbuttons are still tiny compared to them

a comparison with fusion on the lxqt panel settings dialog:

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/6937817/c17d20b0-d85e-11e4-8333-aa2214bdffd0.png)

Also it seems they are 2 different kinds of spinbuttions since changing the top border only affects 2, would also explain why the up/down arrows look different(space between)

according to the ui file all four are qspinbox widgets https://github.com/lxde/lxqt-panel/blob/master/panel/config/configpaneldialog.ui

**Comment by tsujan** [comment]
Spin buttons are horizontal by default in Kvantum. Some apps give a predetermined, non-expanding space to spinboxes, supposing that their buttons should be vertical. In such cases, Kvantum decreases the button widths from 16 to 8px for the text to be displayed correctly.

In your screenshot, the "Groesse" spinbox has enough space, so it's drawn in the default way. But the GUI has given predetermined widths to the "Icon size" and "Laenge" spinboxes, suitable only for vertical buttons. Therefore, Kvantum has decreased their button widths for those spinboxes to fit into the availabe space.

In the last few days, I've experimented with stricter criteria for such cases and will add them to Kvantum soon. I'll also see what I can do with the spin heights.

BTW, Kvantum has also a key for vertical spin buttons (see Kvantum Manager). You could use it with appropriate indicator size and arrow images if you don't like such exceptions. However, those exceptions exist in GUI's, not in Kvantum. Developers don't see them because they ignore the possibility of horizontal spin buttons.

**Comment by tsujan** [comment]
I forgot to say that if you open "configpaneldialog.ui" with Qt4/Qt5 Designer, all spinboxes look the same. So, the space limitation should be set somewhere in the code of lxqt-panel itself.

**Comment by sixsixfive** [comment]
>BTW, Kvantum has also a key for vertical spin buttons 

nice never knew that

>So, the space limitation should be set somewhere in the code of lxqt-panel itself.

but it seems all other styles i've tried(oyxgen, qftkstyle, windows, fusion) have a workaround for this

**Comment by tsujan** [comment]
> but it seems all other styles i've tried(oyxgen, qftkstyle, windows, fusion) have a workaround for this

They don't need any workaround because none of them can have horizontal spin buttons.

**Comment by tsujan** [comment]
Now the key "size.minheight" under the IndicatorSpinBox section (and also some others) should have effect. The "size.minwidth" will also have effect only if the widget width is not predetermined (in the app's code).

**Comment by sixsixfive** [comment]
>However, I think what you want is a spinbox that aligns with its adjacent button. I'll see what I can do.

exactly, its also still ugly (i don't see any effect..)
![aaa](https://cloud.githubusercontent.com/assets/3780774/6945310/1cf71060-d899-11e4-942f-8107cac61312.png)

**Comment by tsujan** [comment]
Now spinboxes are aligned with iconless (tool and push) buttons and combos if all of them inherit PanelButtonCommand and have the same vertical text margins.

The height of spinboxes can also be adjusted with "text.margin.top" and "text.margin.bottom" under the LineEdit section (because only their line-edits have text).

You don't need to change anything in your theme, Glare, as this screenshot (taken with Qt Designer) shows:

![alignment](https://cloud.githubusercontent.com/assets/981076/6969323/05944b00-d983-11e4-9884-08b04ab2e23b.png)

Please test! I may change some calculations later but will keep the alignment in the above sense.

**Comment by sixsixfive** [comment]
works in the designer, but not the app itself :/

**Comment by tsujan** [comment]
Did you logged out and in again? As it's about a panel, the app may have a cache.

**Comment by sixsixfive** [comment]
yepp, rebuild lxqt from git, rebuild kvantum -->reboot-->no effect

**Comment by tsujan** [comment]
I see nothing in configpaneldialog.cpp from the lxqt-panel source that sets a specific height to those spinboxes or combos.

**Comment by sixsixfive** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/3780774/6988319/697d43c4-da50-11e4-83a5-e4a81559bb90.png)

**Comment by sixsixfive** [comment]
also it seems the change broke the toolbar buttons(see screenshot) there is now more space between them)

**Comment by tsujan** [comment]
What about now?

> also it seems the change broke the toolbar buttons(see screenshot) there is now more space between them/they are wider)

Because now button text margins are also applied when buttons have icons only. That seems more logical to me because text margins are in fact label margins and icons belong to labels.

**Comment by sixsixfive** [comment]
>What about now?

still nothing

>That seems more logical to me because text margins are in fact label margins and icons belong to labels.

maybe this is great for all kind of buttons, but my toolbar looks now totally weird, maybe you could make an exception for toolbars?

**Comment by tsujan** [comment]
> but my toolbar looks now totally weird

The buttons look distant from each other with your theme because you have text.margin.left/right=10 under PanelButtonCommand. Doesn't setting a smaller value for them under PanelButtonTool solve your problem? Buttons on toolbars are toolbuttons and their section is PanelButtonTool.

> also something changed the entry from "custom background image" has now the same size as the plus button

Such an alignment was exactly what I wanted to achieve, and you wanted it too when opening this issue, didn't you?

**Comment by sixsixfive** [comment]
>Such an alignment was exactly what I wanted to achieve, and you wanted it too when >opening this issue

yepp but it still refuses to work in the groupbox

>Doesn't setting a smaller value for them under PanelButtonTool solve your problem?

indeed it does

**Comment by tsujan** [comment]
> yepp but it still refuses to work in the groupbox

Could you please be more specific? A screenshot?

**Comment by sixsixfive** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/3780774/6989713/9ee329de-da5f-11e4-95f2-00072604f54b.png)

**Comment by tsujan** [comment]
Oh, yes, I know. It isn't related to groupbox. The height of those spinboxes is still an enigma to me.

I added some missing parentheses to the code. Please test again (for that spinbox height in the app). If it isn't fixed yet, I'll think about it tomorrow.

**Comment by tsujan** [comment]
Strange!! My last commit isn't pushed!

**Comment by tsujan** [comment]
Now it's pushed. It seems I need some sleep :)

**Comment by sixsixfive** [comment]
r174 -> no change :(

**Comment by tsujan** [comment]
The problem was deeper than I thought. I remembered I'd seen a similar issue in Qt5 QupZilla too. It may be a Qt5 bug. I included a workaround. Please test!

Your line-edits and spinboxes don't inherit PanelButtonCommand. So, with big fonts you might see a little difference in heights. You have compensated that for normal font sizes by setting size.minheight but if you want the alignment with large fonts too, set both "text.margin.top" and "text.margin.bottom" to 3 under LineEdit (to compensate for 1px frame widths).

BTW, please test with horizontal spin buttons too; the problem you mentioned earlier should be fixed now.

Feel free to give me bad news about failure ;)

**Comment by sixsixfive** [comment]
yepp that it works with both vertical an horizonal spinbuttons (=

**Comment by tsujan** [comment]
I should find a way to report this weird bug (if it is a bug in Qt5 plugin system).
