### ISSUE TITLE
[FreeBSD]Fail to build: 0.10.9 and HEAD.

### ISSUE THREAD

**Issue by rigoletto-freebsd** [tsujan/Kvantum#340]
Hello,

I am experiencing an issue to build the last Qt5 version of Kvantum on FreeBSD (Qt4 build fine). Could you take a look to see if this is platform specific?

[Kvantum-qt5-0.10.9.log](https://github.com/tsujan/Kvantum/files/2845596/Kvantum-qt5-0.10.9.log)

Thank you.

**Comment by tsujan** [comment]
That's because of this condition, near the top of `/Kvantum/style/themeconfig/ThemeConfig.cpp`:
```cpp
#if defined Q_WS_X11 || defined Q_OS_LINUX
```
You could change it as follows and retry:
```cpp
#if defined Q_WS_X11 || defined Q_OS_LINUX || defined Q_OS_FREEBSD || defined Q_OS_OPENBSD
```
The above-mentioned condition may appear in other places too, in which case, you'll need to change them too.

Users of *BSD systems have kindly added *BSD support to my other apps. Also in this case, I need a *BSD use to do so -- I can only support Linux. So, please tell me about the result after that change and whether other changes are also required!

**Comment by rigoletto-freebsd** [comment]
Built fine now. :+1:

 Thanks!

**Comment by rigoletto-freebsd** [comment]
Btw, I'm Kvantum maintainer on FreeBSD now.

**Comment by tsujan** [comment]
Thanks for telling me! I'l change it in the source soon.

> Btw, I'm Kvantum maintainer on FreeBSD now.

Great! Please tell me if you encounter any problem on *BSD. It's good to have a nice *BSD support :)

**Comment by rigoletto-freebsd** [comment]
Great! Thank you. :-)
