### ISSUE TITLE
[Wayland]Sidebar view in KDE System Settings is not visible when using themes with transparency/blur

### ISSUE THREAD

**Issue by mthw0** [tsujan/Kvantum#343]
It looks like this: https://imgur.com/a/CGndhrG, but in the screenshot there is actually transparent area with blur, not a black area. I tested this with Fluent-kvantum, Aether-kv and MateriaBlur themes, they are all affected, so I figured it's probably a bug in Kvantum or even in KDE. Could you look at it?

**Comment by tsujan** [comment]
Wayland isn't ready for window translucency yet and I've disabled it in Kvantum. I don't know how you enabled it again (patching the code?) but the problem is either in Qt/KDE wayland support or in wayland itself. Nothing can be done on Kvantum's part except for waiting.

Fortunately, in recent months, there were considerable improvements in Plasma Wayland and I'm sure they will be continued. However, Wayland still has serious problems and can't be compared to X11, especially with regard to translucency.

**Comment by tsujan** [comment]
Oh, my bad! I enabled window translucency under Wayland with Qt >= 5.11 because most issues were fixed. The problem with that window can be about QtQuick. Also see https://github.com/tsujan/Kvantum/issues/333#issuecomment-459472496

**Comment by mthw0** [comment]
Is there something I can do about this, like reporting to KDE bugtracker?

**Comment by tsujan** [comment]
I don't know. KDE devs are already aware of the problems QtQuick can cause. They hope those problems will be fixed in future, while I think they aren't fixable; they can be just made hidden with Breeze.

**Comment by tsujan** [comment]
BTW, enabling translucency under wayland was a reasonable risk I took. However, it was a risk ;)
