### ISSUE TITLE
Adwaita refresh theme.

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#347]
We haven't had a good solution to to the gtk-qt theming mess since the demise of qtcurve. None of the default themese span toolkits besides Yaru.

Right now there is both Adwaita-QT and Breeze-gtk lack polish, and the Adwaita-QT will is going to become irrelevant now that Gnome has updated their default theme. So the bottom line is we have a million themes but none of them really work.

I know this is a big project which few people would want to wade into, but please leave this issue open. I might eventually link it on bounty source and reddit to solicit interest.

**Comment by tsujan** [comment]
I made `KvGnome` a long time ago but Gnome's appearance changed and I felt free to change `KvGnome` according to my taste, so that it isn't very similar to Gnome's theme anymore.

I don't know about "Adwaita refresh". To which GTK version does it belong? Would you please be more specific? Do you want me to make `KvGnome` and its dark variant similar to Adwaita again?

**Comment by tsujan** [comment]
And please understand the situation: The problem with following Gnome is that Gnome devs don't know what they want, so that following their work will be meaningless after a while. That's the case both for coding in GTK+ and in the making themes like that of Gnome.

I had a reason to say goodbye (alongside some curses) to GTK+ after all.

**Comment by ripefig** [comment]
I get some of the frustration, but still - their old Adwaita theme has been was the most stable of all gtk themes. And it's the only theme that 100% works for gtk and looks elegant (imho - I just really really love gnome's visuals). Plus, when you install a flatpak, you get Adwaita-themed app, unless you want to mess with theme installation etc. 

So if you were to copy any gtk theme, it makes sense to follow the official one. Linux really needs a default theme for the entire ecosystem. KVGnome may be a good starting point for this, I am not sure.

**Comment by tsujan** [comment]
I can change `KvGnome` and its dark variant to match the latest gtk theme once in 6 months (= Gnome's cycle). Actually, I wanted to remove them because I didn't like them (preferring KvGnomeAlt and, especially, KvGnomish). Now, they can have a purpose ;)

However, I'm very busy with coding, So, it may take a while.

> So if you were to copy any gtk theme, it makes sense to follow the official one.

It's just a matter of fair cloning (100% cloning isn't possible between Qt and gtk). Kvantum can do it and, fortunately, the gtk code is irrelevant here.

**Comment by ripefig** [comment]
Yeah, it's a bad idea to just blindly copy 1:1 because the widgets are different. Adwaita-QT tried that and they it paradoxically had the opposite effect (i.e. had they taken more liberties, they would have gotten closer to the Gnome look).

**Comment by tsujan** [comment]
> ... because the widgets are different

Exactly. There's no one-to-one correspondence between Qt and GTK+ -- not even between their buttons. But there are enough similarities.

**Comment by tsujan** [comment]
OK, I checked the latest gtk theme, made preliminary changes to KvGnome (no commit yet) and liked it as a simple light theme:

![adwaita](https://user-images.githubusercontent.com/981076/53497703-0264cf80-3aba-11e9-8ef2-9c4785dd1a4b.png)

If Gnome devs keep it as good as this, I'll have no problem with updating it whenever needed.

**Comment by ripefig** [comment]
There is an issue with the tabs. Normal tabs are very different from headerbar tabs in Adwaita. I don't know if KVGnome is the best starting point. The Materia theme doesn't look anything like Adwaita but it may be a cleaner start.

https://store.kde.org/p/1229134

**Comment by tsujan** [comment]
@ripefig 
(1) There are 2 kinds of tabs in Qt: ordinary tabs and "document mode". These will be KvGnomes's doc mode tabs:

![doc_mode](https://user-images.githubusercontent.com/981076/53550948-3c32e600-3b4d-11e9-833b-cfbb6741728d.png)

GTK doesn't have ordinary tabs of Qt. Ordinary tabs will be drawn like centered buttons, as in the previous screenshot.

(2) GTK has a header bar, not a header bar tab. KvGnome's toolbar+menubar will be like that header bar, as in the above screenshot.

**Comment by tsujan** [comment]
Done. The new `KvGnome` fairly matches the latest Adwaita; more than that would be an obsession. It should be used with the latest git Kvantum; otherwise a few elements might not look right. Any previous customization of `KvGnome` should be removed before using its new version.

I'll do the the same for the dark variant later (not soon) and might polish `KvGnome` too.

The problem with a uniform look and feel is that many users may not like that look. Gnome devs seem happy to keep their eyes closed to this simple fact -- actually, to any fact -- but it's not my problem.

Personally, I don't like a few elements in the current Adwaita or `KvGnome`. Fortunately, most of them can be changed for Qt apps by using Kvantum Manager.

NOTE: The theme looks good under KDE and LXQt with KWin (with Openbox too). I don't know how Gnome users could change that ugly title bar of Gnome but, again, not my problem.

**Comment by emansom** [comment]
Relevant again.

https://blogs.gnome.org/aday/2022/01/13/human-interface-guidelines-libadwaita-1-0-edition/
