### ISSUE TITLE
Inconsistent/unexpected dragging behavior.

### ISSUE THREAD

**Issue by ripefig** [tsujan/Kvantum#358]
If you drag the titlebar to the edges of the screen, the window gets maximized/tiled in certain DEs.

If you drag by empty window chrome, the window gets dragged but the snapping features are unavailable.

This behavior isn't good. Is there a way to make sure the drag action takes advantage of DE snapping features?

**Comment by tsujan** [comment]
Dragging from inside window has become different from title-bar dragging for a while: it's now based on purely Qt methods and without X11 dependency (because of an unresolved bug in Qt's handling of X11). Hence the difference in behavior.

**Comment by tsujan** [comment]
> Is there a way to make sure the drag action takes advantage of DE snapping features?

It did before but I didn't want Qt bugs inside Kvantum. You could see those bugs in Breeze: 

(1) Run `kvantumpreview -style breeze` in terminal.
(2) Move the cursor over tool-bar buttons. You'll see the "hover effect".
(3) Drag the window from inside it (not from title-bar).
(4) Move the cursor over tool-bar buttons again. You will NOT see any hover effect because of a bug in Qt -- until you click somewhere.

Repeat the same thing with kvantum and you won't encounter any problem.
