### ISSUE TITLE
Tabs improvement in Mojave themes

### ISSUE THREAD

**Issue by gikari** [tsujan/Kvantum#361]
Apple's Mojave has two variations of tabs - the first one, that is used now in Kvantum themes:
![macOS_tab_1](https://user-images.githubusercontent.com/14205339/54078681-a2ea9900-42dd-11e9-84c1-0ff3aa6af8f3.png)

and the second one, which is used, for example, in Finder, Safari, and Terminal apps: 
![finder](https://user-images.githubusercontent.com/14205339/54078714-7be09700-42de-11e9-91ec-c232dc7a5da0.png)
![safari](https://user-images.githubusercontent.com/14205339/54078708-489e0800-42de-11e9-9491-f443d4f542b5.png)
![terminal](https://user-images.githubusercontent.com/14205339/54078730-90249400-42de-11e9-97ec-ddae82866819.png)

Could Mojave theme have something like these tabs from above in _document mode_? 
So Dolphin, Falcon, Konsole and other apps may have different tabs.

Multiple tabs in Dolphin, Falkon and Konsole looks like this now:
![dolphin](https://user-images.githubusercontent.com/14205339/54078765-088b5500-42df-11e9-9f3d-b29c895acfee.png)
![falkon](https://user-images.githubusercontent.com/14205339/54078815-08d82000-42e0-11e9-9a0b-e2e03e5b7cc1.png)
![konsole](https://user-images.githubusercontent.com/14205339/54078813-f4942300-42df-11e9-810c-be7f12701b92.png)

**Comment by tsujan** [comment]
Here, I change the active Kvantum theme once in a while but KvMojave and its dark variant are among themes that I may use for weeks. I've made them in a way that they don't contain ugly elements. The second kind of tabs in your screenshots don't look elegant to me.

That being said, tastes are different, of course, and the answer to your question is "yes." The theme can be changed so that doc-mode tabs become like in your screenshots. You could consult `Theme-Making.pdf` → "Floating Tabs" and change the theme according to your taste (in KvaMojave themes, button elements are also used for tabs, so you may want to add "floating-" button elements).

**Comment by gikari** [comment]
Thank you for assistance. Is it possible to change a color (and some other parameters, like margins) of the floating tabs independently of the normal tabs?

**Comment by tsujan** [comment]
> Is it possible to change a color (and some other parameters, like margins) of the floating tabs independently of the normal tabs?

Yes, because element colors are inside the SVG file. Text colors are inside the `kvconfig` file and are the same for all tabs. Also frame widths and text margins are the same but frame shapes are in the SVG file.

With a little SVG skill, you could make doc-mode tabs have a rectangular shape with a 1-px border (although the frame widths are 3 px, you could put 1-px rectangles inside 3-pix ones and group them together to make frame elements...).

Check `KvGnome` or `KvFlatLight` to see how different the tabs can be in the doc-mode!

Kvantum includes so many parameters and SVG is so flexible. What you can do with a theme is only limited to your SVG skill and your knowledge of Kvantum parameters (all of which are documented inside the `doc` directory -- trust the documentation and you could do many things).

**Comment by tsujan** [comment]
There is one limitation in `KvMojaveLight`: toggled (selected) doc-mode tabs should have a high contrast with the normal ones because ordinary tabs are so. That's because Kvantum doesn't support different text colors for doc-mode tabs.
