### ISSUE TITLE
menuitem size

### ISSUE THREAD

**Issue by 4fury** [tsujan/Kvantum#362]
Selam!
I want to squeeze menuitem height. For example, up to the font size. I try zero value frame padding ang text margin. But unsuccessed.

**Comment by tsujan** [comment]
The text you see doesn't define the height. Qt and other toolkits add a small spacing to the top and bottom and calculate the height based on the biggest letter, considering underlines, etc.

Anyhow, this is what you could use:
```
[MenuItem]
...
frame=false
text.margin.top=0
text.margin.bottom=0
text.margin.left=0
text.margin.right=0
```

**Comment by 4fury** [comment]
https://u.teknik.io/WmHiR.png
According to your config. Height is obviously greater than the largest letter + the subscript and superscript characters.

If use qss
```
QMenu::item {
	padding: 0px;
}
```
https://u.teknik.io/SYtCm.png
But I can't use the qss. Because I'll must write absolutely all widgets. If I don't it I break half of the design.

**Comment by tsujan** [comment]
Apart from the fact that there are also other factors (like `min_height`, check box size,...), Kvantum never returns a sizes smaller than that of `QCommonStyle`. I've added this line intentionally:
```c++
  /* set the minimum to the default size */
  return s.expandedTo(defaultSize);
```

The above line is important because it respects what Qt considers the best size.

In `QCommonStyle`, we have:
```c++
h =  mi->fontMetrics.height() + 8;
```

QSS is not our concern because stylesheets are very different from `QStyle`.
