### ISSUE TITLE
0x00007ff9cade546a in Kvantum::Style::drawItemText(QPainter*, QRect const&, int, QPalette const&, bool, QString const&, QPalette::ColorRole) const 

### ISSUE THREAD

**Issue by davidedmundson** [tsujan/Kvantum#365]
see https://bugs.kde.org/show_bug.cgi?id=405801

I've had a bunch of these recently. It's hitting it from our QQC2 wrapper, so probably unchecked use of the widget in drawComplexControl

**Comment by davidedmundson** [comment]
I would guess this:

Kvantun.cpp:15485:
  if (const QCommandLinkButton *cbtn = static_cast<const QCommandLinkButton*>(painter->device()))

should be qobject_cast 

I don't want to build kvantum to test, if someone could, that would be helpful.

**Comment by tsujan** [comment]
> I would guess this:.... should be qobject_cast

No! Even `qobject_cast` causes a crash (with another backtrace). I guess that's an issue in QQC2.

Anyhow, I fixed the crash by removing all lines related to `painter->device()` and adding them to a much better place. Will make a commit soon.

And thank you very much for reporting the crash!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/438de186ca975c17d333d0293c1764c0e9a676a0

I didn't have a plan for releasing 0.11.0 so soon but, since it was about a crash, I might do it today -- as 0.10.11.

**Comment by tsujan** [comment]
By chance, I remembered what happened 3 days ago:

I used `static_cast` just for a hasty experiment on `QCommandLinkButton`. Then, I forgot about it and added a very senseless nullity check!

Of course, `qobject_cast` should have also caused a crash with QQC because QQC's paint device isn't a `QWidget`.

So, it was definitely my mistake: I always presupposed `QWidget` or its nullity with `QStyle` but, in this case, neither was relevant.
