### ISSUE TITLE
color selection, some performance issues

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#37]
not really a bug but annoying, I wonder why the gtkstyle is so fast here...

https://drive.google.com/file/d/0B_2_dsXrefR-SjlVcU9uV0x5R0E/view?usp=sharing

**Comment by tsujan** [comment]
Those color dialogs are OK and show no lagging here, under KDE. Perhaps this problem is related to how an external Qt5 theme engine is enabled under lxqt.
Windows and Gtk styles are internal. Could you install and test with Qt5 QtCurve?

**Comment by sixsixfive** [comment]
ok seems that it just requires more CPU power with kvantum than on any other engine (if there is only qarma(https://github.com/luebking/qarma) running i have no issues but performance decreases with every other opened window - maybe thats just the tradeoff for a pixmap/svg based engine.

**Comment by tsujan** [comment]
I reopen this issue because I don't have a clue about its cause yet. As I mentioned above, it doesn't exist under KDE. Why it appears under lxqt is still a mystery to me.

**Comment by sixsixfive** [comment]
also i redid the test with a plain openbox session so there is nothing running except openbox, qterminal and the qarma color selection

https://drive.google.com/file/d/0B_2_dsXrefR-MDRRc0dPTHlXSUE/view?usp=sharing

**Comment by tsujan** [comment]
Thanks for the info! Have you seen it anywhere besides qarma (or qarma based apps)? I ask that because I didn't test qarma, thinking that you meant any color selection dialog.

**Comment by sixsixfive** [comment]
yes the same issue (slowness) appears in pencil2ds color wheel but not in drawpiles(which is a different one), also qarmas color selection is the native qt color selection dialog so i'm encountering the same issue on all color selection buttons(like the previous mentioned from the lxqt panel https://github.com/tsujan/Kvantum/issues/35 ) also it seems to be a qt5 only issue since qt4configs color selection is not effected

**Comment by tsujan** [comment]
Very strange! I compiled and installed qarma and Pencil2d against Qt5. Neither under KDE nor under openbox, Pencil's color wheel or "qarma --color-selection" showed any lagging. And it made no difference whether I used "-style kvantum" or "export QT_STYLE_OVERRIDE=kvantum" for running them with Kvantum under openbox. I also used different Kvantum themes, including yours, but still no slowdown or extra CPU usage in color selections.

**Comment by tsujan** [comment]
Please test again and see if the issue is resolved now!
Please also tell me which video card/driver you use.

To make a long story short, I tested the matter with my older nVidia-based computer and, much to my surprise, I could see the problem everywhere (under KDE, Enlightenment, Gnome, openbox, IceWM). I found that it was related to Qt5 spinboxes. More surprisingly, what I did to fix it, wasn't specifically related to spinboxes!

Even if the issue is fixed for you too, two mysteries will remain: why couldn't I reproduce it on my Intel-based laptop? And what's wrong with Qt5 spinboxes?

**Comment by sixsixfive** [comment]
yepp its fixed (=

> why couldn't I reproduce it on my Intel-based laptop?

Hm, i did all those videos on an intel netbook...

**Comment by tsujan** [comment]
Glad to know it's fixed for you. I think the real cause was that Qt5 isn't as fast as Qt4 in getting X11 info.

> Why has kvantum no borders around the selected colors?

It does! It's under the Focus section.
If you set a frame element there (the interior element will be ignored) and add corresponding objects to your image, focus borders will be drawn for radiobuttons, checkboxes, pushbuttons and any other widget that explicitly wants them. Note that the focus frame objects should have no state in their names. And please first update Kvantum because I've made some modifications.

**Comment by sixsixfive** [comment]
>It does! It's under the Focus section.

ah no i mean those darker ones around the colors

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/7007815/2861ed4c-dc8d-11e4-9f12-7a5a3b35bc96.png)

**Comment by tsujan** [comment]
That's GenericFrame and I've intentionally excluded non-scrolling widgets from having GenericFrame because most of them would look ugly. I'll see if I can make an exception for those "color" widgets.

**Comment by tsujan** [comment]
Made the exception for Qt5 color dialog.
Pencil2d's color widget is different and uses "mid.light.color" for the border.

**Comment by sixsixfive** [comment]
nice as always
