### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by cova-fe** [tsujan/Kvantum#375]
I'm using kvantum 0.11 on gentoo  / plasma 5.15.4 / QT 5.12.2 and I have a question regarding the customization of themes. So far I've been able to modify colors for all the parts that I'd wanted to, but I'm not able to change the windows toolbar background. I'm pretty sure I'm missing something obvious, but I searched all the menus I available to no avail. (kde settings, kvantum settings, etc..). Any suggestion? 
many thanks.

**Comment by tsujan** [comment]
> but I searched all the menus I available to no avail. (kde settings, kvantum settings, etc..).

I don't know how you changed other colors but Kvantum has 2 kinds of colors: basic colors, that are inside the kvconfig file of the Kvantum theme; and SVG colors and/or gradients, that are inside the SVG image of the theme.

As for toolbar, it depends on the theme. Some themes don't have an SVG element for toolbar and set its interior/frame to `false` in their kvconfig file, so that their toolbar is integrated with their window (like KvOxygen). Other themes may have toolbar elements  with colors/gradients (like KvAmbience); you need to find and edit them in their SVG files by using Inkscape.

Use the doc included in the source as a reference. When you change a background in the SVG and/or kvconfig file, you might also need to change the text color inside the kvconfig file; otherwise, you might see white on white or black on black. The details are explained in the doc (2 PDF files).

**Comment by cova-fe** [comment]
Thanks for the hint, will look at it.
