### ISSUE TITLE
cutted zoom slider in the statusbar

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#38]
![unbenannt](https://cloud.githubusercontent.com/assets/3780774/7005774/926c9564-dc7b-11e4-84a0-4ffbc50c7205.png)

For some reasons this thing is cutted, also i have tested this with all other qt5 styles:

oxygen --> the same as kvantum
fusion --> the buttions and icons are not cutted(they are scaled) but the slider is cutted, too
windows & GTK+ --> everything is scaled down so no issues here

**Comment by tsujan** [comment]
Is this about a specific app?

**Comment by sixsixfive** [comment]
it might be, i'm unsure snice i don't know any other qt5 app with such a zoom slider

**Comment by tsujan** [comment]
And what's its name? It might be interesting to investigate its code later.
Probably there's a mistake in height calculation.

**Comment by sixsixfive** [comment]
oops ;) http://otter-browser.org/

**Comment by tsujan** [comment]
I saw Otter-browser's source. Its statusbar height calculation is incorrect. It's limited to 13px instead of being dynamically based on the content size. Even with the GTK+ style, the height is incorrect but the slider ticks aren't drawn with that style so the handle doesn't appear to be cut.

I close this issue because it's a (minor) bug in the app in question.
