### ISSUE TITLE
Tooltip has a weird background if popup_blurring=true

### ISSUE THREAD

**Issue by ervasive** [tsujan/Kvantum#380]
Hi @tsujan first of all thank you for such a great project of yours.

I just started playing with the engine and I'm trying different things that I was able to figure out thanks to the Theme-Config and Theme-Making manuals, but one thing that I stumbled upon recently was the following.

If we make the tooltip graphic elements semitransparent and set `popup_blurring=true` option, then some weird background appears under it that I don't know how to get rid of. I'm not sure if it's an option that I was unable to figure out or a bug.

Here's the screenshot:

![Slice](https://user-images.githubusercontent.com/85254/56445623-dd951780-6306-11e9-9942-7a111eb9f8e8.jpg)

And I made a minimal example theme that you can find here: https://github.com/ervasive/kvantum-tooltip-blur-bg

Thank you.

**Comment by tsujan** [comment]
I'll investigate it tomorrow. Thanks for reporting!

**Comment by tsujan** [comment]
OK, I'm back.
This is indeed Kvantum's fault. Your theme doesn't give shadow to tooltips but Kvantum subtracts the shadow of its default theme from the total area and then applies the blur effect (the central area in your screenshot has a strong blur effect).

Since this special case didn't happen in other themes, I missed it. I'll fix it today. Will tell you when the commit is made.

However, please note that, *after the fix*, this will happen:

![blurred_tooltip](https://user-images.githubusercontent.com/981076/56456985-53da5e00-6389-11e9-9f71-814cbbab1d12.png)

See the upper right and left corners (that happens with lower corners too but isn't visible in this screenshot). The blur effect is always applied to a rectangle. There's no may to make it aware of extremely rounded corners. That's why you don't see windows with extremely rounded corners in KDE

So, a rule of thumb: Don't make the corners of shadowless tooltips/menus too rounded *if you want the blur effect with them* (otherwise, they'll be OK).

**Comment by ervasive** [comment]
That was quick :D

Regarding the rectangular blur area, I've noticed it before and was wondering about it, so thanks for the tip. Oh and I assume that shadow variants of tooltips/menus don't affect how the blurred rectangle is drawn? they just hide it a bit better with the shadow?

**Comment by tsujan** [comment]
> Oh and I assume that shadow variants of tooltips/menus don't affect how the blurred rectangle is drawn? they just hide it a bit better with the shadow?

Right. Most of the roundness is for the shadow and the shadow is excluded from blurring (by appropriate "-shadow-hint-" SVG elements). The roundness that remains for the real corner is usually too small to reveal a visual glitch.

If Kvantum wasn't SVG-based, roundness could be handled with the blur effect but, even then, it wouldn't be worth the CPU usage because a non-rectangular area should be approximated by many tiny rectangles (like double integration over an area in calculus).

**Comment by ervasive** [comment]
Got it. Thanks for clearing it up.

**Comment by tsujan** [comment]
You're welcome.

Fixed in https://github.com/tsujan/Kvantum/commit/da499e386dd4f534c4453f62dca2ee8d515fdc64

**Comment by ervasive** [comment]
Works great. :heart:

**Comment by tsujan** [comment]
Oh, I found a side effect of the last commit; should fix it too.

**Comment by tsujan** [comment]
Wasn't a side effect but a typo. Fixed now :)
