### ISSUE TITLE
Yaru theme: calibre toolbar text illegible

### ISSUE THREAD

**Issue by memeplex** [tsujan/Kvantum#397]
Running calibre under gnome with qt5ct and kvantum builtin yaru theme and `CALIBRE_USE_SYSTEM_THEME=1` I get this: 

![image](https://user-images.githubusercontent.com/2845433/59314866-96cff800-8c8d-11e9-9e4a-c2bd6b1dd2c0.png)

Versions:

- Calibre 3.39.1
- Kvantum 0.11.1
- Gnome 3.32.1
- Qt5ct: 0.37

**Comment by memeplex** [comment]
Btw I've seen the same effect with Materia kvantum theme, although not with Materia Light kvantum theme. I know you're not the developer of those themes but maybe that helps you debug the issue.

**Comment by tsujan** [comment]
You use a Kvantum theme with dark toolbar and without grouping toolbar buttons — like KvYaru or KvAmbiance?

That's definitely a problem in Calibre's code (it isn't related to Qt5ct). It doesn't show up with other styles because their toolbars aren't different from their windows. It doesn't show up with themes like KvGnome either:

![kvgnome](https://user-images.githubusercontent.com/981076/59315734-429a3780-8cd0-11e9-89c5-de9e35c63736.png)


I'll try to find a workaround but no promise. Thanks for reporting.

**Comment by memeplex** [comment]
The theme is KvYaru. The screenshot is for the default settings. When I unset the grouping option the text just become totally invisible. With KvAmbiance it's the same, except that ungrouping makes some parts of the toolbar dark in a very inconsistent way.

**Comment by tsujan** [comment]
I just downloaded and had a glance at Calibre's source. Apparently, Calibre never calls `drawControl()` with `CE_ToolBar` and that's the cause.

I can only think of one workaround; it will be effective if Calibre at least calls `drawPrimitive()` with `PE_PanelToolBar`; otherwise, no workaround will be possible.

Will tell you about the result whenever I find time to test.

**Comment by memeplex** [comment]
Calibre developers are rather reluctant to theming (that's the reason you have to explicitly enable theming using an env var). I think the only alternative to giving up here is some kind of workaround.

**Comment by tsujan** [comment]
The above-mentioned workaround had no effect but I found a very simple workaround. It requires Qt 5.12 though (it'll come to your distro sooner or later if it isn't there yet). This screenshot is taken with it and with KvYaru:

![kvyaru](https://user-images.githubusercontent.com/981076/59316768-5300e100-8cd5-11e9-8b0f-830f38dc08c9.png)

I should make sure it doesn't have any side-effect before adding a commit -- we don't want to ruin everything just for Calibre ;) But I can't think of any side-effect, so I'll add a commit tomorrow.

Thanks again for the report!

**Comment by memeplex** [comment]
Great, as always you're the fastest developer alive.

**Comment by tsujan** [comment]
I found yet another problem with calibre!!

If the "Layout" button (on the right side of the status bar) is clicked and if compositing is enabled in the theme, the popup will be totally transparent!

It seems that the developers of calibre don't know how to work with QStyle. I'll try to find another workaround for it too.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/b7cc691319ff2b7f45156c156017bf89c55141f8

The workaround is general, although only Calibre uses it. It works with Qt ≥ 5.12, by using a handy attribute that was added to Qt 5.12.0.

The transparent menu of the "Layout" button can be seen with Breeze and QtCurve too and is caused by a very bad hard-coded style. No workaround is possible for it but it's tolerable, IMO.
