### ISSUE TITLE
Automatic GTK conversion?

### ISSUE THREAD

**Issue by Izaic** [tsujan/Kvantum#410]
Would it be possible to add automatic GTK conversion to kvantum? Perhaps even just something that would just match the colors and let you select an existing kvantum theme to base the widgets off of, so that the person can then take that and tweak it?

**Comment by tsujan** [comment]
No, it isn't possible :)

Both GTK+ and Kvantum themes are complex, making them requires patience and practice, and both are flexible. But they have almost nothing else in common because (1) Qt and GTK+ are very different from each other and (2) Kvantum has its own logic to make SVG styling as flexible as possible.
