### ISSUE TITLE
reaching kvantum-manager from systemsettings

### ISSUE THREAD

**Issue by notmart** [tsujan/Kvantum#411]
Plasma's Systemsettings has a module that can be used to configure what widget theme is used.
for some styles that support it, such as breeze and oxygen, there is a configure... button that gets enabled and is possible to klaunch the settings from there.
this needs the settings app tp be built in two ways: as an executable to be directly launched (like kvantum nanager is now) and as a plugin (same sources, just sans-main.cpp). This approach is needed to have all in-process so it's possible to have the config window modal to the systemsettings window (and know when to enable apply and what not).
kvantum manager could probably be provided as that as well with very little change.
As a reference the code to do that in Breeze is: https://cgit.kde.org/breeze.git/tree/kstyle/config

**Comment by tsujan** [comment]
Thanks but Kvantum is independent of KDE and will remain so -- although it's tuned to KDE as far as there's no tier-n dependency, for n > 1.

**Comment by notmart** [comment]
hmm, right.
what about having an extra key in the Q_PLUGIN_METADATA which tells that it wants to use the kvantum-manager binary for configuration?
This shouldn't add dependencies and we could check that on the style kcm side and use kvantummanager as is when the configure button is clicked

**Comment by tsujan** [comment]
If you could do it (1) in a frugal way, (2) without any extra dependency and (3) without any problem in other DE's, please make a PR; I'd really appreciate it.

The tier-1 dependency `KWindowSystem` is the most I want for Kvantum because it extends Qt in such a way that there's no need to specific codes for X11 and/or Wayland, supports nice effects and, most importantly, doesn't depend on KDE.
