### ISSUE TITLE
konqueror sidebar buttons

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#42]
![unbenannt](https://cloud.githubusercontent.com/assets/3780774/7107110/b4ce18de-e159-11e4-91d6-6309b9a4b93b.png)

the button doesnt use the pressed button image there is also a weird stripe if the config button is enabled

**Comment by tsujan** [comment]
There isn't any bug here.
Those vertical buttons use a mixture of methods related to push and tool buttons to draw themselves. Hence their different appearance in Kvantum, which distinguishes between push and tool buttons and also between various states. In simple words, that appearance is intentional.
The stripe you mentioned is hard-coded. You could see it with Oxygen too.

**Comment by tsujan** [comment]
Today, your report made me rethink the situation and I remembered that the exception I made for such buttons was for fixing bug #28. Now I added another condition (under PE_PanelButtonTool) so that those vertical buttons aren't excepted anymore. I just hope the change won't have any by-product.

**Comment by sixsixfive** [comment]
yepp this works, could't found any issues yet
