### ISSUE TITLE
Styling treeWidget, mdiArea, subWindow, tableWidget

### ISSUE THREAD

**Issue by Davide-sd** [tsujan/Kvantum#428]
I've read the two pdf documents Theme-Making and Theme-Config, I've also look at several themes and didn't find an answer...

How do I style treeWidget, mdiArea, subWindow, tableWidget? I would really love to change their background color, but I'm not able to find the correct id to use. For instance, if I want to style a button I use button-normal, button-pressed, ... What are the ids to use with these "uncommon" widgets? Is there a list of ids and related widget I can use for reference?

**Comment by tsujan** [comment]
Tree/table/... widgets are item views and controlled by the`ItemView` section. Their backgrounds are the `base.color` and `alt.base.color` (consult the doc) and `ItemView` has options for states of their items  (see a few `kvconfig` files included in Kvantum).

For buttons, the doc is clear too: `PanelButtonCommand` (usual buttons), `PanelButtonTool` (tool buttons), `ToolbarButton` (tool buttons on stylable toolbars), ...

Subwindow background is set to `dark.color` by Qt in its source.

> ... with these "uncommon" widgets?

No widget is uncommon. A complex widget may be made up of common widgets. Kvantum covers every widgets `QStyle` provides (and a little more).

**Comment by tsujan** [comment]
Also, see the explanation of `GenericFrame` (for item views). There may be other things too but all of them are in the doc.

The doc can't explain everything about Qt, of course. Even Qt's doc doesn't do so. Developers should see the source files to know every detail. However, that doesn't have anything to do with theme making: theme makers don't need to be coders.

Last but not least, the doc is a *reference* (as Qt's doc is). I don't think anyone could read it from start to end ;)

**Comment by Davide-sd** [comment]
Thank you very much! You shed some light with the hint about `base.color` and `alt.base.color`. The doc says that if `base.color` is translucent, `alt.base.color` will be considered as solid: would it be possible to force translucency also on `alt.base.color`? I've played with a few themes so far, but the effect of mixed solid and transparent colors over list item views (Dolphin for instance) is just not good at all...

**Comment by tsujan** [comment]
> would it be possible to force translucency also on alt.base.color? 

Actually, it was so before but I encountered some good apps with bad style codes, so that a translucent `alt.base.color` made them messy. Sadly, this wasn't the first time that I had to make a bitter compromise because some good coders write very bad style codes. The problem has never been in Qt itself. You might guess how patient I should have been... ;)

**Comment by tsujan** [comment]
You could also guess that the developers of styles like Breeze never encounter such problems: minimal styles only make use of a tiny part of what `QStyle` provides.

**Comment by Davide-sd** [comment]
The more I dig into theme making, the more I comprehend how complex must have been to develop Kvantum :D

I'm looking at the code, specifically `styles/polishing.cpp` line 1086 where you make `alt.base.color` opaque. I'm also looking at the Kvantum page `Configure Active Theme -> Compositing & General Look` where I see the line edit option `Opaque apps` (btw, at the moment I'm using/modifying Akava-kv theme). Would it be possible to add something similar (maybe we can call it `Force opaque alt.base.color` where we can add the name of the "troubling" apps (like Krusader) allowing all the others to use translucent `alt.base.color`?

**Comment by tsujan** [comment]
> Would it be possible to add something similar....

Yes, it's possible -- I'd thought about it -- but it would make things more complex unnecessarily. Many users aren't as knowledgeable as you are and I don't want to frighten them with "weird" settings.

> ... the "troubling" apps (like Krusader) ...

Yes, Krusader was one of them :) Simple fixes to the codes of such apps could solve their problems but I can't report bugs to all of them. I did report style problems once in a while but got tired of it. It's a shame that even an app like VLC contains ridiculously incorrect styling codes. "Don't their developers know they're making a *GUI* app?", I've asked myself many times.

**Comment by Davide-sd** [comment]
> Yes, it's possible -- I'd thought about it -- but it would make things more complex unnecessarily. Many users aren't as knowledgeable as you are and I don't want to frighten them with "weird" settings.

I don't think it would scare people. To be honest, I only discovered the `Opaque apps` option only when I was looking to obtain full transparency. Anyway, I might give it a try at coding it in the next weeks, see what I can achieve...

Back to the styling questions: please, look at the attached screenshot.

1. The magenta color is controlled by the option `GeneralColors -> window.color`. As you can see, it is applied to 4 different things (the floating toolbar, the mdi window, the arrows in the tabs, and the disabled icons in the tabs and pages). Would it be possible to "uncouple" them? Maybe it is already possible but I don't know the proper name to use in the config/svg?

2. `Box Frame`, `Panel Frame`, `Stack Widget`: here I used the following colors:  
```
light.color=#ff0000
mid.light.color=#00ff00
dark.color=#0000ff
mid.color=#ffff00
```
without relying on these 4 colors, would it be possible to style the panels with config/svg?

3. The cell border yellow lines in the data table, can I control them in a different way rather than using `mid.color`?

![Screenshot_20190918_170623](https://user-images.githubusercontent.com/9921777/65160877-de0d1800-da36-11e9-8c3d-7ce1a625e845.png)

**Comment by tsujan** [comment]
> I don't think it would scare people.

OK, I'll think about it again. I might find a way to make it less weird.

> Would it be possible to "uncouple" them?

I'm afraid the answer is "no" because that's what Qt does in its code. It uses some colors when drawing some widgets. That's why Kvantum's kvconfig file needs some background colors, although Kvantum uses SVG elements as far as possible.

> without relying on these 4 colors, would it be possible to style the panels with config/svg?

It may be possible but I let them be drawn by Qt because of probable problems. I was happy to draw important frames like that of group-boxes or item views with SVG elements.

> can I control them in a different way rather than using mid.color?

The same as above: I left them to Qt. There will be some "dangers" if Qt is interrupted. You could see it this way: Kvantum is neither too cautious nor too brave while painting widgets ;) I've found a balance after years.

BTW, please note that it's better NOT to give arbitrary values to light, mid and dark colors. "light" should be the lightest, "dark" the darkest and "mid" somewhere in between them. Other elements of the theme determine what's dark and what's light. The reason is that Qt uses them to draw "bevels", although they're used in other places too (as you've already seen, e.g. in the case of cell borders).

That being said, theme makers are free to experiment with any color, IMO. `kvantumpreview` contains enough widgets for seeing the result.

**Comment by tsujan** [comment]
OK, I removed the restriction from `alt.base.color` in the latest git Kvantum: https://github.com/tsujan/Kvantum/commit/ee999a3a01dacaa09ea9bb37a6a40269ed0a239d

Krusader is tolerable. I don't know if that's because of a safeguard that I added months ago or its developer has done something (not likely). All apps seem happy, especially Dolphin.

I changed `KvCurvesLight1` so that its `alt.base.color` is a very translucent black (#0000000a):

![alt_base](https://user-images.githubusercontent.com/981076/65179561-42000280-da70-11e9-92de-989bdc933174.png)

I'll test more apps with it. If an app ignores the translucency, I'll revert to the previous commit or do something else. (Please tell me if you found an app with a very bad behavior.)

Thanks for the discussion!

**Comment by Davide-sd** [comment]
> BTW, please note that it's better NOT to give arbitrary values to light, mid and dark colors. "light" should be the lightest, "dark" the darkest and "mid" somewhere in between them. Other elements of the theme determine what's dark and what's light. The reason is that Qt uses them to draw "bevels", although they're used in other places too (as you've already seen, e.g. in the case of cell borders).

Thanks for the detailed explanation! I'll experiment a bit with different colors keeping in mind your suggestions! :+1: 

> OK, I removed the restriction from `alt.base.color` in the latest git Kvantum: [ee999a3](https://github.com/tsujan/Kvantum/commit/ee999a3a01dacaa09ea9bb37a6a40269ed0a239d)
> 
> I'll test more apps with it. If an app ignores the translucency, I'll revert to the previous commit or do something else. (Please tell me if you found an app with a very bad behavior.)
> 
> Thanks for the discussion!

Amazing! Thanks for your fast change!!! I just compiled and installed it. Dolphin in detailed view with translucent `alt.base.color` looks incredible :) There appear to be a little glitch on the header where I used a translucent color, but I'm quite sure it's Dolphin fault because qBitTorrent doesn't present the issue! I'll look into it in the next few days.

I'm also going to need a few more days to test different applications and look for unexpected behaviors. Again, thank you very much for this commit. If you find odd behaviors feel free to revert the commit. In the meantime I'll keep playing and I'll report my findings :D

**Comment by tsujan** [comment]
> There appear to be a little glitch on the header where I used a translucent color

I don't see it here:

![dolphin](https://user-images.githubusercontent.com/981076/65186686-644d4c80-da7f-11e9-99e2-52da29d10131.png)

If you find the time, please explain it to me with a screenshot. Although Dolphin's header has a small problem, I added a workaround for it years ago. So, I'm curious to know about the glitch you see.

> I'm also going to need a few more days to test different applications and look for unexpected behaviors. 

I'd really appreciate that.

> If you find odd behaviors feel free to revert the commit.

Or I may add a workaround. It's too good to be reversed ;)
