### ISSUE TITLE
padding in list views

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#44]
![unbenannt](https://cloud.githubusercontent.com/assets/3780774/7189049/5e49dba8-e47c-11e4-874a-524db813f4ba.png)

is this an issue in my theme or a general issue?

**Comment by tsujan** [comment]
Which issue do you mean specifically?

**Comment by sixsixfive** [comment]
i mean that there is no padding/free space between the items(eg the two plus icons)

**Comment by tsujan** [comment]
This screenshot shows the same dialog, with both your theme and Oxygen. No difference in paddings:

![konqueror](https://cloud.githubusercontent.com/assets/981076/7189665/ac1bfa50-e495-11e4-96bf-b30e8f660111.png)

So, it's about hard-coded paddings (or lack of them).

**Comment by sixsixfive** [comment]
hm strage if i use the gtk or the clearlooks theme i have paddings...

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/7189801/bde39324-e481-11e4-8b99-d666f8e119ca.png)

**Comment by sixsixfive** [comment]
edit ahh ok then --> closed;)

**Comment by tsujan** [comment]
As  you closed the issue, I think you knew why GTK+ and Cleanlooks themes showed a padding. But just for reference: in fact there's no padding; they use bigger icons, which have a bit of padding around them.

**Comment by tsujan** [comment]
You may have already known this too but again, for reference: This is the same dialog with Kvantum's default them:

![1971](https://cloud.githubusercontent.com/assets/981076/7192873/1d7610be-e4af-11e4-9614-7e922253532e.png)

Now there is a padding because the default theme sets a frame with a thickness of 2px under ItemView, while Glare sets none.
