### ISSUE TITLE
White line on Falkon with KvGnome

### ISSUE THREAD

**Issue by Manueljlin** [tsujan/Kvantum#441]
In Falkon there's a white line when tabs are set to the top, and it only seems to happen in KvGnome. When the tabs are set to the bottom, it doesn't have that issue.

![Screenshot_20191014_091353](https://user-images.githubusercontent.com/11275573/66736430-6d0c2500-ee69-11e9-9ee1-1509cbe8e0ec.png)

**Comment by tsujan** [comment]
It isn't white but the window color (#f6f5f4). It's caused by a small miscalculation of tab-bar's height in Falkon's code and wouldn't happen if Falkon got the height from the widget style, like in this GUI:

![tabs](https://user-images.githubusercontent.com/981076/66738337-17407880-ee7b-11e9-99f4-01b4fe58c7ed.png)

It can't be worked around by Kvantum but thanks for your attention!

**Comment by Manueljlin** [comment]
Thank you, I'll try to report it to them then

**Comment by tsujan** [comment]
You're welcome.

I don't think they change the code for a specific Kvantum theme. I don't see it as a bug either; the developer(s) may have chosen this layout for whatever reason, although I can't guess it.

**Comment by tsujan** [comment]
Please also note that Falkon tries to enforce left-aligned tabs instead of consulting the widget style (tabs are centered in KvGnome). I mean, the layout has more than one problem -- although its problems are minor and the app is a really good browser.
