### ISSUE TITLE
Possibility to theme QtWayland titlebars?

### ISSUE THREAD

**Issue by n3rdopolis** [tsujan/Kvantum#442]
Hi

Is there any possibility for a Kvantum QtWayland titlebar plugin?
I am not sure how QtWayland titlebar themes work. I always wondered if the same decorations that are used for MDI windows could be used for it...

Thanks

**Comment by tsujan** [comment]
I read somewhere that Qt might have "client-side decoration" at some point. If that happens and if it can be controlled by `QStyle` (which a natural choice, in my opinion), I'll include it in Kvantum. But I don't think a usable and stable Qt CSD will be created soon. Until then, window decoration isn't related to widget style.

**Comment by teohhanhui** [comment]
Worth keeping an eye on https://bugreports.qt.io/browse/QTBUG-63969

**Comment by tsujan** [comment]
A real CSD should get its background, frame, buttons, layout and sizes from new parameters in `QStyle`. An ugly flat bar with the window background and hard-coded buttons can be anything but a real CSD. Also, a configurable shadow is needed (as in GTK); shadowless windows might be acceptable in 1990s -- or, maybe, with mobile-like Qt Quick apps of 2020s.

That's why I don't think it'll happen soon, *if it happens at all*.

**Comment by tsujan** [comment]
That being said, it's good to remind Qt devs of what is done by macOS. I'm not a fan of CSDs but if something similar to macOS becomes possible with QtWayland, who could dislike it?
