### ISSUE TITLE
Feature request: Update yaru theme

### ISSUE THREAD

**Issue by jbouter** [tsujan/Kvantum#455]
I would like to see the yaru theme updated to better reflect the overhaul it has gotten in the Ubuntu 19.10 release, effectively splitting it into:

* "Yaru", which is a light theme with a dark titlebar
* "Yaru Light", which is light overall, much like Gnome's default Adwaita
* "Yaru Dark", which is a dark them variation for Yaru.

**Comment by tsujan** [comment]
> "Yaru", which is a light theme with a dark titlebar

I only support that. Has it changed?

**Comment by jbouter** [comment]
[It has](https://www.omgubuntu.co.uk/2019/08/improved-yaru-theme-ubuntu-19-10-eoan), and there's a [light theme](https://www.omgubuntu.co.uk/2019/09/yaru-light-theme-not-default-just-option) now too.

**Comment by tsujan** [comment]
I'll take a look at it as soon as I find the time. Thanks!

Being very busy with several projects — Kvantum included — I can't give more time to Yaru. I'll only update the current theme.

People know how to make good Kvantum themes. I'm sure someone will make more Yaru themes if they're really needed.

**Comment by jbouter** [comment]
I entirely understand. Thanks so much for the effort you are putting in.

On an entirely unrelated note: why is there a "Kvantum" directory inside the repository, rather than having it one directory up (and the root being the repository itself)?

**Comment by tsujan** [comment]
>  why is there a "Kvantum" directory inside the repository, rather than 

See https://github.com/tsujan/Kvantum/issues/230

I'm updating KvYaru; will close this page only when it's ready -- it may take some time.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/66bcf2eab472ee2f0363b6efd56321cbd1568e0b

All user customizations should be removed before using the new theme. The whole Kvantum should be upgraded.

Since this theme is for Gnome/GTK users, I removed the dark toolbar+menubar. They didn't integrate well with the GTK title-bar. Moreover, GTK symbolic icons don't change color with Qt apps, so that toolbar icons might not be visible with a dark toolbar.

Also, Qt has 2 tab modes. The doc mode is like Yaru's tabs but the usual mode doesn't exist in GTK; so, I drew usual tabs as grouped buttons.

Also, I reduced layout margin/spacing a little; GTK wastes too much space.

Screenshot of a Qt app with the new KvYaru:

![KvYaru](https://user-images.githubusercontent.com/981076/68698311-e9dc0d00-0595-11ea-883e-2d1968879664.png)

Please tell me if there is any issue.

**Comment by jbouter** [comment]
Thanks for your hard work! :-)

**Comment by tsujan** [comment]
You're very welcome.
