### ISSUE TITLE
Font rendering issue on Kvantum.

### ISSUE THREAD

**Issue by Kodehawa** [tsujan/Kvantum#469]
Font rendering is _extremely_ wrong when the "Opaque Text" option (in hacks) is **not** set. This is against the very latest qt (5.14) on Arch with all the latest updates and kvantum-qt5-git to be sure am running the latest version.
It looks like it tries to render them with a transparent background. As-in, they show what's behind the window.

[I posted about it on /r/archlinux](https://www.reddit.com/r/archlinux/comments/eetbbo/some_fonts_are_rendering_improperly_on_plasma/) and [another person was able to confirm it](https://www.reddit.com/r/archlinux/comments/eetbbo/some_fonts_are_rendering_improperly_on_plasma/fby1ok7/)

The issue goes away if you disable font hinting or force opaque text on the Hacks section. A quick way to test this is to have a background with a lot of colors on the background and use the KvArcDark theme, then move the window around the background.

![image](https://user-images.githubusercontent.com/20606963/71426978-01c4a780-2691-11ea-90d5-889f0a7b3546.png)

**Comment by tsujan** [comment]
Kvantum does NOT render fonts; Qt does.

Yes, your screenshot shows a serious problem in font rendering of your system -- it can have various causes: an incomplete upgrade, a Qt bug, a bug in the DE you use... -- but Kvantum doesn't do anything with fonts.

Actually, the option "Opaque (text) colors" was added as a workaround. Its tooltip explicitly says, "... as a workaround for bugs in applications." I added it a long time ago because exactly the same bug appeared somewhere in Plasma or Qt. Fortunately, it was fixed soon.

Why doesn't that happen with Breeze/Fusion? Breeze and other styles don't use translucency with text colors. As a matter of fact, the concept of "translucency" is alien to them.

On reddit, when a person replies to your question with a sentence like "seems like Kvantum is a bit screwed," you could be sure that he/she knows nothing about the topic.

**Comment by tsujan** [comment]
From https://www.reddit.com/r/archlinux/comments/eetbbo/some_fonts_are_rendering_improperly_on_plasma/, and in spite of uninformed comments there, it can be concluded that you've encountered a new Plasma bug.

**Comment by tsujan** [comment]
OK, Qt 5.14 came here an hour ago. This is a serious and ridiculous Qt regression. I might make exceptions for the buggy Qt 5.14 in the code.

**Comment by tsujan** [comment]
I added an acceptable workaround to the latest git Kvantum (https://github.com/tsujan/Kvantum/commit/f27c8fc4c3293662c6913b1ec2c8057112e1e160).

I also reported the bug: https://bugreports.qt.io/browse/QTBUG-80981

But the bug was so intolerable that the workaround was needed. Moreover, who knows when Qt devs will fix it?

If Qt's quality continue decreasing as fast as this, I'll prefer gardening to programming.

**Comment by trmdi** [comment]
Just a guess. It seems that they don't really care about the translucency, like blur and transculency are used very limitedly in Plasma.

**Comment by tsujan** [comment]
@trmdi 
No. Their code reviews have become very poor -- they merge buggy codes so easily. Version after version, I see new bugs/regressions. Half of the time I put into Kvantum is spent to add workarounds for this or that mess. And Kvantum isn't alone.

I've asked this question many times in my mind: "Do Qt devs use Qt at all?" If the answer is negative, Qt will have a dark future and conversely, if Qt gets worse, I feel that the answer may be really negative.

Text translucency is used by Qt itself; for example, in placeholders (which I used to explain the problem in https://bugreports.qt.io/browse/QTBUG-80981). Now, placeholders have either black texts or completely transparent texts and it makes no difference which widget style is used -- while they should have translucent texts, like int Qt < 5.14.0.

My workaround is good enough but I'm trying to make it still better. Damn! A waste of time....

**Comment by Kodehawa** [comment]
"I'd prefer gardening to programming" mood.

Also thanks for the workaround!

**Comment by tsujan** [comment]
You're welcome. If you have the latest git, the workaround is at its best state.

As for gardening, no one could ruin your work -- except for your kittens ;)

**Comment by trmdi** [comment]
> https://bugreports.qt.io/browse/QTBUG-80981

They marked it as "Important". Very nice. :)

**Comment by tsujan** [comment]
> They marked it as "Important". Very nice. :)

Yes :) I got an email notification.

But, with the included workaround, users will see no difference ;)

**Comment by tsujan** [comment]
They fixed the bug in Qt 5.14.1. But I'll keep the workaround because it's exactly like a real fix and who knows what will happen later? (The problems has already happened twice).
