### ISSUE TITLE
Add screenshots of new themes into Readme

### ISSUE THREAD

**Issue by trmdi** [tsujan/Kvantum#470]
Just want to share my thought.
When I first looked at Kvantum readme page, I just thought it looks ugly and outdated (sorry to say this), I would never use it. But the other themes like KvMojave looks quite nice. Personally I found the reason for me to use Kvantum is because of that theme.
So I suggest you to do that.

**Comment by tsujan** [comment]
> I just thought it looks ugly and outdated (sorry to say this)

You don't need to be sorry at all. There is a myriad of different tastes in the world. Also, not so rarely, something that looks beautiful/ugly to one and the same person might look conversely to him/her later — that has really happened to me.

I don't like all of my Kvantum themes either because I made some of them only for good users that liked them (KvAdapata and KvArc come to mind).

I'll add Mojave screenshots to the collection later. Some screenshots need to be updated too.

**Comment by tsujan** [comment]
Done.
