### ISSUE TITLE
Ad a coloursetting option?

### ISSUE THREAD

**Issue by CavaleriOmar** [tsujan/Kvantum#472]
Some themes are beautiful, but sometimes it would be nice to be able to adjust the color palette, as is done with the standard color theme under the kde settings.
I think this would make it easier to produce themes forks and adapt them to (few) cases where contrast problems are encountered.

**Comment by tsujan** [comment]
Kvantum is much more complex than that. See https://github.com/tsujan/Kvantum/issues/265, https://github.com/tsujan/Kvantum/issues/183 and https://github.com/tsujan/Kvantum/issues/400

> and adapt them to (few) cases where contrast problems are encountered.

Lack of contrast is either a theme problem or a styling bug in the app. In the first case, the problem should be fixed in the theme. In the second case, it should be reported to the app's developer(s).
