### ISSUE TITLE
Change size of combo box/ right click menu

### ISSUE THREAD

**Issue by Dashon1** [tsujan/Kvantum#479]
I was jus t wondering if there was anyway to change the sizes of combo boxes as well as the right click menu when using kvantum. My problem is that the default size of a combo box in breeze is much smaller than that of of kvantum. The same thing occurs in right click menus. I hope that these screenshots will help portray the problem. 
Breeze combo boxes have this width:
![Screenshot_20200206_033759](https://user-images.githubusercontent.com/40647198/73924528-3f247380-4892-11ea-9ac7-1c376dbc035c.png)

kvantum on all the themes I have tried has a width like this: 
![Screenshot_20200206_033739](https://user-images.githubusercontent.com/40647198/73924635-6d09b800-4892-11ea-9f7e-7be1c003ce94.png)

In some applications I end up with extremely long como boxes:
![Screenshot_20200206_033845](https://user-images.githubusercontent.com/40647198/73924718-8e6aa400-4892-11ea-86aa-20c6c62e9376.png)

The size of these combo boxes don't reflect the content inside of them at all. They just seem to be getting longer at a much larger rate than in breeze. I couldn't really capture this part in a screenshot using kde's screenshot program, but in the last screenshot in particular. The combo box is extremely large but the menu options are all 4 to 5 letter words. This is what I meant by the size not reflecting the content. Right click menus aren't as bad and tend to show more content than regular breeze right click menus did but it would be nice if we could change the rate of growth on both of these items.

I may have just missed it or didn't understand it in the documentation but any help would be appreciated.

**Comment by tsujan** [comment]
1. The width of a combo box is determined by its layout and size policy (stretched or fixed). It's the layout/size policy that stretches the combos, not Kvantum.

  2. In *forms* (= a kind of layout), Breeze forces a right-aligned position on every widget under the left column and a left-aligned position on every widget under the right column. Kvantum doesn't (because I dislike that untidy setting); Kvantum's behavior is like that of Fusion (check Fusion and you'll see). Your first screenshot is System Settings -> Application Style, which is a form. (Read 3 below).

  3. Anyhow, no space is wasted. Breeze may show an vast empty space outside the combo instead, as is the case in Application Style.

**Comment by Dashon1** [comment]
@tsujan I understand that no space is wasted and that it is using a similar size policy to that of Fusion, but is there anyway for me to change that size policy?

**Comment by tsujan** [comment]
No, there isn't.

I might add an option for center-aligned forms to Kvantum Manager after removing a useless option from it. Will tell you when it's done (I'm a little busy now).

**Comment by Dashon1** [comment]
Thanks and I understand no rush or anything. Have a good day.

**Comment by tsujan** [comment]
Done.

Please upgrade to the latest git. Then, if you check this:

![KM](https://user-images.githubusercontent.com/981076/73985446-6e99b580-4950-11ea-84b5-475d11e06f79.png)

You'll have this:

![app_style](https://user-images.githubusercontent.com/981076/73985458-778a8700-4950-11ea-8e72-4142e1f19bae.png)

Although I don't like the layout, it's good as an option, especially because it replaces a useless option. Thanks for the suggestion!

**Comment by Dashon1** [comment]
@tsujan wow you work fast. I'll give it a try when I get home. Thanks a lot.

**Comment by tsujan** [comment]
You're welcome.

It was very easy to implement. I was just busy with another job; hence the delay.

**Comment by Dashon1** [comment]
@tsujan just got it compiled and it works perfectly thanks again.
