### ISSUE TITLE
Translation is not working ?

### ISSUE THREAD

**Issue by abcfy2** [tsujan/Kvantum#498]
I'm using Manjaro KDE, and my locate is zh_CN.UTF-8. I find kvantummanager and kvantumpreview not showing with `zh_Hans` translation. Why?

```bash
$ screenfetch 

 ██████████████████  ████████     fengyu@fengyu-ga970ads3
 ██████████████████  ████████     OS: Manjaro 19.0.2 Kyria
 ██████████████████  ████████     Kernel: x86_64 Linux 5.4.24-1-MANJARO
 ██████████████████  ████████     Uptime: 3h 44m
 ████████            ████████     Packages: 1206
 ████████  ████████  ████████     Shell: bash
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.67.0 / Plasma 5.18.3
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breeze [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Dark
 ████████  ████████  ████████     Disk: 422G / 1.5T (30%)
 ████████  ████████  ████████     CPU: AMD Phenom II X4 955 @ 4x 3.2GHz
 ████████  ████████  ████████     GPU: Radeon 550 Series (POLARIS12, DRM 3.35.0, 5.4.24-1-MANJARO, LLVM 9.0.1)
                                  RAM: 3225MiB / 7961MiB
```

```bash
$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=zh_CN.UTF-8
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL=
```

![深度截图_选择区域_20200317140232](https://user-images.githubusercontent.com/5327677/76826653-fe882480-6857-11ea-825f-b97e59ed236a.png)
![深度截图_选择区域_20200317140312](https://user-images.githubusercontent.com/5327677/76826678-0e076d80-6858-11ea-9587-0356063d6113.png)

**Comment by tsujan** [comment]
Yes, `kvantummanager_zh_Hans.ts` doesn't work. Other translations are OK though, as far as I tested.

I don't know if that's a translator's mistake or has another cause. Will investigate it.

**Comment by tsujan** [comment]
@abcfy2, I think the file name should have been `kvantummanager_zh_CN.ts`, not `kvantummanager_zh_Hans.ts`. I couldn't find `zh_Hans` anywhere else and it doesn't exist in "/etc/locale.gen" either. For example, in FeatherPad, I have `zh_CN` and `zh_TW` and both of them work.

Because I don't know Chinese, I need your opinion.

**Comment by abcfy2** [comment]
I'm not familiar with Qt, but I find `qbittorrent` is working: https://github.com/qbittorrent/qBittorrent/blob/master/src/lang/qbittorrent_zh.ts

But I try to rename `kvantummanager_zh_Hans.ts` to `kvantummanager_zh_Hans.ts` and change `language="zh_Hans"` to `language="zh_CN"`, still not working.

**Comment by tsujan** [comment]
> But I try to rename....

That's because I didn't explain it well ;) You should do the same inside the file too (language="zh_CN"). I did it here and `LANGUAGE=zh_CN kvantummanager` worked (the Chinese translation is incomplete though):

![zh](https://user-images.githubusercontent.com/981076/76849383-938c1d00-685a-11ea-8937-62759e3fa621.png)

You mentioned `qbittorrent`. It doesn't have `zh_Hans` either. In all projects I checked, it was either `zh_CN` or `zh` -- `zh_CN` is preferable.

I'll add a commit soon. Thanks for your report!

**Comment by abcfy2** [comment]
Thank you, it's working. It seems that I was not use `sudo make install` to install.

1. Rename `kvantummanager_zh_Hans.ts` --> `kvantummanager_zh_CN.ts`
1. Change `language="zh_Hans"` to `language="zh_CN"` from `kvantummanager_zh_CN.ts`
1. Rebuild and `make install` to install again.

It's working.

![深度截图_选择区域_20200317190337](https://user-images.githubusercontent.com/5327677/76850283-08268200-6882-11ea-956f-efb51c2aed12.png)

**Comment by tsujan** [comment]
Thank *you* for the confirmation!

**Comment by tsujan** [comment]
Done.

**Comment by abcfy2** [comment]
Thanks, and I try to install from the latest git version, it's working.

I will try to finish translating the simplified Chinese if I have enought time.

**Comment by tsujan** [comment]
Take your time. There's no haste.
