### ISSUE TITLE
Symbolic icons on inactive tabs in Dolphin receive wrong color

### ISSUE THREAD

**Issue by nortexoid** [tsujan/Kvantum#510]
The highlight.text.color seems to determine the color of symbolic icons on inactive tabs in Dolphin which can cause very poor contrast. I haven't widely tested, but this seems not to happen with other qt tabs (such as okular), so might be a bug in dolphin. I've attached a screenshot showing the issue, where I have a dark selection/highlight color and white highlight.text.color.
![Screenshot_20200326_092511](https://user-images.githubusercontent.com/969567/77625722-61f31000-6f44-11ea-9694-bae1ccd8e263.png)

**Comment by tsujan** [comment]
Yes, Dolphin has small issues with symbolic icons inside its inactive widgets but I don't think this problem is related to that.

I've made a mistake in `KvYaru`, for example: some of text colors under the Tab section of `KvYaru` have high contrast with `window,color`, so that their corresponding symbolic icons become white. Instead, I should have used *translucent colors* for pale texts.

I'll fix it soon and see if another theme needs a fix too. You could do the same thing in your theme.

Thanks for your report!

**Comment by nortexoid** [comment]
Thanks for the explanation. Unfortunately I don't understand enough to fix my theme (which is a mod of Yaru), since I'm just tinkering with a pre-existing theme I have (Yaru Aqua Light). Could you elaborate? If not, I'll simply have a look at what you've changed in KvYaru, or I suppose I could look at another theme that doesn't have this issue. Cheers!

**Comment by tsujan** [comment]
> Could you elaborate?

I'll fix `KvYaru` and explain the problem and its solution by referring to it.

**Comment by nortexoid** [comment]
By looking at KvGnome, I see what you mean and learned something about the hex code for transparent colors. My theme's fixed, thanks!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/Kvantum/commit/af6a3628984ee633d136b0334041ef55b36dd294

The explanation I'd promised:

As is mentioned in `Theme-Making.pdf` → `A Word about SVG Symbolic Icons`:

**If the text color of a widget in a certain state has a high contrast with `window.color`, the color of its symbolic SVG icons in that state will be `window.text.color`; otherwise, it will be `highlight.text.color`.**

Now, in `KvYaru`, `window.color` is "#f5f6f7" and, in the previous version of `KvYaru`, we had `text.normal.color=#8c898c` under `[Tab]`. These 2 colors do NOT have a high contrast with each other. So, the color of symbolic icons of normal (unselected) tabs was `highlight.text.color`, which is "#fcfcfc" (very light).

In the fix, I used "#3d3d3d" with translucency ("#3d3d3d91" -- "91" is for translucency). That color has a high contrast with `window.color` and so, the color of the SVG icon will be `window.text.color`, which is "#3D3D3D" (dark).

**Comment by nortexoid** [comment]
Thanks for the explanation and fix!

**Comment by tsujan** [comment]
Thank *you* for the report!
