### ISSUE TITLE
[wishlist] Allow DECIMALfont for indicators

### ISSUE THREAD

**Issue by andbgr** [tsujan/Kvantum#523]
I found in the documentation that some sizes can be made dependent on font size, like "2.5font". This would be really neat for indicators' sizes (arrows and such), as they usually have "glyph-like" properties anyway and can otherwise look too big or too small depending on font size.

**Comment by tsujan** [comment]
Sizes like "2.5font" are introduced to be used for spaces and the value of "frame expansion" because, with some themes, a small margin/spacing may not look good with a big font, or we may want to make button corners completely round with all font sizes, etc.

The problem of using "2.5font" with indicator sizes is that indicators are images and small images look sharp enough only with specific sizes. The theme maker needs to check that his/her indicator images are drawn appropriately, so that they look sharp with the fixed sizes he's chosen.

But thanks for caring and sharing your idea!
