### ISSUE TITLE
Weird issue with fonts on some buttons/menus.

### ISSUE THREAD

**Issue by Dashon1** [tsujan/Kvantum#528]
I know kvantum doesn't handle fonts, but I seem to be having a weird issue with some buttons/menus. The ones that are popups and buttons. I forget the name. I'm currently on openSuse Tumblweed with kde plasma 5.18.5 and I was hoping you could help me pinpoint the issue. Here is an example of what I'm talking about. 
![Screenshot_20200507_184831](https://user-images.githubusercontent.com/40647198/81356089-044ef900-9096-11ea-96ac-f2113b085f46.png)

If I switch the application style to breeze it displays normally, but when I'm using kvantum. That weird overlap issue happens. Any ideas?

**Comment by tsujan** [comment]
Since I've never seen such a scene, this can't be an "example" of anything but a unique case. The title-bar said "soundkonverter"; so I installed soundkonverter but couldn't reproduce the problem with themes belonging to Kvantum:

![soundkonverter](https://user-images.githubusercontent.com/981076/81363809-6d1b8d00-90f9-11ea-862c-b6a30655e115.png)

You'll need to be more specific if you want us to find the cause of your problem together.

**Comment by Dashon1** [comment]
Alright well extra details I can think of are that I am using the theme glassy found here: https://store.kde.org/p/1355990/ although I did change some colors. In addition to that the system font that I'm using is comfortaa set at size 13. It only seems to be occuring with buttons of the size you see above. In for example spectacle, kde's screenshot tool, the same type of button isn't as large and displays correctly.

**Comment by tsujan** [comment]
> Alright well extra details I can think of are that I am using the theme glassy found here...

That's the cause: "glassy".

While being a beautiful theme, "glassy" has translucent button backgrounds. You could tell its creator about the problem, giving the address of this page.

Actually, "glassy" has no problem. *The real problem is in those apps (bad GUI design)*; they don't show up with themes that are included in Kvantum because I intentionally use opaque backgrounds for buttons. However, we need to accept the fact that some well-known apps have GUI issues, which their authors will never fix. In this case, it's better to use opaque backgrounds for buttons to avoid problems of this kind.

I might add a warning about it to the doc.

**Comment by Dashon1** [comment]
Alright. Thanks for the advice.

**Comment by tsujan** [comment]
You're welcome. Thanks for reminding me of this issue in some apps.
