### ISSUE TITLE
Smaller Tab Scroll Indicator Sizes

### ISSUE THREAD

**Issue by varlesh** [tsujan/Kvantum#530]
Hi @tsujan 
On [Tab] section used `inherits=PanelButtonCommand` - it's mean arrows used from `PanelButtonCommand`.
Also set `indicator.element=tab`. But it's worked for only `tab-close-STATE`
If i'm add `tab-arrow-STATE`  - it's not applied (with removed inherits too)
It's possible added support customizable tab arrows? We can change arrows on Toolbar, Spinbox, Header and etc... But not on Tabs ((

**Comment by tsujan** [comment]
Hi @varlesh,

Happy to hear from you after a long time :)

I guess you mean tab scroll arrows; don't you? If so, they are actually tool-buttons and drawn as tool-buttons by Qt itself (see `[PanelButtonTool]`). Kvantum should respect that; otherwise, various kinds of problems would happen.

`indicator.element` under `[tab]` provides tab close button (when "-close" is added to its name) and tab tear indicator (when "-tear" is added to its name). See `Theme-Making.pdf` → `Indicators` → `Tab` (inside the table).

**Comment by varlesh** [comment]
Yes, tab scroll arrows. I'm use big close tab button (for more unification with GTK Theme) and arrows inherit size from close button
![image](https://user-images.githubusercontent.com/8083855/81524714-46608f00-9363-11ea-84c5-40eaf501a01a.png)

**Comment by varlesh** [comment]
I can't reduce arrow on area layer, because arrow used on another widgets.
![image](https://user-images.githubusercontent.com/8083855/81525063-85dbab00-9364-11ea-86c6-414f05c30209.png)

**Comment by varlesh** [comment]
It's limit customization close tab button, because arrows inherit size from close tab button.

**Comment by tsujan** [comment]
Yes, arrows get their size from tab's indicator. Actually, the *buttons* that contain them get their size from tab's indicator; otherwise, they would be ugly with some themes.

The calculations are pretty complex. One pixel bigger or smaller might have side effects. I'll re-read the code. If there is a safe possibility for changing their size, I'll tell you. If not, I'll explain why.

**Comment by varlesh** [comment]
Ok... It's not only my request, because mostly GTK Themes used big close tabs button.
For example Adwaita (default GNOME theme):
![image](https://user-images.githubusercontent.com/8083855/81525792-e66be780-9366-11ea-84bc-51e82359d279.png)

**Comment by tsujan** [comment]
It seems possible to use PanelButtonTool's indicator size for scroll arrows. I modified the code and gave absurd big sizes to KvMojaveMix's tabs to see what would happen. The result was acceptable:

![tab_scroll_buttons](https://user-images.githubusercontent.com/981076/81526666-7ad94880-936d-11ea-9c21-694c29285c94.png)

I should read Qt's source, consider frame expansion and do some tests with other themes to know if it's safe.

**Comment by varlesh** [comment]
glad to hear that)))

**Comment by tsujan** [comment]
After taking a look at Qt's source, I think it's safe. Done in https://github.com/tsujan/Kvantum/commit/f17e689f09d92c8d2887d50061ec2ba67053353b

Now, the size of tab scroll arrows is the minimum of PanelButtonTool's indicator size and 12. In this way, it doesn't depend on Tab's indicator size; it isn't too small for clicking either.

Like always, thank you very much for the discussion!

**Comment by varlesh** [comment]
very cool!!!! You are best :+1:
