### ISSUE TITLE
Support for sidebar only blur in Dolphin

### ISSUE THREAD

**Issue by meetdilip** [tsujan/Kvantum#538]
First of all, thanks for this great software. If it is possible, can we have _sidebar only_ blur in _Dolphin_ in KDE Plasma ? Otherwise, it is really hard to read the contents inside the Dolphin window. Thanks.

**Comment by tsujan** [comment]
What do you mean by blurred Dolphin side-bar? If you mean blurring translucent backgrounds, Kvantum already supports it and it isn't limited to Dolphin.

If you mean a translucent and blurred side-bar for Dolphin but an opaque background for Dolphin's view, that's already possible too: uncheck Kvantum Manager → Configure Active Theme → Hacks → Transparent Dolphin view.

**Comment by tsujan** [comment]
Some Kvantum themes (not those included in Kvantum itself) may have a very translucent "base color", so that unchecking  "Hacks → Transparent Dolphin view" won't make Dolphin's view opaque. If a translucent view isn't good for your eyes (which I understand), you could either remove their base color translucency in their `kvconfig` file (under `[GeneralColors]` → `base.color=`) or use another theme.

I close this but feel free to add comments if you have questions.
