### ISSUE TITLE
Set colours in kvantummanager

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/Kvantum#54]
To be able to set colours in kvantummanager (like in qt5ct) would be a great convenience if it wouldn't be a big trouble to implement for you.

If you do this, please also consider adding tooltips explaining some obscure colour settings such as Bright, Less Bright, Dark, Less Dark and maybe othes I'm not aware of or exclusive to kvantum.

Thanks so much for your brilliant utility and good work, especially as it's free of any KDE dependency!

**Comment by tsujan** [comment]
That's quite possible but there are three problems: (1) since Kvantum is SVG based, widget colors will be set by the SVG elements if those elements aren't invisible, and (2) even the general text colors (that can't be set in the SVG image) may be overridden by state-specific text colors of each widget section. Moreover and more importantly, (3) I've put only those settings in Kvantum Manager whose changes wouldn't damage the look of any theme, and color settings don't satisfy this condition.

That being said, I'll think more about it. And thanks for your suggestion!

**Comment by AcarBurak** [comment]
All right, thanks.

By the way, that tooltips thing is not very necessary really as one can look into qpalette reference.

Please feel free to close this if you like.

**Comment by tsujan** [comment]
I leave this issue open for a while; I haven't decided yet.
BTW, all colors are explained in the doc file "Theme-Config". I always update the Kvantum documentation if needed.
