### ISSUE TITLE
Not applying theme to all apps

### ISSUE THREAD

**Issue by Kreuger** [tsujan/Kvantum#545]
Hey guys. Just installed kvantum to use a dark theme. I have set it up in the LXQT Configuration Center. However, not all apps are using the theme ive chosen such as Synaptic and PCManFM-QT.

**Comment by tsujan** [comment]
The short answer: Restart the apps or, more easily and effectively, just log out and log in again.

Detailed answer:

If you choose Kvantum in LXQt Appearance Configuration, all Qt apps will see Kvantum because, as a DE, LXQt *enforces* them to do so. But if you change the Kvantum theme in Kvantum Manager, apps should be restarted to see it (as is mentioned in Kavntum Manager). That's because Kvantum doesn't, can't and shouldn't *enforce* apps to see a theme change in their run-times. pcmanfm-qt runs in the background to draw Desktop, so you need to stop and start Desktop in LXQt Session Settings after a theme change.

Please also note that:

 1. "Style" and "theme" are different concepts. Kvantum is a Qt widget *style* that supports various *themes*. The style change (from or to Kvantum) is controlled by the DE, while the theme change is managed by Kvantum Manager.

 2. Even in the case of changing the style to Kvantum -- whether in LXQt or in KDE -- the running apps may not see Kvantum correctly. Usually an app restart -- or a logout and login for all apps to restart -- is needed. With the latest git Kvantum (and the latest git LXQt), app restart isn't needed most of the time but may be required in some cases because of complications in Qt.

 3. Kvantum doesn't belong to LXQt 's project. I am the author of Kvantum and, by chance, I am also an LXQt developer. Kvantum is independent of all DEs. Some KDE users may think that it belongs to KDE because it can use KWin's blurring and contrast effects but it isn't a part of KDE either.

I close this but feel free to add comments if you have any question.

**Comment by tsujan** [comment]
BTW, Synaptic is a GTK app in Debian; isn't it? Here, we're talking about *Qt*, not GTK. Qt and GTK are completely different toolkits. The most well-known DEs that are made based on Qt are KDE and LXQt.

**Comment by Kreuger** [comment]
Thank you that answered everything. And youre right, I forgot that Synaptic is a GTK based app.
