### ISSUE TITLE
Modified kvconfig file not having any effect

### ISSUE THREAD

**Issue by xd003** [tsujan/Kvantum#553]
OS - Arch Linux
DE - Plasma kde 5.19.3
WM - Kwin
kvantum-qt5 0.16.0-1

I was originally using Sweet kvantam theme from here - https://github.com/EliverLara/Sweet/tree/nova/kde/kvantum
Everything was working as expected , but i wanted to some of the colors , so i modified the hex in the kvconfig file
https://www.diffchecker.com/tk7tm6Pc#right-3

After modifying the kvconfig file , i reinstalled the theme in same location overwriting the existing config and applied the same theme again but the colors are not getting changed

I also made sure that In configure active theme option , the kvconfig is pointing to my modified kvconfig
I don't really understand why is it not taking effect and still stuck to the old config
i even did a reboot but to no avail

**Comment by tsujan** [comment]
As is explained in `Theme-Making.pdf` → `Theme Installation Paths`,  if you have installed a theme both as root and as user, the latter will take priority.

To modify a few colors of a theme, you don't need to re-install it. Just follow the explanation at the top of `Kvantum Manager` → `Configure Active Theme`.

But if you want to make another theme with the same name (why?!) and install it as root, first remove the user installation in `Kvantum Manager` → `Change/Delete Theme`

**Comment by xd003** [comment]
@tsujan thanks for the quick reply ,although i never did a root installation of theme in first place
i had simply downloaded the svg and kvonfig file in Downloads folder and installed + applied it using kvantum manager

then i removed that local installation from kvantum  and edited the kvconfig file in Downloads folder and installed it again
i also read the theme installation path section in theme-making.pdf and checked the file with the highest priority has my modified kvconfig too

cat .config/Kvantum/Sweet/Sweet.kvconfig | grep window.color
window.color=#10151a

For some reason , it is still following the old kvconfig which i already deleted

**Comment by tsujan** [comment]
This is the "Sweet" theme modified as you did and installed as user over the original "Sweet" theme:

![sweet_modified](https://user-images.githubusercontent.com/981076/88453213-27f63400-ce7a-11ea-8bfb-26f49466bac6.png)

As can be seen in the screenshot, I've selected the text of an editable combo-box and the highlight color is what you've chosen.

As for the window color, Sweet uses an SVG element for "window", which overrides the window color set in its kvconfig file. You could either change the color of that SVG element or, more easily, just remove the block `[Window]` from you customized kvconfig file. If you do the latter, you'll see your color and could adjust the window translucency in Kvantum Manager in whatever way you like.

Please note that Kvantum is *SVG-based*. The colors under the `[GeneralColors]` section are needed but some of them may be overridden by colors/gradients of SVG elements if present.

Also note that the color of selected view items is also determined by the SVG elements whose IDs (names) start with `itemview` (use the search utility of Inkscape to find them).

Although I've closed the issue (because it wasn't an issue), you could ask here any question you may have about colors and SVG elements.
