### ISSUE TITLE
[QUESTION] Run a build without including all the themes.

### ISSUE THREAD

**Issue by cyclinggeorgian** [tsujan/Kvantum#558]
Hi, there are some themes that haven't been updated in a very long time and look out of place on the latest Plasma. I have tried, to my limited C++ abilities, to read the code and find a way to compile program without the themes. But unfortunately i wasn't able to find any build flags that would allow me to run build without themes.
So i guess my question is - did i miss it? (with is very probable) or there are no possibility to run a build without including all the themes?

**Comment by tsujan** [comment]
> and look out of place on the latest Plasma.

I'm afraid Kvantum doesn't have any relation to Plasma. It can make use of some KWin (≠ Plasma) properties if existing but it doesn't depend on KWin either. It may be used in GTK environments too.

Some themes were added because people wanted them. For example, I don't like `KvArc`, `KvAdapta` or `KvFlat` but I don't remove them either because their files can be used for making other themes.

> i wasn't able to find any build flags that would allow me to run build without themes.

No, there isn't a build flag and I have no plan to add one. The space they take is negligible. Just ignore the themes you don't like.

However, I'll remove all Openbox themes from Kvantum when Qt6 comes. The users that might still use Openbox could find them in older versions.
