### ISSUE TITLE
Kontact/Kmail crash when opening attachments with kvantum

### ISSUE THREAD

**Issue by feilee** [tsujan/Kvantum#559]
When using kvantum as an Application Style, Kmail/Kontact always crash when openning attachments. When using other Application Style it works fine.
Maybe an index related issue. When is selected another windows or desktop, Kmail change the current open email to the last selected email before changing the mail folder.

Originaly reported here -> https://bugs.kde.org/show_bug.cgi?id=425651

**Comment by abracwan** [comment]
Hi @tsujan. Sorry for bothering you with this bug. I am currently trying to reopen the old KDE bug report and trying to understnad the current bug. I am not familiar with KMail's code, but I think your suspicion is quite logical. I found that certain themes (KvMojave, KvGnomeDark, KvYaru) manifest this bug and the old one, whereas other themes (Arc, KvCyan) do not. I would like to find out if the latter themes indeed **do not** modify the color palette when focus is toggled. How can I check this for myself? I would like to do some testing to report to the KMail devs.

**Comment by tsujan** [comment]
> I found that certain themes (KvMojave, KvGnomeDark, KvYaru) manifest these bugs, whereas other themes (Arc, KvCyan) do not.

KvMojave, KvGnomeDark, KvYaru,.. have different colors for the active and inactive states of some widgets, while KvArc and KvCyan ignore the inactive state, like Breeze and Oxygen do.

> I would like to do some testing to report to the KMail devs.

There are already two detailed crash reports at https://bugs.kde.org/show_bug.cgi?id=425651 and https://bugs.kde.org/show_bug.cgi?id=425604 and there's no trace of Kvantum in any of them. I think that KDE developers have enough info to investigate the problem in their codes.

Please don't get me wrong. If the problem was caused by Kvantum, I'd be happy to see a backtrace that showed it and I'd act immediately. Whenever a KDE file is created in `/var/lib/systemd/coredump` — and it happens often — the first thing I do is searching for Kvantum in its backtrace. Fortunately, I find nothing. Understandably, the rest isn't my concern.

**Comment by abracwan** [comment]
Hi Tsujan. Thank you for your response. I'm pretty new to bug reporting and couldn't make heads or tails of the bugtrace. Hopefully the KDE devs will be able to. I guess I'll wait and see if they have time to attend to the bug 😅 -- then I'll find out how I can help them with testing, for example.

**Comment by tsujan** [comment]
> couldn't make heads or tails of the bugtrace

I'm not familiar with KMail code either but if an external program causes a crash, you could find it in the backtrace.

> you've really done a great job maintaining your complex project!

Thanks! Kvantum wouldn't be possible without users' reports and suggestions. Bug reports are the greatest asset of an open-source project and I really appreciate them.

**Comment by NickLion** [comment]
> BTW, https://bugs.kde.org/show_bug.cgi?id=405220

Hi, sorry to up this issue. I'm reporter of that bug and can confirm, I was reproducing it with breeze as well. I wasn't able to reproduce it neither with breeze nor kvantum later so I've closed that issue, though had feeling bug wasn't solved but went undercover. I could confirm that with some kvantum themes (like mentioned KvMojave, KvYaru) this bug manifests again, but I almost definitely sure it's not kvantum problem, just some minor difference leads to uncover this bug again.

Reasons:
1. Earlier a was able to reproduce this bug with other style engines like breeze.
2. When affected theme is applied you can notice that when kmail/kontact looses focus (just click outside of kmail) whole mail tree is reset. This kind of behaviour is **very** unlikely to be caused by style engine.
3. The bug itself consists of two parts (as I see): 1) when current mail in tree is changed or mail tree is reset opening attachment leads to crash; 2) in some cases when kmail looses focus it reset mail tree. While some kvantum themes trigger second part (not sure how and still thinking problem in kmail) first part isn't related to kvantum.

**Comment by abracwan** [comment]
Interesting! Even though you closed your original issue, there are new bug reports for both of those two parts of the bug. Headover to [bug 419300](https://bugs.kde.org/show_bug.cgi?id=419300) (mail tree reset) and [bug 425665](https://bugs.kde.org/show_bug.cgi?id=425665) (crash on opening attachment). You can cast your votes there so that the kmail maintainers can pay more attention to it.

**Comment by tsujan** [comment]
@NickLion, @abracwan, feel free to add comments to this page if you have new info.

Being busy with several projects, I can't look into KDE codes. But judging from the appearances, I think there should be some code in KMail, Kontact or one their dependencies that changes the item selection under some problematic conditions or in a problematic way.

It's also possible that some change in a recent version of Qt has triggered the problem in KMail/Kontact or is the culprit but, since I haven't seen a radical change in the behavior of item views, I give this a low probability.

**Comment by abrac** [comment]
@NickLion @feilee I was looking into this again recently, and realised that their is a fairly obvious workaround. 

Go to `/usr/share/Kvantum/<theme>/`, where `<theme>` is the theme that you are currently using. Symlink its `svg` file and copy its `kvconifg` file to a new folder: `~/.config/Kvantum/<theme>-no-inactiveness/`. Open the new `kvconfig` file in a text editor and find "`no_inactiveness=false`". Change `false` to `true`. 

Open *KvantumManager* and go to *Application Themes*. Select your new theme (i.e. `<theme>-no-inactiveness`) and add the following applications: *Kontact,KMail,KOrganizer,KAddressBook,Akregator,KNotes*. Click *Save*. Quit and re-open Kontact/Kmail, and you will see that you will no longer get the previous issue.

**Comment by tsujan** [comment]
@abrac, thanks! That option is in Kvantum Manager → Configure Active Theme → Compositing & General Look → Ignore inactive state.

A user had said that it didn't make a difference but he might not have restarted Kontact/Kmail after checking the above option.

It seems reasonable: if Kontact/Kmail has problem with inactiveness, then inactiveness can be disabled as a workaround.

**Comment by nicman23** [comment]
i can confirm that for me it did not help as i was already running with the above option anyways (and had the issue)

**Comment by tbigfoot** [comment]
Quite an old closed thread, but as I spent some time to workaround this issue somehow, I consider worth to mention the solution that actually helped in my case.
It actually didn't help to set `no_inactiveness` either, but updating specific kvantum theme's config and removing all references to inactive colors did the trick (e.g. values like `inactive.window.color`).

**Comment by tsujan** [comment]
@tbigfoot 
Thanks! To me, it shows again that Kontact/Kmail has a bug in handling the inactive/active states of its item views.

But it also shows that `no_inactiveness` was skipped somewhere in Kvantum's code because, otherwise, you wouldn't need to remove inactive colors when it's set to `true`. I hope that's corrected in the latest commit: https://github.com/tsujan/Kvantum/commit/01c39abf99a78630e3f5635a5c6828754ec4b225

**Comment by tsujan** [comment]
I'm afraid if all KDE devs have the following attitude, this bug will never be fixed. Quoting from https://bugs.kde.org/show_bug.cgi?id=419300#c10:

```
changing the color when a window looses focus is a silly design
```

A silly design is the one that assumes active and inactive widgets should have the same colors — as if `QPalette::Inactive` doesn't exist in Qt!
