### ISSUE TITLE
.desktop files that do not pass validation.

### ISSUE THREAD

**Issue by whyman** [tsujan/Kvantum#565]
Hi,

On Gentoo, we receive the following:
```
 * QA Notice: This package installs one or more .desktop files that do not pass validation.
 * 
 * 	/usr/share/applications/kvantummanager.desktop: error: value "Qt;Utility;Settings;DesktopSettings;LXQt;X-XFCE-SettingsDialog;X-XFCE-PersonalSettings;X-GNOME-PersonalSettings;" for key "Categories" in group "Desktop Entry" contains an unregistered value "LXQt"; values extending the format should start with "X-"
```
See: https://bugs.gentoo.org/743052

**Comment by tsujan** [comment]
Hi,

`LXQt` is a category used by the LXQt desktop environment. All desktop entries belonging to `lxqt-config` are in that categoriy and appear in LXQt Configuration Center. I want Kvantum Manager to appear in the same place.

I might discuss the error message of `desktop-file-validate` with the LXQt team later. But the issue is not in Kvantum.

Anyway, thanks for mentioning this!

**Comment by tsujan** [comment]
I opened a question here: https://github.com/lxqt/lxqt/issues/1845
