### ISSUE TITLE
The headings of some windows have wrong background color

### ISSUE THREAD

**Issue by nortexoid** [tsujan/Kvantum#566]
Not sure if this is a bug in kvantum, KDE, or my theme, but in the following screenshot you can see that windows with a certain style of heading take the base.color color for the background of the heading instead of the window color. Can this be fixed?

![Screenshot](https://user-images.githubusercontent.com/969567/94932411-5111f100-04c9-11eb-9cc2-c2089ee1c4c9.png)

**Comment by tsujan** [comment]
It may have 2 causes: Bad style codes in KDE and/or QML.

Some KDE GUIs use KDE color schemes directly, instead of using `QPalette`. So, make sure that you have a KDE color scheme that matches your Kvantum theme (see the explanation in Kvantum Manager → Change/Delete Theme).

As for QML, see Kvantum → `Theme-Making.pdf` → `A word about QML/Qt Quick`.

**Comment by tsujan** [comment]
Also you may mean "KTitle". If so, check Kvantum Manager → Configure Active Theme → Transparent KTitle label.

**Comment by nortexoid** [comment]
Thanks--checking "Transparent KTitle Label" solved the problem. Now at least I know what those titles are called :)

**Comment by tsujan** [comment]
Sometimes it's hard to know what causes a problem in KDE. I first check QML and bad coding styles because there are so many instances of them. In this case, they weren't the cause -- I misread your comment at first; my mistake.
