### ISSUE TITLE
Cannot apply themes to anything except Manager. Cannot disable composite effects non-root.

### ISSUE THREAD

**Issue by negativzeroe** [tsujan/Kvantum#568]
Essentially title, I have in my ~/.profile: 

    export QT_QPA_PLATFORM=wayland
    export QT_STYLE_OVERRIDE=kvantum

I've tried testing various values in there that I have found across the internet as well as guesses, qt5, xwayland, etc.

Themes apply to the manager but if I open Calibre, Sigil, Nextcloud client, Flameshot config, all still have the bland white theme that is default. I have searched and not found much on the subject, I have qtwayland5 installed, running Ubuntu 20.04. On top of this I cannot disable the composite effects to get rid of transparency, if I run as sudo I'm able to.

**Comment by tsujan** [comment]
Your question isn't about Kvantum but Qt5. I guess your DE isn't Qt-friendly.

You didn't mention under which DE you work but most probably, `.profile` isn't sourced by it. You could check that in a terminal:

```
echo $QT_STYLE_OVERRIDE
```

Each DE should have a tool for setting EVs but you could also try `~/.config/environment.d/*.conf`. See https://www.freedesktop.org/software/systemd/man/environment.d.html

If your DE is Gnome, be cautious about `QT_QPA_PLATFORM=wayland`. It may cause all Qt apps crash.

> Themes apply to the manager

Because it's forced there. Other Qt apps need `QT_STYLE_OVERRIDE`. You could also try a Qt config tool like `qt5ct`, which not only sets `QT_STYLE_OVERRIDE` but has more settings.

> On top of this I cannot disable the composite effects to get rid of transparency

Wayland doesn't exist without compositing.

**Comment by tsujan** [comment]
> if I run as sudo I'm able to.

Running an app with sudo is a big mistake under X11 and impossible under Wayland. Your app uses XWayland, not Wayland; otherwise, you couldn't run it with sudo.

All in all, Ubuntu 20.04 isn't an ideal distro for experimenting with Wayland. If you like Wayland, you need a bleeding-edge distro (like Arch, Manjaro, OpenSUSE Tumbleweed,..).

**Comment by negativzeroe** [comment]
I just came from Arch this weekend, was having trouble waking when docked and it's necessary as my machine is production. After about two weeks of coming up empty I decided to switch to Ubuntu. I'll try placing environment variables.

**Comment by negativzeroe** [comment]
Is there any other way to disable transparency in a kvantum theme I like if I can't disable compositing?

**Comment by tsujan** [comment]
> if I can't disable compositing?

Oh, I thought you told about translucency under Wayland in general. Disabling *Kvantum's* translucency is possible by disabling composite effects in Kvantum Manager; X11 and Wayland aren't different in this regard.

If that doesn't work for you, I'm afraid there should be a problem somewhere; e.g. in file permissions (changed by `sudo`).

**Comment by tsujan** [comment]
> I just came from Arch this weekend, was having trouble waking when docked and it's necessary as my machine is production. 

I suggest Manjaro then: Arch without Arch hassles.

**Comment by tsujan** [comment]
OK, I tried `~/.config/environment.d/qt.conf` under gnome-shell with another machine and it worked without problem: I put `QT_QPA_PLATFORM=wayland` in `~/.config/environment.d/qt.conf` and rebooted. A reboot is needed and "export" shouldn't be used there.

Strange that Gnome doesn't have a simple utility to set an EV!

**Comment by negativzeroe** [comment]
Yes it seems to work for me too other than the icons, now they are breeze for some reason (it should be noted that when the qt theme wasn't affected, the icons were), is there another EV for icons?

I put it under ~/.config for testing and have: 

    QT_QPA_PLATFORMTHEME=qt5ct
    QT_STYLE_OVERRIDE=kvantum

The first line was recommended from the manager.

**Comment by negativzeroe** [comment]
Also, yeah these options are greyed out in the manager without sudo:

![image](https://user-images.githubusercontent.com/28630693/99433016-98fea300-28d2-11eb-871d-ffee5c00154a.png)

Where should I look for permissions?

**Comment by tsujan** [comment]
> The first line was recommended from the manager.

Yes, under DEs that lack a Qt plugin, qt5ct is a solution.

> Where should I look for permissions?

No. Take a look at their tooltip of "Composite effect" ;)

**Comment by negativzeroe** [comment]
Yup, I'm on Gnome, (I actually installed gnome-session so I could avoid some of the quirks of the ubuntu-session) and yes I didn't see that the first time around I feel so noob right now...

**Comment by tsujan** [comment]
> I feel so noob right now

It isn't about being a noob. Gnome isn't Qt-friendly, as Qt isn't Gnome-friendly.

BTW, you could try the themes KvGnome, KvGnomeDark and KvYaru; they're  added for use under Gnome or Ubuntu.

**Comment by tsujan** [comment]
I still don't believe that Gnome doesn't have a simple tool for setting EVs... Maybe there is one but hidden somewhere?

**Comment by negativzeroe** [comment]
Yeah I'm trying to edit one to match Arc Blackest. But I think I'm on the right path now.
