### ISSUE TITLE
tooltip delay/timeout

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#57]
could you pls add a setting to change this? Kvantum seems to display them immediately which is really annoying

**Comment by tsujan** [comment]
Good idea (although, to me, for the opposite reason)! And done! But only for Qt5: there's no easy way to implement it for Qt4.
Use the new key "tooltip_delay" under the General section. Its unit is millisecond (read Theme-Config).
I didn't add it to Kvantum Manager just because I didn't find a good place for it.

**Comment by sixsixfive** [comment]
nice ;)
