### ISSUE TITLE
Plasma5 settings dialog --> some strange colors

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#62]
![bildschirmfoto1](https://cloud.githubusercontent.com/assets/3780774/11344708/25337dfc-9213-11e5-98b2-f9f25c0e294d.png)

as you can see my popupmenu is white for some stange reason the same also happens on the included plasmathemeexplorer or cuttlefish(both plasma sdk and both seem to be QML applications)

**Comment by tsujan** [comment]
Plasma5 dialogs/menus have more issues than you may see with your theme(s). Those issues may only show up with Kvantum not because they're Kvantum's fault but because it uses parameters beyond Breeze or other theme engines.
Unfortunately, with so many important bugs in Plasma5, such issues may not be fixed soon. Worse than that, the KDE devs might even not see them because of their emphasis on Breeze.

**Comment by sixsixfive** [comment]
>may only show up with Kvantum not because they're Kvantum's fault but because it uses parameters beyond Breeze or other theme engines.

well I did a few tests with a dark color scheme: oxygen, windows=fail breeze, fusion=works

its also stange that fusion works since its a very simple/generic theme and I don't think there are any KDE specific fixes

>because of their emphasis on Breeze...

hm it think the breeze style is ok, but the icon theme is crap ;(

>Unfortunately, with so many important bugs in Plasma5

haven't found any yet - maybe thats because I'm using now a Qt-centric distro.

**Comment by tsujan** [comment]
> its also strange that fusion works since its a very simple/generic theme

It works exactly because of that ;) Every developer should test his widgets with Fusion first.

> it think the breeze style is ok...

I didn't mean it wasn't OK. To me, it's a good minimalistic theme. They just don't (have time to) check their design with other style engines to see probable mistakes.

> haven't found any yet - maybe thats because I'm using now a Qt-centric distro

And maybe I found many because I wanted to restore all the good things I had with KDE4 ;) My last test, yesterday, was a nightmare: it took me half an hour to realize why Plasma5 totally froze whenever I tried to open any file with Dolphin -- it was because I used Aurorae instead of the default titlebars. KDE is so complex that such bugs may show up only under specific circumstances.

BTW, after seeing Qupzilla in the taskbar of your screenshot, I got its latest version and saw that its speed-dial settings dialog had a slider issue, which I'd never seen anywhere else but made me change a boolean. I'll push the change after some tests. (The invisiable Apply and Close buttons with dark themes is Qupzilla's fault).

**Comment by sixsixfive** [comment]
> (The invisiable Apply and Close buttons with dark themes is Qupzilla's fault).

well it sucks like all browsers with dark themes but there is a fix if your theme includes a bright GTK version(the only real fix I know is using a GTKbased browser to switch to a bright version with GTK2_RC_FILES= or GTK_THEME=)

>And maybe I found many because I wanted to restore all the good things I had with KDE4

Good luck, I'm still missing many great things from KDE2/3 (*-_-)

**Comment by tsujan** [comment]
Fixed Qupzilla's slider.
