### ISSUE TITLE
Kvantum-0.9.2_amd64.deb does not work with Kubuntu 15.10 Plasma 5.4.3

### ISSUE THREAD

**Issue by wolfland** [tsujan/Kvantum#63]
It's me again..

I am running Kubuntu 15.10 with Plasma 5.4.3 from kubuntu backports. Kvantum 0.9.1 works fine
but when I installed Kvantum-0.9.2_amd64.deb using sudo dpkg -i the theme changes to "breeze"
and the "Kvantum" theme engine no longer appears in System Settings dialog. When I re-install
Kvantum-0.9.1_amd64.deb it goes back to working fine as before. 

Just wanted to let you know there might be a problem and I will run 0.9.1 in the meantime.

Let me know if you need to try anything.

Thanks,
WolfLand

**Comment by tsujan** [comment]
Thank you for telling me about such problems!
Kvantum-0.9.2_amd64.deb is compiled against Qt-5.5.1 (under Debian), while Ubuntu's Qt version is still 5.4.2. Qt-5.5.1 includes some changes that aren't backward compatible. I'll change the Qt dependencies of the next package so that it couldn't be installed with Qt < 5.5.1.

**Comment by tsujan** [comment]
After installing Kubuntu-15.10 on VirtualBox and making a deb for it, I uploaded an archive to "kde-look.org" with two deb packages, one of which (with "ubuntu" in its name) is for Ubuntu. Please try it and tell me if it works for you!

**Comment by wolfland** [comment]
Tsujan,

           The 0.9.2-1 Ubuntu deb is tested and works fine.

Thanks again,
WolfLand

**Comment by tsujan** [comment]
Good! Please keep telling me about problems like this in the future!

BTW, if I remember correctly, you'd reported crashes with KDE on two occasions, when Kubuntu was in transition. Months ago I experienced such a crash under Debian and found its cause. It was only because not all Qt packages were updated. So, whenever Kubuntu is in a transition state, you could wait until *all* Qt packages are ready to be upgraded to the same version.

**Comment by wolfland** [comment]
Good info thanks for passing it on. I will keep that in mind next time I 
have problems
with Kubuntu.

And of course I will keep you informed of any issues I have with Kvantum.

WolfLand
