### ISSUE TITLE
Option to disable smooth scrolling

### ISSUE THREAD

**Issue by new-sashok724** [tsujan/Kvantum#644]
Hello again :) Not a bug, but feature request, hopefully addressed to right project this time:

I prefer to disable all kinds of animation in my system for maximal UI responsiveness.
When i switched from Breeze theme to Kvantum (KvArc), i noticed that scrolling stuff e.g. in Dolphin is not instant (it is slightly animated), despite that `Animation speed` setting in KDE is set to Instant, and `animate_states` in Kvantum theme config is disabled.
If i change theme from Breeze to Kvantum while Dolphin is running, scrolling is still instant until i restart the app.
I think option to disable animation for scrolling would be useful.

Thanks in advance!

**Comment by tsujan** [comment]
I'm afraid this isn't related to Kvantum either. Kvantum has no scrolling animation.

I don't think System Settings' animation speed has anything to do with Dolphin but I may be wrong. Anyway, Kvantum doesn't cause Dolphin's smooth scrolling.

**Comment by new-sashok724** [comment]
But i tested it before reporting. With Breeze, there's no smooth scrolling

**Comment by tsujan** [comment]
I've written every line of code in Kvantum. Except for "Kinetic scrolling", which isn't about what you described and is disabled by default, Kvantum doesn't have any code for smooth scrolling. In fact, each app needs to have its own code for it if it wants smooth scrolling.

**Comment by new-sashok724** [comment]
I've looked in Dolphin code, looks like it's using QStyle::SH_Widget_Animation_Duration property. Is it something that can be changed by theme?

**Comment by tsujan** [comment]
Yes, `SH_Widget_Animation_Duration` can be controlled by the style but Kvantum doesn't touch it. Actually, most styles don't touch it; Fusion (the default style of Qt) either.

However, I took a look at Breeze's code and saw that it changed it according to KDE's settings. Being a KDE-specific style, Breeze follows KDE settings. Kvantum can't follow KDE settings because it isn't specific to KDE.

Moreover, it's up to the app to make something out of `SH_Widget_Animation_Duration`. I'm not sure that Dolphin's smooth scrolling follows it but *if it does*, that's something specific to Dolphin. I've written the code of smooth scrolling for [pcmanfm-qt](https://github.com/lxqt/pcmanfm-qt) and it doesn't depend on `SH_Widget_Animation_Duration`.

All in all, this is about KDE and how it sets its own parameters.

**Comment by new-sashok724** [comment]
Maybe add option to set it? If it's in Qt, it can be used by any application, so not Dolphin-specific

**Comment by tsujan** [comment]
I can add an option for it but it would be misleading for the following reason:

Dolphin's following `SH_Widget_Animation_Duration` for its smooth scrolling is just what Dolphin does: it has a certain code for smooth scrolling that depends on `SH_Widget_Animation_Duration`. That's just a choice, not a rule. You can't enable smooth scrolling in a Qt app just by setting `SH_Widget_Animation_Duration` to a non-zero value (a value that it has by default); you should write code for it. I hope that'll change in Qt6 but it isn't the case for now.

**Comment by new-sashok724** [comment]
I think option for it should be named just like in Qt documentation ('Animation duration'), not 'Enable/disable smooth scrolling' :)

```
Determines how much an animation should last (in ms). A value equal to zero means that the animations will be disabled. This enum value has been introduced in Qt 5.10.
```

**Comment by tsujan** [comment]
Once this thing is standardized in Qt, I'll add an option for it. For now, it would be a source of confusion.

When there is *no* scroll animation in most apps, what should last X ms? ;) People would change it and see no change, e.g., in qpdfview or Qt Designer — even under KDE — simply because they have no code for scroll animation and if codes are added to them, they might not depend on it.

BTW, that "explanation" in Qt doc is very confusing too: Which animation? Where? Unless you look into Qt's source, you won't know it's about tree views, tab-bars, tool-bars, *and not about list views*!

Kvantum's animations have nothing to do with it.
