### ISSUE TITLE
Text color does not persist

### ISSUE THREAD

**Issue by mvenghaus** [tsujan/Kvantum#648]
Hello,

I've the problem that the text color is correct after applying a theme. But when I close the window and reopen it the text is not readable. I've tried reinstalling, different themes with no success.

After "Use this theme"
![image](https://user-images.githubusercontent.com/6408081/116891706-51c16000-ac2f-11eb-8016-aa8ac5e42def.png)

After restart
![image](https://user-images.githubusercontent.com/6408081/116891784-6d2c6b00-ac2f-11eb-8e6f-1c82734d4beb.png)

Resolution: 1920x1080 
DE: GNOME 3.38.4 
WM: Mutter 
WM Theme: Mojave-dark 
Theme: Mojave-dark [GTK2/3] 
Icons: McMojave-circle-dark [GTK2/3]

Any ideas?

Regards
Marcus

**Comment by tsujan** [comment]
The problem is in the theme you use, not in Kvantum.

**Comment by tsujan** [comment]
And there's a contradiction in your report: you have "KvGnomeDark" in your screenshot, which is a theme that is shipped with Kvantum and does NOT have any problem (no theme that comes with Kvantum has a problem).

Probably, you've edited "KvGnomeDark" manually and in a wrong way. Or, maybe, you've installed a buggy, third-party theme with the same name.

**Comment by tsujan** [comment]
There are also two other possibilities. As the text in the screenshot says, under Gnome, a Qt config tool is needed. You may have none or you may use `qt5ct` with customized palettes/colors.

**Comment by mvenghaus** [comment]
thx for the fast reply!

fyi  I changed QT_QPA_PLATFORMTHEME from gnome to gtk2 and now everythings works perfect

**Comment by tsujan** [comment]
> I changed QT_QPA_PLATFORMTHEME from gnome to gtk2

Then, you're using Qt's gtk2 style, nor Kvantum.

**Comment by mvenghaus** [comment]
As you probaly already see I'm not an expert :) For my understanding kvantum is a style plugin and needs s.th. like base platform theme. Or do I have to change the platform theme to kvantum!?

These are my settings:
QT_QPA_PLATFORMTHEME=gtk2
QT_STYLE_OVERRIDE=kvantum

**Comment by tsujan** [comment]
> As you probaly already see I'm not an expert

It's all right. You shouldn't need to be an expert to use Kvantum. The problem is that your DE is Gnome and Gnome is Qt-unfreindly.

Take a look at https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md#in-other-des. For Gnome, `~/.config/environment.d/qt.conf` works. Just create that file, add `QT_STYLE_OVERRIDE=kvantum` to it and reboot.

`QT_QPA_PLATFORMTHEME` is for the platform Qt plugin. What does it do? It can set the icons of Qt apps, change the active style (to Kvantum, Fusion, Breeze,...), etc. In short, it's for Qt's settings. Gnome doesn't come with a Qt plugin but I've seen Gnome users usually use `qt5ct`. Whether you'll need it or not, I'm not sure.

**Comment by mvenghaus** [comment]
thx for the explanation!
