### ISSUE TITLE
colorize icons

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#67]
Not really a feature request but I found this feature in virtuality(https://github.com/luebking/virtuality), it colorizes the icons on hover which is a very nice subtle effect for the more and more common symbolic icons

https://drive.google.com/file/d/0B_2_dsXrefR-VXFQc29UVl9IbUE/view?usp=sharing

**Comment by tsujan** [comment]
It's possible but doesn't worth the effort, IMO.

As a matter of fact, SVG animations could be added to all elements too and, at one point, I'd also thought about a tab changing animation. But such fancy things have their costs. An extra CPU usage is just one of them. Any animation could interfere with probable hard-coded ones and I don't want false problems for Kvantum.

I admire the work of the author of Virtuality/Bespin. Several months ago, the appearance of Virtuality inspired me to add many lines to Kvantum's code just for creating themes like KvCurves and KvCurves3d but that was worth the effort because the result was beyond those themes.

**Comment by sixsixfive** [comment]
also what about some animations to make the transition between the different states more smooth (eg slowly blend in/out)

**Comment by tsujan** [comment]
I leave this issue open as I might reconsider it in the future but I'm against style engine animations for the reasons mentioned above.

**Comment by sixsixfive** [comment]
ok, also to make it clear i don't want it for any element a general setting under hacks or general would be enough

**Comment by tsujan** [comment]
Since, contrary to other style plugins, the elements can have any form and color in Kvantum, panel animations seem to be possible *only* with "frameN" elements, i.e. elements that show the Nth frame of the animation. For example, if you want a hover animation for buttons, you might include three sets of nine interior+frame elements for "button-focused" in your SVG file.

On the other hand, icon/text animations don't need extra SVG elements but they require predetermined animation types like blinking, zooming in and out, colorizing, etc.

Experimenting with these ideas requires *lots* of work and I'm not sure that the CPU usage will be reasonable or the animation will be acceptable at the end. I might try them when I have enough time. No priority and no promise though!

**Comment by tsujan** [comment]
@sixsixfive
For starters, I made the branch "experimental" and implemented a tinting effect on mouseover in it (without animation). Please test the branched zip file and tell me if it's like what you wanted (see the new Kvantum Manager -> Hacks)!

**Comment by sixsixfive** [comment]
well i personally won't use it since i love my colorful toolbar icons (=

also some ideas (eg to create a perfect GTK3/E integration")

it should be possible to recolor standard/unpressed/unfocused icons(eg on E17 all default icons are blue, GTK symbolic icons use the default text colors and change to the selected textcolor if pressed)

currently it isnt applied to active buttons like here in the file selection dialog:

![aaa](https://cloud.githubusercontent.com/assets/3780774/12007837/6084483c-ac17-11e5-8593-6a2a4adbaf30.png)

so there is no way to see if the icon/toolbarbutton is active

**Comment by tsujan** [comment]
> currently it isnt applied to active buttons...

Here, it's applied to all buttons under mouse, *except for those that are disabled*. If you mean the "Choose" button in the above screenshot, it's disabled, not active. I see no reason for tinting disabled icons.

> it should be possible to recolor standard/unpressed/unfocused icons...

"Symbolic icons" have a special meaning in GTK3 itself; hence them being colorized.
There isn't such a thing as a default icon but the icon of the default button. Kvantum has already three ways for distinguishing them, namely, bold font, the default indicator and the default frame.

All in all, because there's no concept of monochrome, symbolic icon in Qt (although KDE uses something slightly like it with Breeze), I'm satisfied by this optional hover tinting. It's good with monochrome icon sets like nouveKDEGray. Apparently you haven't encountered any problem with it either. So, I'll add it to the master branch.

**Comment by tsujan** [comment]
An example with 25% of tinting with `#8c1011`: https://dl.dropboxusercontent.com/u/7793460/tinting.mkv

**Comment by sixsixfive** [comment]
>you mean the "Choose" button in the above screenshot, it's disabled, not active. I see no reason for tinting disabled icons.

no i meant the button in the top right corner(view as list which is active)

**Comment by tsujan** [comment]
> no i meant the button in the top right corner

Here it's correctly tinted with both Qt4 and Qt5. Maybe you don't use the latest experimental branch or you can't see the tinting because of a low percentage.

BTW, I mistook the "Choose" button with something else: it's the default button as is also tinted on mouse-over here.

**Comment by tsujan** [comment]
As I found a *real* use for effects (setting the opacity of disabled icons outside KDE) and animations had better be coded in apps themselves IMO, this suggestion has done its good job. So, I close this issue.
