### ISSUE TITLE
Opaque background behind text

### ISSUE THREAD

**Issue by ardnod** [tsujan/Kvantum#670]
In Kvantum 0.20:

![20](https://user-images.githubusercontent.com/87319104/125315255-382b4b80-e337-11eb-9e59-e8af2f8c6280.png)

For example, in Kvantum 0.14.1:

![normal](https://user-images.githubusercontent.com/87319104/125315366-585b0a80-e337-11eb-92c3-7650dae3825a.png)

Kvantum theme: Spite
QT version: 5.12.8
Operating system: Kubuntu 20.04.2

**Comment by tsujan** [comment]
Yes. That's because the line-edit uses a background other than the base color. Since a version, when the background is different from the base color, Kvantum draws it because some line-edits (like those in Kate) use such backgrounds to show that a searched text is found or not.

It isn't good practice to have non-base backgrounds in line-edits — at least, the base color should be used if they aren't needed — but that's how some developers (especially KDE devs) design their apps.

Thanks for paying attention to this but I had no other choice with the current state of affairs (bad style codes). If you think you have a solution, please tell me. Closing this for now...

**Comment by tsujan** [comment]
Applied a partial solution for the dilemma: https://github.com/tsujan/Kvantum/commit/58f7d6ce87f32ab8d53473b82ee408c0aa431050

**Comment by tsujan** [comment]
And made the solution "stronger" in https://github.com/tsujan/Kvantum/commit/1e3521cbe8f8ddf3d310a85029f4a4cae980b0c5
