### ISSUE TITLE
resize grip still themeable?

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#75]
since i can't get it to work

![aaaa](https://cloud.githubusercontent.com/assets/3780774/14049522/11bd45ba-f2b6-11e5-872e-56d29ed7090d.png)

**Comment by tsujan** [comment]
> resize grip still themeable?

Yes, of course!

> I can't get it to work

The object names are `INDICATOR_NAME-normal` and `INDICATOR_NAME-focused`. INDICATOR_NAME is defined under the `SizeGrip` section and will be "sizegrip" if not defined in your theme.

You could check that with KvDark, which has a different sizegrip.

**Comment by sixsixfive** [comment]
yeah but if i disable both the frame and the interior(as in the config) shouldn't it not empty?

**Comment by tsujan** [comment]
> if i disable both the frame and the interior(as in the config) shouldn't it not empty?

No, because it is an indicator.

To disable it, you have two options: either set `indicator.element=none` under the `SizeGrip` section (there's no object named as "none" in the default SVG file and there shouldn't be any in your SVG file), or add two invisible rectangles with the names `sizegrip-normal` and `sizegrip-focused` to your theme.

**Comment by sixsixfive** [comment]
i see indicator instead of interior fixes it ...

**Comment by tsujan** [comment]
In fact, SizeGrip did have an interior and frame at first but several months ago, when I started to clean up the code, I found that senseless and changed it to an indicator.

The list and properties of all indicators can be found in the table under Theme-Making.pdf → Indicators.
