### ISSUE TITLE
Changes to theme .svg file titlebar/menubar colors not effected

### ISSUE THREAD

**Issue by cjkr** [tsujan/Kvantum#753]
When I make changes to the titlebar or menubar in the .svg file, these changes in color are not reflected even after restarting the computer. I have installed kvantum 1.0.0-1 on Plasma 5.23.4 using the Fluent theme found [here in the KDE store](https://store.kde.org/p/1499836).

**Comment by tsujan** [comment]
The problems are in your SVG files.

As for menubar, its color can be changed without problem in your light theme. However, in your dark theme, you have this under its elements in your SVG file:

```xml
style="opacity:0.05;fill:#ffffff;fill-opacity:1" />
```

An opacity of 0.05 is so low that you couldn't see the color.


As for titlebar, you have this:

```xml
  <path
     id="titlebar-focused"
     d="m223.93 354.69v32h32v-32z"
     fill="#f7f7f7" />
```

If you change the color manually, you'll see it changed in `kvantumpreview`. But if you change the color by using Inkscape, you won't see any change because  Inkscape makes it like this:

```xml
  <path
     id="titlebar-focused"
     d="m223.93 354.69v32h32v-32z"
     fill="#f7f7f7"
     style="fill:#fc0000;fill-opacity:1" />

```

Here, the problem is `fill="#f7f7f7"`: it takes priority. I think you might have added it manually or some app might have made it so for you (an SVG cleaning app?). If you remove it, you'll see what you do in Inkscape.

Please also note that "titlebar" doesn't have anything to do with the main window; it's only for MDI (sub-windows). The titlebar of the main window is determined by your window manager (e.g., KWin in KDE).

**Comment by tsujan** [comment]
BTW, my explanation was about "Fluent-round". I downloaded "Fluent" and saw the same thing in its SVG files, namely, lines like `fill="#202020"`. Maybe, its author (whom I mistook for you) used a program other than Inkscape.

**Comment by cjkr** [comment]
From your advise, I went and opened the SVG file with a text editor and saw that each element had two color values. I manually changed the **fill** property to match the **style** color property. It fixed the problem. Thanks for the assistance.

**Comment by tsujan** [comment]
You're welcome.And sorry for thinking that the SVG files were made by you.

**Comment by cjkr** [comment]
No problem.
