### ISSUE TITLE
[idea] reversed tabs

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#78]
recently i had to create my gtk3 theme from scratch(thanks to the gnone/gtks devs -_-), however i played a bit with the normal tabs/notebooks and found something really nice(ok its a bit different) but would something like this possibe in kvantum?

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/14297241/2295fde8-fb7e-11e5-8810-ca36701e9721.png)

https://github.com/sixsixfive/Ivy/blob/master/.dist/.stuff/gtk-3.20/theme/notebook.css

**Comment by tsujan** [comment]
That's something you could do in the SVG file by creating appropriate objects for tabs; nothing is needed to be changed in the code, IMO.

**Comment by tsujan** [comment]
I'll try to make an SVG file for it when I have free time.

**Comment by tsujan** [comment]
An example of what can be done in the SVG file:

![tabs](https://cloud.githubusercontent.com/assets/981076/14302224/e373842e-fbb3-11e5-9d39-ce18391ae3f7.png)

Because tabs have totally different structures in Qt and GTK+, an exact replica of your screenshot isn't possible. However, the opposite is also true: a GTK+ replica of KvCurves' tab is impossible, for example ;)

**Comment by tsujan** [comment]
A more polished example:

![2016-04-06-07 04 43-scrot](https://cloud.githubusercontent.com/assets/981076/14304223/51e241ea-fbc6-11e5-90c8-985ad4b6973b.png)

**Comment by sixsixfive** [comment]
yeah i see, not possible for normal tabs...

**Comment by tsujan** [comment]
No, it isn't possible, in a sense. More specifically, QTabBar is outside the page area of QTabWidget, while GtkNotebook is a container that includes tabs too. So, what's stylistically possible for one may not be possible for the other.
