### ISSUE TITLE
[Q] How to change font size?

### ISSUE THREAD

**Issue by mizzunet** [tsujan/Kvantum#788]
Font size seems to be a bit smaller.
![image](https://user-images.githubusercontent.com/10193999/166260417-55908295-ccbb-4ac0-957f-adba4943f279.png)

How can I change font size with Kvantum?

`qt5ct` and `qt6ct` can change font and size. But any one of these can be used, can't use them together.

I have `$QT_STYLE_OVERRIDE=kvantum`. I have no DE.

Thanks (:

**Comment by tsujan** [comment]
> qt5ct and qt6ct can change font and size.

They are *platform-theme* plugins and should have that feature. Kvantum is a *style* plugin and shouldn't set the font size; that's not its job.

A Qt platform plugin (usually inside `/usr/lib/qt/plugins/platformthemes/`) is required for choosing and activating style plugins (inside `/usr/lib/qt/plugins/styles/`) as well as changing other settings. KDE  and LXQt have advanced platform plugins; `qt5ct` can be used under other DEs.

**Comment by tsujan** [comment]
> Font size seems to be a bit smaller.

The font and its size are exactly those of the platform. Kvantum doesn't and shouldn't change them.

**Comment by tsujan** [comment]
> But I cannot use both qt5ct and qt6ct at a same time, can I?

Logically, Qt5 and Qt6 plugins shouldn't interfere with each other; if they do, there is a design problem that should be fixed by their developers.

For example, I use a Qt6 plugin for LXQt (which will be merged when LXQt is ported to Qt6), while LXQt's Qt5 plugin is also active. Therefore, LXQt's font settings apply to Qt5 and Qt6 apps alike: I have the same font with the same size in Qt5 and Qt6 apps.

If `qt6ct` can't be used alongside `qt5ct`, I think it's developer needs to know about the problem.

Anyway, without a Qt6 plugin, you can't change font and/or its size in Qt6 apps.

**Comment by eclairevoyant** [comment]
@mizzunet can't you set `QT_QPA_PLATFORMTHEME=[themeName]` per application rather than exporting globally? that should solve the issue. Arch wiki also mentions you can instead pass `--platformtheme [themeName]` as an arg to the application

Although all this is kind of OT for this repo, I figured I'd add it here since it's the first place I ended up looking.
