### ISSUE TITLE
Grey header background and grey lines in some applications

### ISSUE THREAD

**Issue by bathtime** [tsujan/Kvantum#803]
Tested on:
OS: Manjaro KDE
Arch: x86-64/ARM
WM: X11 and Wayland

In the KDE settings manager there are grey lines located near the scroll bars and between list items (first pic below). And it seems to possibly be connected, but in KDE system manager, konsole, gwenview, and other applications, there are grey header backgrounds when the header/application isn't active/focused.

This seems to happen regardless of KDE or Kvantum settings, colors, or theme chosen. I've tried using multiple SVG files from different themes with all elements turned on full red, and they still remain some variation of grey.

Editing the inactive colours in the KDE system settings manager can change the shade of the header background, but it will always be some shade of white, regardless of hint, shade, or tint settings.

I would like to turn those objects cyan or black to fit the theme, and I'm thinking they should be able to be changed as most other elements can be.

Generally this issue isn't really a big problem on light themes, but in high contrast and dark themes, this can be quite noticeable. I've fixed the issue using qt5ct with a stylesheet, but this creates more problems than it solves and breaks much of the Kvantum theme.

KDE Settings:
![KDE settings](https://github.com/bathtime/amoled/raw/main/screenshots/greylines.png)

Konsole (note again that it only happens in the unfocused split tab):
![konsole](https://github.com/bathtime/amoled/blob/main/screenshots/greyheader.png?raw=true)

My settings can be located here, but I suspect you won't need them to see the issue:

[Theme settings on github](https://github.com/bathtime/amoled/tree/main/.config/Kvantum/amoled)

Thanks for reading and for all your hard work!

**Comment by tsujan** [comment]
Sadly, KDE is full of bad style codes and has so many style bugs. What you described is just a harmless example. A more serious one can be seen in this screenshot of Dolphin:

![dolphin](https://user-images.githubusercontent.com/981076/174457355-e2c3034c-8c7e-4007-8e39-ee2cad2d2a69.png)

Why KDE devs don't leave styling to the Qt widget style where there's no benefit to interfering, I don't know. They sometimes contradict KDE rules too (in the above screenshot, `ChangeSelectionColor` is set to `false`, and the problem is also reproducible with Fusion and Breeze).

There are lots of worse cases, which terribly contradict [QStyle](https://doc.qt.io/qt-6/qstyle.html). Kvantum can do nothing about them.

**Comment by tsujan** [comment]
> I've fixed the issue using qt5ct with a stylesheet, but this creates more problems than it solves and breaks much of the Kvantum theme.

Stylesheets are the enemy of Qt widget style. The problematic situation of Qt stylesheets is known to Qt devs too: https://bugreports.qt.io/browse/QTBUG-68671

**Comment by tsujan** [comment]
BTW, out of curiosity, I installed your Kvantum theme, logged into KDE from LXQt, launched systemsettings5 and didn't see any gray strip:

![amoled](https://user-images.githubusercontent.com/981076/174462520-b08770ba-ff1a-42d5-9788-4c8cbe95980c.png)

This may be related to a KDE setting (which I can't find in the jungle of KDE settings) or a different version of Plasma (I have plasma-desktop 5.24.5-2 from Manjaro).

However, this doesn't make any difference in what I said about KDE's style code.

**Comment by bathtime** [comment]
You must be able to see them but just aren't looking close enough; I can see them clearly in your picture above. There are several of them, though they are only about one pixel in wide, so they're easy to miss. One is under the 'Notifications' header.  Another is over the 'Highlight Changed Settings' button. Another is directly beside and below the scrollbar. Using a color picker, you'll see those are true grey and not cyan.

https://github.com/bathtime/amoled/blob/main/screenshots/greylines-devpic.png?raw=true

**Comment by tsujan** [comment]
Oh, I thought you meant the gray *strip*. Otherwise, yes, I can see those *lines*. They're drawn by the app and can be seen with all styles.

But their being gray should depend on your color scheme and/or your Kvantum colors inside `kvconfig` file (I don't have time to check the code of an app like systemsettings5 to know what colors it uses) because they are definitely not gray with KvCyan:

![kvcyan](https://user-images.githubusercontent.com/981076/174497249-dd0ee091-fd31-4dc8-87d1-50cc349ad40f.png)
