### ISSUE TITLE
QML widgets still broken

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#84]
fusion:
![fusion](https://cloud.githubusercontent.com/assets/3780774/15271544/da7c258c-1a4f-11e6-8cb5-afac58b4eb5c.png)

kvantum:
![kvantum](https://cloud.githubusercontent.com/assets/3780774/15271546/e691c192-1a4f-11e6-8966-32440155a455.png)

**Comment by sixsixfive** [comment]
tabs are broken, too(text attach active tab)

qml:

![tabsqml](https://cloud.githubusercontent.com/assets/3780774/15271663/7aa239d0-1a54-11e6-8b13-05260565917b.png)

normal:

![tabs](https://cloud.githubusercontent.com/assets/3780774/15271664/837f1442-1a54-11e6-84cb-dc6e43327901.png)

**Comment by tsujan** [comment]
Ah, again an incomplete design that presupposes all margins/spacings should be fixed as they are in Fusion! I'll see if I can include yet another workaround for such tabs. Thanks for reporting!

But the Wallpaper dialog is "OK" here:

![wallpaper](https://cloud.githubusercontent.com/assets/981076/15273722/6c751d10-1ab7-11e6-9934-d28495721431.png)

"OK" because the combo-box arrow button has an acceptable panel in all Kvantum extra themes and not OK because Plasma widgets are a mess. There should be something in your theme that prevents drawing of a panel for that button.

**Comment by tsujan** [comment]
I was happy to see that even Fusion and Breeze couldn't hide the faulty design of those tabs:

![3](https://cloud.githubusercontent.com/assets/981076/15274110/b7069c2e-1ac0-11e6-9547-57a4b8384082.png)
![4](https://cloud.githubusercontent.com/assets/981076/15274114/be9347bc-1ac0-11e6-8f09-20938e2bf022.png)

Yes, the problem is shown worse by Kvantum but it's up to the designer to correct it. I can't include a workaround for every design flaw -- although I do for the recurrent ones.

It remains to see why Plasma arrow buttons don't have panel in your theme.

**Comment by sixsixfive** [comment]
>But the Wallpaper dialog is "OK" here:

there is still no border on the treeview and wallpaper selection, also for some strange reason kvantum uses the dropdown image for the combobox

**Comment by tsujan** [comment]
> for some strange reason kvantum uses the dropdown image for the combobox

Why they didn't use a standard combobox in plasma widgets, I don't know. The same is true for Plasma spinboxes. Kvantum shows them as they really are: an amalgam of a line-edit with a button bg color (!) and a dropdown button. Of course, Kvantum doesn't give a button bg color to that line-edit because it's SVG-based.

I'm just curious why the arrow panel isn't drawn by your theme. A link for download?

> there is still no border on the treeview and wallpaper selection

A screenshot?

BTW, I can't see those ugly tabs in systemsettings-5.6.3-1 on Manjaro anymore. (Removed?) I'll make a small compromise for their height because it doesn't require redundant calculations - but not for their width.

**Comment by sixsixfive** [comment]
>I'm just curious why the arrow panel isn't drawn by your theme. A link for download?

i have no frame and background for them
https://github.com/sixsixfive/Ivy/blob/master/gui/base/Ivy/.themesrc/Kvantum/Ivy.kvconfig#L306

**Comment by tsujan** [comment]
Oh, that's your choice but then your drop-down buttons should be cut at right, unlike this:

![2016-05-15-22 03 01-scrot](https://cloud.githubusercontent.com/assets/981076/15275750/59134ddc-1ae9-11e6-8bee-6f640b8b8fc9.png)

**Comment by tsujan** [comment]
Now I got what you said about no border on the wallpaper selection. I have no idea but I'm pretty sure it's about Plasma widgets again. Since they don't have any function, I have no motivation to examine the source of that untidy dialog. Maybe later.

I'll close this issue after including the small workaround mentioned above -- unless you find a problem that's really in Kvantum.

**Comment by tsujan** [comment]
OK, I found the problem of those QML combo-boxes: they announce the existence of a line-edit while they aren't editable! After I made Kvantum not take such announcements seriously, they're drawn like ordinary combo-boxes. This is with your theme:

![screenshot_20160516_012457](https://cloud.githubusercontent.com/assets/981076/15276754/37c44772-1b06-11e6-8ea1-fc7ab39b2c39.png)

I'll make commits after some tests tomorrow.

**Comment by tsujan** [comment]
All problems -- except for the bad design of those ugly tabs -- should be fixed now. The cause was the inconsistent behavior of some QML widgets (read the commit text). Please test!

And please report any QML problem you find -- except for a checkbox position in the preferences dialog of the Plasma CPU monitor ;)

**Comment by sixsixfive** [comment]
nice

> Please test!

I will however due all the recent changes I currently recreate my theme so this will take some time ;)
