### ISSUE TITLE
[minor] missing button states

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#85]
currenty there are 5 button states possibe in kvantum however a complex theme would require a few more.

eg:

button normal
button hover
button pressed
button disabled
button focused(button default/tab selection)

missing:

button pressed hover
button pressed disabled
button pressed focused

also the same states could be possible on derrivated widgets like checkboxes

for example a hovered pressed button, becomes in kvantum a unpressed hovered button

**Comment by tsujan** [comment]
In Kvantum, "focused" means "hover" most of the time -- only for line-edits it means that the widget is the focus widget (i.e. gets the keyboard focus). I think by "focused" you mean "default" and/or "focus widget", and by "hover" you mean "focused".

When a button is disabled it cannot be pressed, so "pressed disabled" doesn't make sense. "toggled disabled" makes sense and Kvantum has it (the theme maker doesn't need to do anything for it).

"pressed hover" (which means "pressed focused") is redundant because when you press a button, the mouse is already above it.

"toggled focused" makes sense but doesn't exist in Kvantum -- IMO, it clutters the states.

Check boxes and radio buttons have already "-checked-normal" and "-checked-focused" states.

Default push-buttons have two ways of being distinguished, which are added to their "normal", "focused" and "pressed" states too.

Anyway, you comment reminded me to check `PE_FrameFocusRect` and see whether it's functional because I didn't used it in any theme.

**Comment by tsujan** [comment]
OK, now the focus frame (under the `Focus` section) works for widgets that need it but I preferred to keep it disabled in all my themes (it's distracting and not so useful). Its max thickness is set to 2px.

**Comment by sixsixfive** [comment]
>"pressed hover" (which means "pressed focused") is redundant because when you press a button, the mouse is already above

for normal buttons this is true, however i mean toggled buttons(eg the toggled pushbutton in kvpreview)

**Comment by tsujan** [comment]
> for normal buttons this is true, however i mean toggled buttons

As I said above, "toggled focused" makes sense but it would clutter the states. It would also require lots of code lines without being really useful. Fusion doesn't have it either.

**Comment by sixsixfive** [comment]
ok ;)
