### ISSUE TITLE
scrollbar sliders disabled state?

### ISSUE THREAD

**Issue by sixsixfive** [tsujan/Kvantum#87]
It seems the disabled state isn't working for the scrollbars the indicator is also missing:

![unbenannt](https://cloud.githubusercontent.com/assets/3780774/15624856/a67a642a-2494-11e6-8390-6d393829f524.png)

**Comment by tsujan** [comment]
That should be about a small mistake you made in your theme:

![scrollbar](https://cloud.githubusercontent.com/assets/981076/15627156/a5b9d76c-24f0-11e6-9df5-f7241530cc63.png)

**Comment by sixsixfive** [comment]
nope, its the same in the default theme, the scrollbar becomes transparent my theme has a normal and disabled state but it isnt used(its grey like the progressbar)

**Comment by tsujan** [comment]
They are not missing in "Raspberry" whose link you gave to me:

![raspberry](https://cloud.githubusercontent.com/assets/981076/15627998/5b89dbd2-250a-11e6-8559-51d48498e4fd.png)

Give me a link for the changed version for me to find the mistake!

**Comment by sixsixfive** [comment]
I guess you are talking about the SCALE sliders? Well I'm talking about the inactive SCROLLBAR sliders!

**Comment by tsujan** [comment]
> I guess you are talking about the SCALE sliders

Yes, I was because I didn't see any problem in your scrollbar sliders.

If you mean why the slider is semi-transparent in the disabled mode, that's because all disabled widgets with frame and interior behave so. This isn't something new -- as the doc says:

"You do not need to draw any object for the disabled state of interiors or frames because they are automatically created based on the normal state by reducing its opacity. However, *the disabled states of most indicators should be included in the SVG image*..."

The disabled scrollbars don't have grip and glow because they have no sense for them (the user can't grip on them).

**Comment by sixsixfive** [comment]
so there is no way to get a normal grey inactive slider? looks like a bug to me (every theme I know uses a different image for the inactive scrollbar to show people that it is inactive(eg a scrollbar inside an inactive view or an inactive groupbox that gets only active if a checkbox is switched)

**Comment by tsujan** [comment]
I think by "inactive" you mean "disabled".

> looks like a bug to me

Why it didn't look like a bug to you in the case of push or tool buttons, for example? I don't mean that your viewpoint is invalid -- I really ask.

**Comment by sixsixfive** [comment]
For me this is a bug because its weird eg: why has the active slider a handle but not the inactive one?

A transparent slider doesnt make much sense, since on some themes(like the default one) it looks very weird(eg i can se the groove under the slider) 

Also, I have used many interfaces in the last 25y but i've never seen a transparent scrollbar slider.

>Why it didn't look like a bug to you in the case of push or tool buttons, for example?

buttons aren't styled in my theme yet - so i can't say anything about that - however if it is even there impossible to use a different image I would it consider a bug, too 

I have seen themes that made the disabled buttons and its text transparent to completely hide them - such themes would probably not possible in kvantum - Also in this case even a simple theme like adwaita wouln't be possible with kvantum (normal adwaita buttons have gradients and shadows , inactive buttons don't have them and they are brighter, thats nothing you can archive by making the button transparent)

**Comment by tsujan** [comment]
> why has the active slider a handle but not the inactive one?

In Kvantum, the disabled state of a *widget* is derived from its normal state by making it 70% opaque. Indicators have a different story. The scrollbar and its handle are widgets.

> it looks very weird(eg i can see the groove under the slider)

LOL! As if you've seen a seven-headed dragon! What you see just indicates that they're disabled.

> Also in this case even a simple theme like adwaita wouln't be possible with kvantum

You're exaggerating again! KvGnome is similar to Adwaita *enough* (and KvgnomeDark, which I'm usung now, to its dark version). I've never intended Kvantum to mimic other themes exactly. Even the default theme isn't a replica of the default theme of Enlightenment.

So, no, with Kvantum you couldn't make an *exact* replica of gtk+ themes, as with Adwaita you couldn't make *any theme* similar to some of Kvantum themes (KvCurves, for example). I've never had such an obsession.

**Comment by sixsixfive** [comment]
>as with Adwaita you couldn't make any theme similar to some of Kvantum themes (KvCurves, for example). I've never had such an obsession.

are you talking about this one http://kde-look.org/content/show.php/KvCurves+for+Kvantum?content=170534?

Also even if i dislike GTK3 I have to admit that almost any theme is possible in GTK3 (which combines image based themes like kvantum/gtk2-pixbuf with the power and easiness of  CSS. 

At the first sight I can't see anything that would make it impossible, I'm also pretty sure that it would even be possible in GTK2 with a mix of the pixbuf and the aurorae/murrine engine...

Also I close this since since it seems invalid...

**Comment by tsujan** [comment]
> are you talking about this one...

It is installed with Kvantum; you didn't need to search for it in kde-look.org.

> ... I have to admit that almost any theme is possible in GTK3...

No, it isn't; at least not with an *absolutistic* thinking style like yours ;) You may dislike gtk3 but you have a strong bias toward it. Someone with the same bias toward Kvantum might convince you that it isn't possible (I'm not that "someone").

Anyhow, that absolutistic thinking style of yours has been a real asset to Kvantum -- or maybe, I've skilfully transformed it to an asset ;) -- but I don't share in it.

**Comment by sixsixfive** [comment]
>It is installed with Kvantum; you didn't need to search for it in kde-look.org.

i never installed more than the engines and the settings/preview

>No, it isn't

And I tell you it is, ok maybe not the background blurring, however thats not the job of the composite manager. 

> You may dislike gtk3 but you have a strong bias toward it

thats ok, since GTK3 has probably the best theming engine around, sure there exist others that have more features like edje or native coded ones like Qt/C++ however the code for those is complex. CSS is well known and can do almost anything since v3.

**Comment by tsujan** [comment]
I said I'm not that "someone". So, this isn't for convincing you but for mentioning a few facts for future reference if a similar discussion happens -- facts that most people tend to overlook.

For a complex gtk3 theme like http://gnome-look.org/content/show.php/GnomishDark?content=147290, I had to do complex maneuvers that required an intimate knowledge of GTK+. Fortunately I coded in gtk, otherwise such a theme wouldn't work OK. The result was fixed -- ordinary users couldn't make any change to it without breaking it.

Of course, I should have had an intimate knowledge of Qt to make Kvantum possible, but to create a *theme* like KvDarkRed, I just had to follow Kvantum docs. The result isn't fixed -- ordinary users could make many changes to it (with Kvantum Manager) without breaking it.Those with SVG skills could do even more.

Yes, gtk3 theming is flexible, but not infinitely. Kvantum is flexible too, but not infinitely either.

@sixsixfive, your themes are *simple enough* to be made with gtk3 more easily than with Kvantum. The story is different in the case of complex themes. Just take a look at `gtk+-x.xx.x/gtk/theme/Adwaita` to see how ridiculously hard making the default GTK3 theme might be -- and yet, to me, KvGnome is much more elegant.

Although I don't compare Kvantum with Adwaita (a fair comparison would be with other Qt engines), Kvantum would be the winner if I did.
