### ISSUE TITLE
Qt6 doesn't seem to respect Xft.dpi

### ISSUE THREAD

**Issue by Trinity3e** [tsujan/Kvantum#874]
Hello, this issue is since qt6 support was introduced, a workaround was to set qt platformtheme to qt6ct and have it put the styling to Kvantum, but it introduces weird slowdowns. i need to do it properly.

The situation is as follows: no qt scale applied, bare LXQt desktop so no fancy composited scaling a'la KDE, just Xft.dpi set higher. Left: text in qt5 programs is good, right: in qt6 is tiny.

Thanks in advance, and my excuses if I provided too little info

<img width="462" alt="image" src="https://user-images.githubusercontent.com/123660226/231190887-5191318a-bee2-4904-9459-76b370a7a1d7.png">

**Comment by tsujan** [comment]
> bare LXQt desktop...

The default LXQt doesn't support Qt6 yet. There are several Qt6 branches that provide a complete Qt6 support but LXQt can't merge and release them yet because it first needs KDE Frameworks to be ported to Qt6 by KDE devs (LXQt 1.3.0 will be released soon but will still be based on Qt5).

I use those branches and have full Qt6 support under LXQt. This is qBittorrent styled by Kvantum and scaled by a factor of 2 under LXQt:

![scaled](https://user-images.githubusercontent.com/981076/231223656-d0011498-84b0-4689-b0e9-db600a2461ef.png)

Anyway, your problem was the lack of Qt6 platform support, which you solved temporarily by installing `qt6ct`. Don't forget to remove it when LXQt is ported to Qt6!

**Comment by tsujan** [comment]
BTW, Arch already provides git Qt6 branches. See https://github.com/lxqt/lxqt/discussions/2139#discussioncomment-4763798 and its following comments for a list.

**Comment by tsujan** [comment]
> Oh, so I can already build parts of LXQt on Qt6

Yes :) In addition to the packages related to the Qt6 platform support, I'm using Qt6 versions of libfm-qt, pcmanfm-qt and lximage-qt, in order to test them before porting LXQt to Qt6. I hope it'll be done for the November release.

> So qt6ct is like an universal platform override

Yes, but only for DEs that lack Qt platform support. Under LXQt or KDE, it could interfere with their Qt plugins. But, *for now*, it's safe to use `qt6ct` with LXQt.

> was that in your screenshot where you showed me qbittorrent?

Yes. I used it in terminal just to take a screenshot.

**Comment by Trinity3e** [comment]
Got it, thank you.

LE: Oh wow, I just built lxqt-qt6plugin-git, and qt6 shows good now! Didn't expect it to be that easy, i didn't even need to relogin :)

<img width="417" alt="image" src="https://user-images.githubusercontent.com/123660226/231263259-3b6568bc-0b6b-4834-a309-8b3eb864d04c.png">

**Comment by tsujan** [comment]
> I just built lxqt-qt6plugin-git, and qt6 shows good now

Good! Just don't enable `qt6ct` anymore.
