### ISSUE TITLE
Default install location cannot be changed

### ISSUE THREAD

**Issue by bertini97** [tsujan/Kvantum#913]
Dear dev, the lines
```cmake
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "/usr")
```
make `libkvantum.so` install in `/usr`, which is the reserved space to install packages with the packaging system. In the INSTALL file it says

> /usr/local may not be good in Linux distros and could cause troubles later.

I believe it should be the opposite. Moreover, adding `-DCMAKE_INSTALL_PREFIX=/usr/local` to cmake has no effect on the build location.

Please consider this, or at least make it available to change location. Feel free to close if you don't agree.

Best wishes.

**Comment by tsujan** [comment]
> adding -DCMAKE_INSTALL_PREFIX=/usr/local to cmake has no effect on the build location

`libkvantum.so` is installed where Qt's style directory is, regardless of `CMAKE_INSTALL_PREFIX`, which is for the binaries `kvantummanager` and `kvantumpreview` as well as the themes.

> In the INSTALL file it says...

Yes, because if the user installs a package later and forgets about his/her manual installations (which can happen easily), he/she might still use what's inside `/usr/local/` without knowing it.

A manual installation isn't recommended in general. Making an installable package is always the best way.
