### ISSUE TITLE
QT6 programs seems don't have blur

### ISSUE THREAD

**Issue by heddxh** [tsujan/Kvantum#923]
I use qt6ct to apply kvantum theme to qt6 app, but they don't have blur but only transparency:
![图片](https://github.com/tsujan/Kvantum/assets/63106571/2bbc2d15-d4cd-4ac4-bf55-082f89cd50c2)

If I do something wrong or it is a theme/qt bug?
My theme is [MacSonoma-kde](https://github.com/vinceliuice/MacSonoma-kde) and I am on KDE, Arch linux

**Comment by tsujan** [comment]
This isn't a bug. The blur effect needs `KWindowEffects`, and there's no stable version of it for Qt6 yet.

BTW, your screenshot shows a recent version of qBittorrent. Its GUI has become buggy since its version 4.6: those transparent regions inside its left pane are the result of bad style codes in qBittorrent. You could add it to the list of opaque apps if its developer doesn't fix it.

**Comment by heddxh** [comment]
Ok, thank you for your replay and you great kvantum!!

**Comment by tsujan** [comment]
You're very welcome.
