### ISSUE TITLE
Kvantum crashes plasma settings

### ISSUE THREAD

**Issue by hazel-bunny** [tsujan/Kvantum#942]
https://bugs.kde.org/show_bug.cgi?id=469597

**Comment by tsujan** [comment]
I don't think the problem is caused by Kvantum. In `Kvantum::Animation::updateTarget()`, `target()` is `styleObject`, which is already checked for nullity (it's also the parent object of the animation).

Moreover, since the code is taken from Qt → `widgets/styles/qstyleanimation.cpp`, the issue of Plasma settings will surface in another form sooner or later.

**Comment by tsujan** [comment]
Added a workaround in https://github.com/tsujan/Kvantum/commit/acc46e083b65f65623e7be5ede29f2d0921aea5a

However, I'm pretty sure that plasma-settings's problem will pop up in another form — as it did here once, with no trace of Kvantum in its backtrace
