### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by Grief** [tsujan/Kvantum#943]
Plasma 6 was released today. I wasn't able to get kvantum working in KDE neon. Am I missing something? If not, is it planned to upgrade to support plamsa 6?

**Comment by Grief** [comment]
Sorry, I needed to install the package `qt6-style-kvantum`

**Comment by tsujan** [comment]
Kvantum isn't related to Plasma, and it has supported Qt6 for years.

V1.1.0 will be released soon, making the default compilation be against Qt6 and using KWin6's blur and contrast effects if present  — among other things.

**Comment by tsujan** [comment]
> need my blurrrrrr

For KWin6+Wayland, it'll come soon, with Kvantum 1.1.0. I'm waiting for a stable version of kwindowsystem6 in Manjaro Testing.

In the meanwhile, if Kvantum is compiled with the option `WITHOUT_KF` set to `ON`, blurring will be supported under KWin+X11.

**Comment by Leonerd-04** [comment]
> qt6-style-kvantum

I couldn't find such a package in KDE Neon's repos. Where did you install it from?

Or am I missing something else?

By the way, I'm asking to try to fix Kvantum not appearing under Settings > Global Theme > Application Style when moving to Plasma 6. Please let me know if I should make a bug report about that.

**Comment by Grief** [comment]
@Leonerd-04 I've installed it from this ppa: http://ppa.launchpad.net/papirus/papirus/ubuntu/

**Comment by Leonerd-04** [comment]
@Grief thanks, it's working now!

**Comment by tsujan** [comment]
The default compilation is changed to Qt6 in https://github.com/tsujan/Kvantum/commit/fc4ffbfe32f1519734519c4de0b4358b2aa5e8bd. Please test the latest git.

The Wayland blur effect with scale factor > 1 has a problem outside Plasma, although the blur effect is OK under X11. That's because of an old issue in kwin_wayland. If you have Plasma6, please test the scale factor there (I don't have Plasma6 yet). If the issue still exists, I could add a simple workaround.
