### ISSUE TITLE
Kvantum+Klassy (or not only?)

### ISSUE THREAD

**Issue by evgeniy-harchenko** [tsujan/Kvantum#973]
I use [Klassy](https://github.com/paulmcauley/klassy) and Kvantum. In one of Klassy settings I have strange issue.
<details>
  <summary>Expected:</summary>

 ![image](https://github.com/tsujan/Kvantum/assets/42656259/915de94c-82cf-4395-8c3a-1f6c3603360f)
</details>

<details>
  <summary>What I get:</summary>

![image](https://github.com/tsujan/Kvantum/assets/42656259/69207597-7f29-415f-b1b5-a984b08a7c61)
</details>

Table with settings is empty. There is no problem with Breeze, Fusion, etc.

Steps to reproduce:
1. Apply `kvantum`.
2. Open `klassy-settings`.
3. Choose `Klassy: Window Decoration`.
4. Choose `Buttons` tab.
5. Open `Button Colours...`
6. Check `Override individual colours` checkbox.

Tested on KDE Neon 6, KDE Plasma 6.0.4, Kvantum version: latest git commit https://github.com/tsujan/Kvantum/commit/c25881380bcb78d91d6891b2f10b034f0948dfb6.

**Comment by tsujan** [comment]
There should be a problem in the code of those widgets in Klassy. Breeze and probably most of the other styles don't show the problem because all of them draw widgets in the same way.

The issue should be fixed in Klassy. I'm afraid I don't have time to dig into Klassy's code.

**Comment by evgeniy-harchenko** [comment]
I created [test project](https://github.com/evgeniy-harchenko/kv_bug), unfortunately the problem is not in Klassy.

**Comment by tsujan** [comment]
Thanks for providing a simple code!

Yes, I can see the problem. But when I compile the same code with Qt5, I get a correct result:

![Qt5](https://github.com/tsujan/Kvantum/assets/981076/acf4612a-1a6d-4561-ac7d-8d5b906fe71b)

I didn't find a difference between Qt6 and Qt6 by a quick look at Kvantum's code but will investigate it. Reopening....

**Comment by tsujan** [comment]
OK, this is about a bug in Qt 6.7 — it doesn't exist in Qt 6.6.0 or previous versions. There's a backward incompatible change in Qt 6.7, and the problem can also be seen with Fusion  (by using ` -style fusion`): if you resize the first row with Fusion (which isn't easy with your code but is possible) and increase its height, the check-boxes of the other rows will disappear.

Other styles don't reveal the problem (completely) because all of them use what's in Qt's `qcommonstyle.cpp`, while Kvantum has its own methods. Qt devs have made a suspicious change to that file in Qt 6.7, such that the issue becomes almost hidden.

Anyway, I added a workaround in https://github.com/tsujan/Kvantum/commit/26cab47bcb7fa13e1ee6678e53d64985da6f5f4f. Please upgrade to the latest git.

Thanks again for making me see the issue!

**Comment by tsujan** [comment]
Oh, a screenshot that shows the Klassy's config dialog with Qt 6.7 and the above-mentioned commit:

![workaround](https://github.com/tsujan/Kvantum/assets/981076/83e93bc2-4961-4545-98c6-768b9b4d1381)

**Comment by evgeniy-harchenko** [comment]
Thanks a lot for your work!

**Comment by tsujan** [comment]
It was *your* work too :) Without your help, I wouldn't think that a basic thing like this might have changed in Qt so silently.

**Comment by tsujan** [comment]
Oops! That's an old issue that I hadn't noticed, because I always use animations. Will fix it soon; it's rather a copy-paste mistake. Thanks!

> I'm sorry but...

You absolutely don't need to be sorry; I'm really happy that you find and report these hidden problem :)

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/Kvantum/commit/550374f282bbd07347c140406f08c04f326d5b03

**Comment by evgeniy-harchenko** [comment]
Oh, thanks a lot one more time! And I remembered about one more problem. KvAdapta and some other themes have strange appearance with some programs. E.g. krusader:
![image](https://github.com/tsujan/Kvantum/assets/42656259/d3d411c9-fcfb-455f-9bbd-03ca86a4df55)
Here more programs and examples: https://github.com/vinceliuice/Qogir-kde/issues/56

**Comment by tsujan** [comment]
Some old apps may not be compatible with symbolic icons. Some others may have hard-coded styles that force colors in an incorrect way, e.g., setting the background without setting the foreground, or conversely. Kvantum includes some codes for working around such problems, but that's not possible in all cases.

**Comment by tsujan** [comment]
Oh, and I'm not saying that it can't be a problem in a Kvantum theme. If you see that problem in kvantumpreview or most apps, it should be a problem in the theme (mine or not).

**Comment by evgeniy-harchenko** [comment]
Hi, @tsujan, maybe you will find this interesting or useful. I did some investigations and got some results.

So, many but not all problems are because of custom stylesheets which can be applied using `setStyleSheet`.

![bug](https://github.com/tsujan/Kvantum/assets/42656259/1c296175-ad6d-4605-a0a4-ead29f0fdec8)

1 - button to switch between empty (default) and custom stylesheets, red label - custom;
2 - plain `QToolButton` with text and icon;
3, 4 - `CheckButton` (inherits `QToolButton`) buttons are drew using `paintEvent`, using `buttonText()` brush from palette from `QStyleOptionToolButton`. They are the same, but as you can see, when there is no style applied <ins>4th button is still has wrong colour</ins>, their single difference is that 3rd button is inside `SegmentedButton` (inherits `QWidget`) So, in both cases we have wrong colours in palette.
5 - SearchField with custom stylesheet too;
6 - MenuBar with same problems.

Affected themes are: KvAdapta, KvMojaveMixed, KvMojaveMixed1.

If it is needed, I created [test project](https://github.com/evgeniy-harchenko/kv_bug).

**Comment by tsujan** [comment]
> So, many but not all problems are because of custom stylesheets

Yes, stylesheets can override style colors, and more...

**Comment by evgeniy-harchenko** [comment]
Yes, I got it. stylesheets are only qt-side questions. But what about these buttons?

![image](https://github.com/tsujan/Kvantum/assets/42656259/79c99388-c556-40c3-ad3d-3e8433648797)

I changed [test project](https://github.com/evgeniy-harchenko/kv_bug). Now there are only these two buttons, without any custom stylesheets.
First button uses correct colors from kvantum theme - `text.normal.color` from `Toolbar` section, while second uses `button.text.color` from `GeneralColors` section.

**Comment by tsujan** [comment]
By adding a paint event to a widget, you override QStyle.

**Comment by tsujan** [comment]
A paint event may be needed on many occasions, but then `QStyle` methods should be called; otherwise, problems will be imminent. There is one exception, and that's where a dev wants to draw a widget *completely*. Not only that's a complex job, but also it damages platform integration.

The same is true about style sheets in codes: they should be complete.

Sadly, many devs don't use `QStyle` correctly when they need it. For example (and that's what I've encountered on so many occasions), they may mistake a `QStyle` parameter for a constant: if it's an integer, they assume it's "3"; if it's a color, they assume it's while, etc.

Kvantum includes many workarounds for such issues, but there's no way to circumvent all of them.
