### ISSUE TITLE
Strange header behavior

### ISSUE THREAD

**Issue by evgeniy-harchenko** [tsujan/Kvantum#977]
Some color combinations cause strange header behavior. It is hard to explain, so here is a sample theme: [repo](https://github.com/evgeniy-harchenko/kv_bug/tree/cff709e240d03f9d51fe22a637341d2bc10f2daf/SampleTheme)
(color scheme must be applied too). 

As you can see, some UI elements are shifted left and hover effect is broken. But if I make `button.text.color` in `[GeneralColors]` section in `kvconfig` lighter, e.g. set it to `#75949c` the problem goes away. Also the problem disappears if I make `ForegroundNormal` darker in `[Colors:Header]` section in color scheme file, e.g. set it to `100,100,100`.

Here is the illustration of the problem for better understanding:
<details>
  <summary>Image</summary>
  
![Header](https://github.com/tsujan/Kvantum/assets/42656259/b9e1b1f9-ed5d-403d-9758-26faa041f96e)

</details>

It can be reproduced on any theme. All you need is to make this colors dark/light enough.

**Comment by tsujan** [comment]
> As you can see....

I see nothing strange in kvantumpreview, and I don't know which app is in your screenshot ;) Is that app in QML?

**Comment by tsujan** [comment]
Oh, that's the new System Settings — the ugliest and most unintuitive app I've ever seen ;) It's written in QML.

If you take a look at the KDE "color schemes" that come with Kvantum, you'll see that none of them contains "Header". Whatever they mean by this new section, it isn't compatible with Qt. In no way Kvantum can be responsible for what KDE devs do with their QML styling and "color schemes".

Apparently, you've found a random solution to this mess. Why `ForegroundNormal` has that effect, I don't have any clue, because it isn't a standard Qt color.

**NOTE:** I don't use KDE since they started to make it like a mobile DE (I am an LXQt user and developer), but I have a full Plasma installation and accept bug reports by KDE users. However, as I've emphasized in `Theme-Making.pdf`, KDE developers are responsible for discrepancies in QML apps; Kvantum is a Qt **widget style**.

**Comment by evgeniy-harchenko** [comment]
I’ll leave here a small addition for those who make themes. This problem persists on color schemes without Header section too. Just tested. So, I recommend to choose correct color for `button.text.color` in `[GeneralColors]` section in `kvconfig`.

**Comment by tsujan** [comment]
> I’ll leave here a small addition...

If you use [Discussions](https://github.com/tsujan/Kvantum/discussions) for Plasma issues, they'll be more visible to others.
